### PR TITLE
JP-3609: Change treatment of MIRI MRS values with no photom info

### LINKED ISSUE #8452: MIRI MRS photom should not reset NaN values to unity
_Issue [JP-3609](https://jira.stsci.edu/browse/JP-3609) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

At present, MIRI MRS photom code explicitly ignores NaN-valued photom entries and resets these to one when applying the photometric calibration.  As a result, the cal.fits files have bogus values in the between-slice regions.  Following the spirit of <https://jira.stsci.edu/browse/JP-3570> and the approach used for MIRI LRS and NIRSpec, this code should be removed so that between-valued slices are NaN-valued in cal files.

### PR DESCRIPTION
**Pull request by drlaw1558**
Resolves [JP-3609](https://jira.stsci.edu/browse/JP-3609) by ensuring that for MIRI MRS pixels with NaN-valued photometric correction, the resulting cal file contains NaN values instead of code hard-resetting calibration factors to unity.  This keeps the SCI array consistent with the ERR and VAR arrays.

This change should have no effect on the s3d and x1d results, since the affected pixels are always skipped by cube building anyway.

Closes #8452 

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by jemorrison — APPROVED** [review]
This is needed and should help outlier detection. Plus it is just the correct thing to do

**Comment by jemorrison** [comment]
@drlaw1558 have you run the regression tests yet. Probably need to update some of the truth files

**Comment by drlaw1558** [comment]
@jemorrison No, I haven't run the regression tests.  Not sure how to do that.

**Review by hbushouse — COMMENTED** [review]
Code changes look fine. Will withhold final approval until we see regtest results.

**Comment by hbushouse** [comment]
Started a regtest run at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1423

**Review by hbushouse — APPROVED** [review]

**Pull request merged**
