### PR TITLE
JP-3471 improve Step.spec attribute formating in docs

### LINKED ISSUE #8085: Atributes documenation in most steps appear garbled
_Issue [JP-3471](https://jira.stsci.edu/browse/JP-3471) was created on JIRA by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz):_

I found what appears to be a bug, but probably a change, in the way Sphinx is pulling the triple quoted comments from the "Attributes Documentation" for many of the steps. It is adding returns and spaces literal, making this section almost unreadable. 

Examples are these two cases, but there are many more.

+  <https://jwst-pipeline.readthedocs.io/en/latest/api/jwst.cube_build.cube_build_step.CubeBuildStep.html> 

+ <https://jwst-pipeline.readthedocs.io/en/latest/jwst/tweakreg/tweakreg_step.html>

### PR DESCRIPTION
**Pull request by braingram**
Resolves [JP-3471](https://jira.stsci.edu/browse/JP-3471)

Closes #8085

This PR adds a custom `AttributeDocumenter` subclass to control the formatting of the long `Step.spec` string in the sphinx documentation.

For one example see the OutlierDetectionStep spec:
https://jwst-pipeline.readthedocs.io/en/latest/api/jwst.outlier_detection.OutlierDetectionStep.html#jwst.outlier_detection.OutlierDetectionStep.spec

and with this PR:
https://jwst-pipeline--8101.org.readthedocs.build/en/8101/api/jwst.outlier_detection.OutlierDetectionStep.html#jwst.outlier_detection.OutlierDetectionStep.spec

To update the formatting outside of `api` a few uses of `automodule` are replaced with `automodapi`:
- tweakreg: https://jwst-pipeline--8101.org.readthedocs.build/en/8101/jwst/tweakreg/index.html
- skymatch: https://jwst-pipeline--8101.org.readthedocs.build/en/8101/jwst/skymatch/index.html
- mrs_imatch: https://jwst-pipeline--8101.org.readthedocs.build/en/8101/jwst/mrs_imatch/index.html#module-jwst.mrs_imatch

One change to the code was necessary (adding an `__all__` to `jwst/tweakreg/astrometric_utils.py` to allow `automodapi` to pick up the documentation for `TIMEOUT` see: https://jwst-pipeline--8101.org.readthedocs.build/en/8101/jwst/tweakreg/astrometric_utils.html#variables).

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [x] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by mcara — APPROVED** [review]
Oh wow! I am impressed!

**Comment by hbushouse** [comment]
Wow, the docs now look great!  Nice job.

But what's causing all the CI tests to fail in the jwst/tweakreg/tests/test_amutils.py test module?

**Comment by braingram** [comment]
Thanks for pointing that out!
I also saw a SSL warning in the logs so I'm thinking the service where the catalogs are downloaded from dropped the ball (perhaps due to the other network issues yesterday).
I didn't see those failures in earlier runs or locally. I closed and reopened this to trigger the CI.

**Review by hbushouse — APPROVED** [review]
OK, looks good now.

**Pull request merged**
