### PR TITLE
Unpin pytest=3.8.2 and numpy=1.15.2 to pick up latest

### PR DESCRIPTION
**Pull request by jdavies-st**
The bugs in `pytest 3.9` where the _tmpdir_ fixture was broken seem to be resolved in `pytest 3.10`, so I'm now unpinning it in our CI and RT build scripts.

### CODE REVIEW

**Comment by hbushouse** [comment]
Partially addresses #2838. Still need to unpin numpy some time.

**Comment by jdavies-st** [comment]
Added unpinning `numpy` to this PR.  I've been testing locally with it for a week and it seem fine.  `astropy` has also unpinned their `numpy`, so we certainly won't get the conda build error anymore in our CI and RT tests.

**Comment by pllim** [comment]
Try to rerun with pytest 4.0 and see...

**Comment by pllim** [comment]
Don't do eeet.... pytest-dev/pytest#4425

**Comment by pllim** [comment]
(Also the title is wrong... it should be numpy=1.15...)

**Comment by pllim** [comment]
p.p.s. I have nothing against numpy upgrade. But you might want to pin to pytest 3.10 instead of letting it up all the way to 4.0.

**Comment by jdavies-st** [comment]
I've been using `pytest 4.0` since it was out, and I've seen no issues with either our CI or RT tests.  I suspect whatever bug is listed above, that we don't see that usage in our code.  So I'm merging.

**Pull request merged**
