### PR TITLE
JP-2509 Update COARSE algorithm to use FGS1 exclusively

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Closes #
Resolves [JP-2509](https://jira.stsci.edu/browse/JP-2509)

**Description**

This PR updates the default COARSE tracking algorithm, COARSE_TR_202111, to use FGS1 exclusively.

Checklist
- [ ] Tests
- [ ] ~~Documentation~~
- [x] Change log
- [ ] Milestone
- [x] Label(s)

### CODE REVIEW

**Review by hbushouse — APPROVED** [review]
Have no idea what things like `t_pars.pointing._fields` are or how they're used, but I'll take your word for it.

**Comment by bhilbert4** [comment]
I can test this out on the NRC-03 data. I just need to know how to run it on existing uncal files.

**Comment by stscieisenhamer** [comment]
@bhilbert4 The command is `set_telescope_pointing.py`. You will need to have the environmental MAST_API_TOKEN set.  See the following for more details:

https://jwst-pipeline.readthedocs.io/en/latest/jwst/lib/engdb.html

https://jwst-pipeline.readthedocs.io/en/latest/jwst/lib/set_telescope_pointing.html#commands

**Comment by stscieisenhamer** [comment]
One failure is the usual crds/CI issue. Going ahead with the merge.

**Pull request merged**
