### PR TITLE
Fixed filename conflicts in badpix_selfcal test

### PR DESCRIPTION
**Pull request by emolter**
JIRA ticket N/A

GitHub issue N/A

This PR addresses persistent regression test failures in `test_miri_mrs_badpix_selfcal`.  These were caused by two tests writing their outputs to the same filename, making it so that the ok-ify script was not picking up the correct output file when attempting to update the truth file.  This PR specifies unique file names for the two conflicting tests.

## Tasks
- [x] **request a review from someone specific**, to avoid making the maintainers review every PR
- [ ] add a build milestone, i.e. `Build 11.3` (use the [latest build](https://github.com/spacetelescope/jwst/milestones) if not sure)
- [ ] Does this PR change user-facing code / API?
  - [ ] add an entry to `CHANGES.rst` within the relevant release section (otherwise add the `no-changelog-entry-needed` label to this PR)
  - [x] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [x] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [x] Do truth files need to be updated ("okified")?
      - [x] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by tapastro** [comment]
Ran the tests to generate an okify target - https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1718/
You may want to delete the old truth files if/when you get a chance, as they may just sit there stale if you don't.

**Comment by emolter** [comment]
New regtests for just `test_miri_mrs_badpix_selfcal` after uploading the new truth files to artifactory and deleting the old ones: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1720/

**Comment by emolter** [comment]
Those regression tests passed, so I think this is good to go

**Review by tapastro — APPROVED** [review]
Looks good!

**Pull request merged**
