### PR TITLE
Jp 681

### PR DESCRIPTION
**Pull request by ddavis-stsci**
Updates so that only nodded observations have x1d products listed as background  & if there is only one science member do not have it be its own background.

### CODE REVIEW

**Comment by ddavis-stsci** [comment]
Note: The unit test test_level3_spectrographic.py is failing. I think that the new association rules are generating an additional level3 association and the test is only expecting two. 
`AssertionError: /Users/ddavis/src/JWST/scsb/jwst/jwst/associations/tests/data/pool_007_spec_miri.csv: n_asns not expected 2 3`

**Comment by ddavis-stsci** [comment]
Program 00623  with MIRI LRS data still produces an association with 12 _cal products as science and 12 _x1d products listed as background.

**Comment by nden** [comment]
Are these failures expected?

**Comment by stscieisenhamer** [comment]
This one dropped from my radar. Will look today.

**Pull request merged**
