### PR TITLE
reducing running time for EMICORR step

### PR DESCRIPTION
**Pull request by penaguerrero**
This PR fixes some remaining issues with the emicorr step when it doesn't find matching mode info in the reference file or have info itself for a given mode, as well as optimizing (and hence speeding up) some of the slower parts of the algorithm.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by hbushouse** [comment]
Regression test running at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1111/

**Comment by hbushouse** [comment]
> Regression test running at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1111/

Finished successfully with no errors or differences.

**Comment by braingram** [comment]
My curiosity got the best of me and I started looking at this step. Are there specific parts of the step that are taking longer than others? I have a few questions/comments about the cross correlation:
https://github.com/spacetelescope/jwst/blob/c357f755015f441cd780953b94425abcfb02de5d/jwst/emicorr/emicorr.py#L429-L433

`cc` above appears to be used to find the best lag between the reference and rebinned phase array (please correct me if I'm wrong here or anywhere in these comments, it's my first time looking at the step). Would it be suitable to swap this with a call to [numpy.correlate](https://numpy.org/doc/stable/reference/generated/numpy.correlate.html)? Something like:
```python
cc = numpy.correlate(np.hstack((reference_wave, reference_wave[:-1]), rebinned_pa, 'valid')
```
This would produce an unnormalized `cc` but the index of the max value should be the same. On my machine with a 500 element reference_wave (based off the size in the reference file) the `correlate` call takes around 30 microseconds whereas the looped normalized cross correlation (the current code) takes ~23 milliseconds.

Next in this section (where `cc` is used):
https://github.com/spacetelescope/jwst/blob/c357f755015f441cd780953b94425abcfb02de5d/jwst/emicorr/emicorr.py#L439-L440
what about changing the `where` call to `argmax`? If for some reason `cc` contains 2 'max' values the `where` call will return a 2 length array. When this is provided to `roll` it rolls the array twice (once for each value). So if the `where` call returns `[1, 3]` the roll will shift the array 4 elements.

**Comment by penaguerrero** [comment]
At this point I don't want to experiment with the correlation lines because we have vetted the current code. However I did change the where for argmax and confirmed there is no difference in the output file.

**Comment by hbushouse** [comment]
@penaguerrero Are you done with adding little changes yet?  Need to know if/when we can merge this, in order to make a 1.13.2 release.

**Comment by penaguerrero** [comment]
yes, now I'm done :P

**Comment by hbushouse** [comment]
Regression test run started at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1115

**Comment by hbushouse** [comment]
I've just confirmed that this branch now runs properly with the datasets that SDP had trouble with in their recent tests of jwst 1.13.1.

**Review by hbushouse — APPROVED** [review]

**Comment by hbushouse** [comment]
Regtests show no errors, so I'm merging.

**Pull request merged**
