### PR TITLE
Calibration changed from dividing to multiplying across all modes.

### PR DESCRIPTION
**Pull request by dmggh**
This is part of the work needed to support JP-988 and JP-796.

### CODE REVIEW

**Comment by stscicrawford** [comment]
I'm just marking this as 'Do not merge' until we have the regression tests passing as this will likely cause failures there as we do not have the new photom reference files submitted yet either.   So this will have to be merged coordinated with that work.

**Comment by philhodge** [comment]
> This will need unit tests updated and a change log

There are comments in test_photom.py regarding the changes that are needed when replacing division with multiplication.

**Comment by hbushouse** [comment]
Still just needs a change log entry.

**Comment by dmggh** [comment]
Updated change log.

**Comment by stscicrawford** [comment]
Closing as this has been incorporated into #4118

**Pull request closed without merging**
