### PR TITLE
Update log messages containing newlines

### PR DESCRIPTION
**Pull request by melanieclarke**
This PR updates any log messages currently containing newlines, replacing them instead with multiple log messages.  This is a pre-requisite to removing the problematic MultiLineLogger (e.g. #8694), which automatically splits these messages into multiple log messages.

To find these messages, I reviewed every instance of '\n' in the jwst code base and updated code for any that appeared in log messages.  I have tested most of the changes from the command line to make sure they look right, and will run regression tests to make sure they don't break anything.

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] ~added entry in `CHANGES.rst` within the relevant release section~
- [ ] ~updated or added relevant tests~
- [ ] ~updated relevant documentation~
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [x] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by melanieclarke** [comment]
Regtests here:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1637/

**Comment by melanieclarke** [comment]
@braingram - here are the changes I think are needed to update log messages prior to removing the MultiLineLogger.  Let me know what you think.

**Comment by braingram** [comment]
I think it's best if someone else review this as I think we disagree on the approach. I understand your reasons for wanting to update the log messages so users don't see different log messages but I don't think it's possible or worth the risk since it requires changes to log messages which are largely uncovered (this patch shows 16% coverage).

I do not think there is any way we can update these log messages to reproduce the buggy logs caused by `MultilineLogger`. To expand on the `DarkCurrentStep.log` issue brought up in #8694 If created outside the detector1 pipeline, the log messages will not be split on newlines. However if created in the detector1 pipeline the log messages will be split. If the goal is 0 change to the log output we can't remove `MultilneLogger`.

**Comment by melanieclarke** [comment]
Okay thanks, I'll can assign a different reviewer if you like.

But to clarify - my goal is not zero change to the log messages, it's to make sure we don't print newlines to the log.  It's poor form, which is probably why the MultiLineLogger existed in the first place.  Whether or not we follow this up with removing the MultiLineLogger is a separate issue.

**Review by tapastro — APPROVED** [review]
LGTM - once this is in and we're reasonably convinced we're not logging any newlines, we can move forward with the MultiLineLogger removal.

**Pull request merged**
