### PR TITLE
Fix void pointer arithmetic in tweakreg

### PR DESCRIPTION
**Pull request by mcara**
Fixes compiler errors on Windows (VS compiler). Related to https://github.com/spacetelescope/drizzlepac/pull/258/commits/92f65dee7daa4c864adb1645af393e285120fa81

### CODE REVIEW

**Comment by jdavies-st** [comment]
Thanks @mcara.  Could you rebase (or merge) this branch against `master`.  It will pick up the CI changes and hopefully the Jenkins CI tests will pass.

**Comment by mcara** [comment]
@jdavies-st Now checks seem to pass.

**Comment by jdavies-st** [comment]
If you want to run the regression test locally:
```
export TEST_BIGDATA=https://bytesalad.stsci.edu/artifactory/
pytest --bigdata --basetemp=/path/to/temp/outputdir jwst/tests_nightly/general -k image3_pipeline2
```

**Comment by mcara** [comment]
@jdavies-st Thanks! The latest commit should take care of this bug.

**Comment by jdavies-st** [comment]
That fixes it.  Thanks @mcara.

Any chance we can get a simple unit test for this function?  Or shall we merge this and do that another time?

**Pull request merged**
