### PR TITLE
Update infrastructure files to include emicorr

### PR DESCRIPTION
**Pull request by hbushouse**
This PR adds entries for the new emicorr step to a couple of infrastructure files, in order to get unit tests to pass everywhere.

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by braingram** [comment]
To check that I understand these changes. Prior to this PR `emicorr` would not run via the cli (`strun emicorr ...`) as the step alias was not added to [get_steps](https://github.com/spacetelescope/jwst/blob/master/jwst/stpipe/integration.py) which is fixed in this PR. Adding the step to `get_steps` also requires adding it to `jwst.step.__all__` due to this test https://github.com/spacetelescope/jwst/blob/02a3f2ebcc56ba5eb9f52f38dc74262a6db09a6a/jwst/stpipe/tests/test_integration.py#L13 which compares `__all__` and the output of `get_steps`. Is this correct?

**Comment by hbushouse** [comment]
> To check that I understand these changes. Prior to this PR `emicorr` would not run via the cli (`strun emicorr ...`) as the step alias was not added to [get_steps](https://github.com/spacetelescope/jwst/blob/master/jwst/stpipe/integration.py) which is fixed in this PR. Adding the step to `get_steps` also requires adding it to `jwst.step.__all__` due to this test
> 
> https://github.com/spacetelescope/jwst/blob/02a3f2ebcc56ba5eb9f52f38dc74262a6db09a6a/jwst/stpipe/tests/test_integration.py#L13
> 
> which compares `__all__` and the output of `get_steps`. Is this correct?

You are correct, sir. Without this change, executing "strun emicorr ..." results in "ValueError: 'emicorr' is not a path to a config file or a Python Step class". With this change, it runs just fine.

**Comment by hbushouse** [comment]
> LGTM!
> 
> Is it worth looking into adding a test to catch this type of omission for future step additions? Perhaps iterating through `Step` and `Pipeline` subclasses checking that all are registered?

Good question. We seem to have run into this issue twice in the past 1-2 weeks when brand new steps got merged. The CI tests did not reveal any failures (not sure why). It's not until we run a full regtest that suddenly we see 1 or 2 unit tests failing, because of the missing suffix or step name in tests like this. I would've thought that the unit tests would get run by at least some of the CI's.

**Review by zacharyburnett — APPROVED** [review]
LGTM when build CI passes

**Comment by zacharyburnett** [comment]
I think this should be good to merge now, the ARM64 builds are just taking a while but I assume they will pass

**Pull request merged**
