### PR TITLE
fix for running cube build in spec2 on a list of files

### LINKED ISSUE #5115: cube build crashes with Lvl2 association files
_Issue [JP-1560](https://jira.stsci.edu/browse/JP-1560) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

When testing spec2 associations I noticed that they cause cube building to crash with incorrect channel configurations.  Although running each rate file through calwebb_spec2 individually works fine, running the association file through calwebb_spec2 does not.  It works ok up to the _cal.fits stage if I disable cube build and extract1d, but not if those two steps are on.

Error message for the crash is:

2020-06-30 12:48:18,511 - stpipe.Spec2Pipeline.photom - INFO - Step photom done
2020-06-30 12:48:18,771 - stpipe.Spec2Pipeline.cube_build - INFO - Step cube_build running with args (<IFUImageModel(1024, 1032) from det_image_seq4_MIRIFULONG_34LONGexp1_cal.fits>,).
Traceback (most recent call last):
 File "/Users/drlaw/jwcode/jwst/jwst/pipeline/calwebb_spec2.py", line 95, in process
 asn.filename
 File "/Users/drlaw/jwcode/jwst/jwst/pipeline/calwebb_spec2.py", line 306, in process_exposure_product
 result_extra = self.cube_build(result)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 357, in run
 f'Step \{self.name} parameters are: \{self.get_pars()}'
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 1221, in get_pars
 pars = config_parser.config_from_dict(instance_pars, spec, allow_missing=True)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/config_parser.py", line 301, in config_from_dict
 validate(config, spec, root_dir=root_dir, allow_missing=allow_missing)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/config_parser.py", line 390, in validate
 raise ValidationError('\n'.join(messages))
jwst.stpipe.config_parser.ValidationError: Config parameter 'channel': the value "" is unacceptable.
Config parameter 'filter': the value "" is unacceptable.
Config parameter 'grating': the value "" is unacceptable.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
 One or more products failed to process. Failing calibration.
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/Users/drlaw/jwcode/jwst/scripts/strun", line 26, in <module>
 step = Step.from_cmdline(sys.argv[1:])
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 156, in from_cmdline
 return cmdline.step_from_cmdline(args)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
 step.run(*positional)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 392, in run
 step_result = self.process(*args)
 File "/Users/drlaw/jwcode/jwst/jwst/pipeline/calwebb_spec2.py", line 111, in process
 'One or more products failed to process. Failing calibration.'
RuntimeError: One or more products failed to process. Failing calibration.

### PR DESCRIPTION
**Pull request by jemorrison**
This fixes problems that were encountered when trying to run the `calwebb_spec2` pipeline on an ASN file that contains a list of multiple products, in which case the pipeline loops over the processing for each product one at a time. The `cube_build` step was failing on the 2nd iteration (processing for the 2nd product) due to step param values having been modified during the 1st iteration.

Fixes [JP-1560](https://jira.stsci.edu/browse/JP-1560)
Fixes #5115

### CODE REVIEW

**Comment by tapastro** [comment]
Thanks for helping out Jane, I appreciate it! 

I tried your changes, and it runs appropriately using the default calwebb_spec2.cfg. I tried setting a user-defined value at the command line, trying --steps.cube_build.channel==3. It returns errors:

Config parameter 'output_type': the value "user" is unacceptable. I'll look into it tomorrow, but just putting this out there in case you see something is up.

**Comment by jemorrison** [comment]
the option needs to be --steps.cube_build.channel=3 (only one =)

**Comment by jemorrison** [comment]
Ok I get your error now. I see the problem. I pull push over another change

**Comment by jemorrison** [comment]
The code changes some of the values in cube_build_step in the spec depending on the data or other user options. But if they are changed the next time around the defaults in the spec are not used by the values from the previous run are used. I did not realize that was how the values in the spec work. I wonder if I can override this feature some how.

**Review by hbushouse — COMMENTED** [review]
Needs a description and change log entry

**Comment by hbushouse** [comment]
Also a flake8 error that needs fixing

**Review by tapastro — APPROVED** [review]
Testing this with defaults and with a command-line-defined value for channel both worked; I'm not sure if there's a way for a user to select a value for only some association files, but otherwise this looks good to me!

**Review by hbushouse — APPROVED** [review]

**Pull request merged**
