### PR TITLE
JP-3601: Fix background interval edge case

### LINKED ISSUE #8431: Extraction background edge case bug
_Issue [JP-3601](https://jira.stsci.edu/browse/JP-3601) was created on JIRA by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke):_

While experimenting with setting polynomial background regions in extract_1d for BOTS data, I came across a crash when background upper and lower limits are both out of range for some part of the array.  This happens when setting a region above and below the curved spectral trace in a narrow subarray: there is data within the background limits for part of the array, but not the full array.  In this case, the limits are checked and both upper and lower limits are set to the edge of the array (0 at the bottom, ns at the top).

The crash comes from line 702 in jwst/extract_1d/extract1d.py:

IndexError: index 6 is out of bounds for axis 0 with size 6

I think the problem is that when counting intervals (npts, line 680), intervals with equal upper and lower limits are not counted, but when computing background levels, the value at that point is added to the val array (line 702).  I think the fix should be to skip intervals for which upper and lower limits are equal – it is not likely that that point contains a valid background level anyway.

### PR DESCRIPTION
**Pull request by melanieclarke**
Resolves [JP-3601](https://jira.stsci.edu/browse/JP-3601)

Closes #8431 

This PR fixes a crash in an extraction background edge case, in which both lower and upper limits for the background region are outside the valid area for some data range.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by melanieclarke** [comment]
In testing, the initial simple fix was a little too simple: it did not handle correctly the cases where part of a pixel falls within the specified region, or the case where an empty interval is specified, but the limits are within range of the data.  The updated version should now handle both of those cases correctly, as well as fixing the original crash.

**Review by nden — COMMENTED** [review]
I am not familiar with extract_1d at that level of detail but the changes seem to address the ticket. Is there a reasonable tests to add?

I started a regression test run here https://github.com/melanieclarke/jwst.git

**Comment by melanieclarke** [comment]
Thanks @nden - I'll see if I can add some unit tests to cover the relevant cases.

**Comment by melanieclarke** [comment]
@nden - unit tests added for a couple relevant cases in background and source extraction.

Looking at the regression tests, it looks like the test_nirspec_fs_spec3[s00024-s1600a1-x1d] failure is the only relevant change.  For this spectral extraction, the WCS is invalid: all wavelengths are set to NaN and the extraction region is out of range.   The old version defaulted the flux to 0.0 and the errors to NaN in this case; the new version defaults the flux to NaN and the errors to 0.0.  I think the new version is closer to the intended default values.

**Review by hbushouse — APPROVED** [review]
Looks good to me. I'll take your word that the new regtest result is the more appropriate result.

**Pull request merged**
