### PR TITLE
JP-3128: Fix memory leaks in C code

### PR DESCRIPTION
**Pull request by mcara**
Resolves [JP-3086](https://jira.stsci.edu/browse/JP-3086)
Resolves [JP-3128](https://jira.stsci.edu/browse/JP-3128)

This PR fixes memory leaks in C code due to incorrect reference count of returned arrays. This PR addresses a part of #7483 (other improvements in that PR should be merged after that PR is re-based after this PR is merged). Affected packages are: ``cube_build``, ``wfss_contam``, and ``straylight``.

This PR implements the recommendation from https://numpy.org/doc/stable/user/c-info.how-to-extend.html:

> The [Py_BuildValue](https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue) (format_string, c_variables…) function makes it easy to build tuples of Python objects from C variables. **Pay special attention to the difference between ‘N’ and ‘O’ in the format string or you can easily create memory leaks.** The ‘O’ format string increments the reference count of the [PyObject](https://docs.python.org/3/c-api/structures.html#c.PyObject) C-variable it corresponds to, while **the ‘N’ format string steals a reference to the corresponding [PyObject](https://docs.python.org/3/c-api/structures.html#c.PyObject) C-variable. You should use ‘N’ if you have already created a reference for the object and just want to give that reference to the tuple.** You should use ‘O’ if you only have a borrowed reference to an object and need to create one to provide for the tuple.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

Regression test: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/598/

### CODE REVIEW

**Comment by mcara** [comment]
I do not see any _new_ failures in the regression tests that I could attribute to the changes proposed in this PR but all tests run in the last month had failures.

**Review by hbushouse — APPROVED** [review]
Changes look good to me (very straightforward), and I agree that the failures in the regtest run are unrelated (the truths have since been updated).

Would be nice if someone's got the time to run this PR branch against one of the MIRI MRS mosaics that had been a big memory hog, to verify the same memory reduction as the PR submitted by @jemorrison.

**Comment by hbushouse** [comment]
Does this really fix [JP-3016](https://jira.stsci.edu/browse/JP-3016), which is not related to memory leaks?

**Comment by mcara** [comment]
No. My bad

**Comment by mcara** [comment]
And https://github.com/spacetelescope/jwst/pull/7483 should be rebased after this one is merged.

**Comment by mcara** [comment]
> Would be nice if someone's got the time to run this PR branch against one of the MIRI MRS mosaics that had been a big memory hog, to verify the same memory reduction as the PR submitted by @jemorrison.

From https://github.com/spacetelescope/jwst/pull/7483#issuecomment-1464233450 see:

> I changed how I am using Py_Build and using N rather than 0. The memory does seem to freed up better now, but in the test I have done the memory usage is about as good as this PR.

**Comment by mcara** [comment]
Screen Shot 2023-03-14 at 9 58 40 AM

The bot keeps removing the relevant label

**Review by drlaw1558 — APPROVED** [review]
Looks like this is working well.  I tested that (as expected) results from the straylight step are identical before/after the change.  I also tested trying to build a large (78 input files) cube that would ordinarily crash my laptop.  With the current pipeline memory usage grew to about 120 GB before crashing; with this branch memory usage topped out about 17 GB and successfully built the cube.

**Comment by hbushouse** [comment]
OK, it sounds like everyone is on-board with this so I'm going to merge. Will need to coordinate with @jemorrison 's PR once she gets back.

**Comment by jemorrison** [comment]
@hbushouse @mcara @drlaw1558 
Looks like you solved the problem much easier than what I had done. Thanks a ton @mcara. The old PR did a few things that may not be needed at all. It added an option (like outlier detection had) 'in_memory" which if the memory needed was too large it would write the data to disk and then open each file and work with the data. It takes longer to do this. Is this something we might still need - it is only used if 'in_memory = FALSE' (by default it is True).  I will test the updated cube_build and that super large set (over 500 files) and see if helps. This 'in_memory' option also added writing out the IFU cubes to disk as they were created and passed the filenames to extract1d. Again not sure if that is needed.

**Comment by mcara** [comment]
> The old PR did a few things that may not be needed at all. It added an option (like outlier detection had) 'in_memory" which if the memory needed was too large it would write the data to disk and then open each file and work with the data. It takes longer to do this. Is this something we might still need - it is only used if 'in_memory = FALSE' (by default it is True). I will test the updated cube_build and that super large set (over 500 files) and see if helps. This 'in_memory' option also added writing out the IFU cubes to disk as they were created and passed the filenames to extract1d. Again not sure if that is needed.

Why not? If this is a  good option to decrease memory usage and the code is already written - I think you should consider it. Also, it may still be worth moving memory allocation to Python if that memory can be re-used between the calls in a loop (if there is one). I am not that familiar with the code to give my opinion on it.

My only comment about the other PR (which I think should be rebased and reviewed again) was that there were a couple of places in which I thought the code could crash and in the other places it was creating new arrays when I thought those could be reused. I think it may be worth pursuing it. This PR was a stop-gap fix to give more time to review the other one.

**Pull request merged**
