### PR TITLE
Jump step num cores doc update

### PR DESCRIPTION
**Pull request by mwregan2**
This PR allows the new maximum_cores values to be accepted to be able to pass the value to the STCAL jump.py routine. Read_the_docs was updated to match the new options. 

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [x] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by hbushouse** [comment]
CI tests are showing these errors:
` FAILED jwst/jump/tests/test_jump_step.py::test_one_CR[2] - UnboundLocalError: local variable 'n_slices' referenced before assignment
  FAILED jwst/jump/tests/test_jump_step.py::test_nircam[2] - UnboundLocalError: local variable 'n_slices' referenced before assignment
  FAILED jwst/jump/tests/test_jump_step.py::test_two_CRs[2] - UnboundLocalError: local variable 'n_slices' referenced before assignment
  FAILED jwst/jump/tests/test_jump_step.py::test_snowball_flagging_nosat - UnboundLocalError: local variable 'n_slices' referenced before assignment
  FAILED jwst/jump/tests/test_jump_st`

**Comment by mwregan2** [comment]
Howard,

  This is some kind JWST/STCAL issue. This JWST PR matches the STCAL dev repo. How do I get them to both work?
Mike



________________________________

**Comment by mwregan2** [comment]
It needs the stcal/main version of the code.

________________________________

**Comment by hbushouse** [comment]
> It needs the stcal/main version of the code.

OK, that's what I figured. In that case we can just ignore the CI failures, because we understand why they're happening.

**Review by hbushouse — APPROVED** [review]

**Comment by hbushouse** [comment]
I'll confirm that everything's OK by running the regression tests against this PR branch, which will use stcal/main, and hence they should not have any problems (theoretically).

**Comment by hbushouse** [comment]
Regression test running at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/909

**Comment by hbushouse** [comment]
Regtest run was completely successful and it includes all the unit tests, but builds using stcal/main, so it doesn't encounter the problems seen in the CI tests here.

**Pull request merged**
