### PR TITLE
JP-1090: Remove setLevel calls

### LINKED ISSUE #4182: Remove all explicity logging.setLevel calls
Issue [JP-1090](https://jira.stsci.edu/browse/JP-1090) was created by Jonathan Eisenhamer:

The whole of JWST code is littered with logging.setLevel calls, short-circuiting any usefullness of the logging facility.

Remove them. Just remove them...please...gone...go...squashed...

### PR DESCRIPTION
**Pull request by jwhite3**
This PR removes most `setLevel` calls from the project files with the exceptions in `stpipe.log.py` and `stpipe.tests.steps.local.py`

Resolves #4182 / [JP-1090](https://jira.stsci.edu/browse/JP-1090)

### CODE REVIEW

**Comment by hbushouse** [comment]
Does this still allow DEBUG-level messages to be emitted from individual steps when calling `strun` with the `-v` or `--debug` arguments?

**Comment by jwhite3** [comment]
@hbushouse I believe so. From what I understand, those `setLevel` calls were effectively overriding the logging utility in `jwst.stpipe.log.py`

I could be wrong though, so I tagged @stscieisenhamer for a review since he file the issue this is in reference to

**Comment by jdavies-st** [comment]
Yup, logging still works fine with `strun` and running from within python.  Behavior is not changed.  If we do want behavior changed, we will have to fix the stpipe logging config.

So in the future we will have to fix the logging config if we want to be able to run within python and use `setLevel` interactively in the shell or a notebook to control the amount of logging.

**Comment by jwhite3** [comment]
@jdavies-st couldn't you still do that by hijacking the logger with `log = getLogger()` and then `log.setLevel(...)`? I supposed you'd need to know the name though

**Comment by jdavies-st** [comment]
Doing

```
import logging
log = logging.getLogger(__name__)
log.setLevel("WARNING")
```

doesn't work.  But something similar should.  Yeah, not sure what the name should or would be.  @stscieisenhamer ?

**Comment by jdavies-st** [comment]
Ah, but what does work now is:

```
import logging
log = logging.getLogger("stpipe")
log.setLevel("ERROR")
```

:tada:

**Comment by jdavies-st** [comment]
Well, I should clarify.  It now works for any log messages emitted by `stpipe` and it's subclasses.  But for log messages emitted by `crds` or `datamodels`, it does nothing.

So in addition to this PR, we should think about how we want to configure a top-level logger for the package, if needed.  Or have our datamodels use the `stpipe` logger.  Or something else?

I think this PR is fine as-is though.

**Comment by jwhite3** [comment]
Yep for those, you'd need to change the settings individually, but I _think_ that other stuff (like steps and whatnot) would get that level change right?

**Comment by jdavies-st** [comment]
So there is a top-level `jwst` logger.  And also a `CRDS` one.  So if one sets those levels to ERROR or CRITICAL, one can get quiet operation now.

```
logging.getLogger("CRDS").setLevel("CRITICAL")
logging.getLogger("tweakwcs").setLevel("ERROR")
logging.getLogger("jwst").setLevel("ERROR")
```

:tada:

**Comment by stscieisenhamer** [comment]
So, this PR is good to go, as far as what the issue was discussing. There is more to be said but realized this is not the place. However...

@jwhite3: Suggested reading: The [documentation about logging](https://jwst-pipeline.readthedocs.io/en/latest/jwst/introduction.html#logging-configuration). Note: This is supposedly the "official" way that logging was to be handled by STPIPE; all this normal, standard log stuff was not supposed to be used. Then review issues #2159, #2390, JP-564, JP-579.

The ultimate goal is to find a path back towards more standard log handling. Discussions will be had.

**Pull request merged**
