### PR TITLE
Allow jsonschema 3.0 as a dependency

### LINKED ISSUE #3865: Allow use of jsonschema 3.0
`asdf` (in dev) provides support for `jsonschema>=3.0`.  This packages should do the same, as it provides `AsdfExtension` subclasses to read JWST data.

Some details on the issue here

https://github.com/spacetelescope/asdf/pull/684#issuecomment-515732325

### PR DESCRIPTION
**Pull request by jdavies-st**
`asdf` dev allows this now.  Let's see if this works on the `jwst` side now, or see if it needs to wait for a release of `asdf`.

Resolves #3865

### CODE REVIEW

**Comment by jdavies-st** [comment]
As I suspected, we will have to wait until there's a release of `asdf` with support for `jsonschema 3.0` to merge this.

**Comment by pllim** [comment]
Maybe also add a regression test for this `jwst`, `asdf`, and `jsonschema` combo?

**Comment by jdavies-st** [comment]
`asdf 2.4.x` has been released, so this can now be merged.

**Comment by jdavies-st** [comment]
It might be good to also specify `asdf>=2.4` here as well?

**Comment by stscieisenhamer** [comment]
@nden is this one good now?

**Pull request merged**
