### PR TITLE
JP-3665: fix calwebb_tso3 failures for SOSS data in FULL subarray

### LINKED ISSUE #8581: calwebb_tso3 failures for SOSS data in FULL subarray
_Issue [JP-3665](https://jira.stsci.edu/browse/JP-3665) was created on JIRA by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter):_

Operations recently had some more NIRISS SOSS full-frame exposures cause errors in processing, but this time the failure is in the TSO3 pipeline, as opposed to Spec2. See <https://jira.stsci.edu/browse/JSDP-2890> The problem is no doubt related to [JP-3662](https://jira.stsci.edu/browse/JP-3662) because the data are again full-frame readouts, but this time they were at least taken in TSO mode (TSOVISIT=True). But because the Spec2 pipeline is not creating extracted 1-D spectra, the inputs to the Tso3 pipeline again don't contain a "spec" attribute (it's still an image, instead of a spectrum).The logs have the following info:
```java
jw02113002001_02101_00001-seg001_nis_calints.fits {'META.EXPOSURE.READPATT [READPATT]': 'NISRAPID', 'META.EXPOSURE.TYPE [EXP_TYPE]': 'NIS_SOSS', 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NIS', 'META.INSTRUMENT.FILTER [FILTER]': 'CLEAR', 'META.INSTRUMENT.LAMP_STATE [LAMP]': 'NONE', 'META.INSTRUMENT.NAME [INSTRUME]': 'NIRISS', 'META.INSTRUMENT.PUPIL [PUPIL]': 'GR700XD', 'META.OBSERVATION.DATE [DATE-OBS]': '2023-09-28', 'META.OBSERVATION.TIME [TIME-OBS]': '17:17:07.854', 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL', 'META.VISIT.CROWDED_FIELD [CROWDFLD]': 'F', 'META.VISIT.TSOVISIT [TSOVISIT]': 'T', 'META.VISIT.TYPE [VISITYPE]': 'PRIME_TARGETED_FIXED', 2024-06-19 11:45:23,281 - stpipe.Tso3Pipeline.extract_1d - INFO - Step extract_1d running with args (<CubeModel(10, 2048, 2048) from jw02113002001_02101_00001-seg001_nis_calints.fits>,). 2024-06-19 11:45:23,290 - stpipe.Tso3Pipeline.extract_1d - INFO - Input is a NIRISS SOSS observation, the specialized SOSS extraction (ATOCA) will be used. 2024-06-19 11:45:23,290 - stpipe.Tso3Pipeline.extract_1d - INFO - Exposure is through the GR700XD + CLEAR (science). 2024-06-19 11:45:23,290 - stpipe.Tso3Pipeline.extract_1d - ERROR - The SOSS extraction is implemented for the SUBSTRIP256and SUBSTRIP96 subarrays only. Subarray is currently FULL. 2024-06-19 11:45:23,290 - stpipe.Tso3Pipeline.extract_1d - ERROR - Extract1dStep will be skipped. 2024-06-19 11:45:23,291 - stpipe.Tso3Pipeline.extract_1d - INFO - Step extract_1d done 2024-06-19 11:45:23,438 - stpipe.Tso3Pipeline.photom - INFO - Step photom running with args (<CubeModel(10, 2048, 2048) from jw02113002001_02101_00001-seg001_nis_calints.fits>,). 2024-06-19 11:45:23,475 - stpipe.Tso3Pipeline.photom - INFO - Using photom reference file: /ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/niriss/jwst_niriss_photom_0045.fits 2024-06-19 11:45:23,475 - stpipe.Tso3Pipeline.photom - INFO - Using area reference file: N/A 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - Using instrument: NIRISS 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - detector: NIS 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - exp_type: NIS_SOSS 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - filter: CLEAR 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - pupil: GR700XD 2024-06-19 11:45:24,247 - stpipe.Tso3Pipeline.photom - ERROR - Unexpected data model type CubeModel for NIRISS. Photom will be skipped. 2024-06-19 11:45:25,161 - CRDS - DEBUG - Using reference file selection rules 'jwst_1241.pmap' defined by cache. 2024-06-19 11:45:25,161 - stpipe.Tso3Pipeline.photom - INFO - Step photom done Traceback (most recent call last): File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stdatamodels/properties.py", line 350, in __getattr__ val = self._instance[attr] ~~~~~~~~~~~~~~^^^^^^ KeyError: 'spec' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stpipe/cli/strun.py", line 24, in main Step.from_cmdline(sys.argv[1:]) File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 191, in from_cmdline return cmdline.step_from_cmdline(args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stpipe/cmdline.py", line 394, in step_from_cmdline step.run(*positional) File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 509, in run step_result = self.process(*args) ^^^^^^^^^^^^^^^^^^^ File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/jwst/pipeline/calwebb_tso3.py", line 182, in process x1d_result.spec.extend(result.spec) ^^^^^^^^^^^ File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stdatamodels/properties.py", line 353, in __getattr__ raise AttributeError("No attribute '{0}'".format(attr)) AttributeError: No attribute 'spec'```
 
So in this case the photom step is at least catching the problem and skipping, but then when it returns to the Tso3 pipeline, it barfs because the returned datamodel is not the right type or contains the right contents.
 
In terms of how to handle it, it's possible this should be caught already in ASN rules, so that we don't even build a tso3 asn file for these cases (and hence avoid the processing error), but the crfints files could at least perhaps be of some use. It will of course still cause some confusion somewhere, because the x1d/x1dints files don't actually contain 1-D spectra (I think right now they're getting filled with 2-D or 3-D image data - this should be checked).

### PR DESCRIPTION
**Pull request by emolter**
Resolves [JP-3665](https://jira.stsci.edu/browse/JP-3665)

Closes #8581 

This PR addresses a bug in the TSO3 pipeline where NIRISS SOSS data for which 1-D spectra could not be extracted were raising errors, instead of exiting the pipeline gracefully.  This update makes it so that saving x1dints files is not attempted in this case, and the rest of the TSO3 pipeline is skipped.

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [x] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [x] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by emolter** [comment]
[Regression tests started here](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1545/)

**Comment by emolter** [comment]
new regtests [started here](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1555/)

**Comment by hbushouse** [comment]
@emolter I've put some test data in /grp/jwst/ssb/chartreuse/dms_bugs/jp-3665/ that can be used to verify that this fix works. I've verified that using jwst/master to run "strun calwebb_tso3 jw02113-o002_tso3_00001_asn.json" duplicates the error seen in operations. Try the same command using this PR branch.

**Comment by emolter** [comment]
@hbushouse yes it runs fine.  I also tested it on `jw02113-o002_20240619t062654_tso3_00001_asn.json`.  Do you think I should write a regtest for this fix with one of these datasets?

The following messages are produced:
```
2024-06-24 15:18:38,967 - stpipe.Tso3Pipeline.extract_1d - INFO - Input is a NIRISS SOSS observation, the specialized SOSS extraction (ATOCA) will be used.
2024-06-24 15:18:38,967 - stpipe.Tso3Pipeline.extract_1d - INFO - Exposure is through the GR700XD + CLEAR (science).
2024-06-24 15:18:38,967 - stpipe.Tso3Pipeline.extract_1d - ERROR - The SOSS extraction is implemented for the SUBSTRIP256and SUBSTRIP96 subarrays only. Subarray is currently FULL.
2024-06-24 15:18:38,968 - stpipe.Tso3Pipeline.extract_1d - ERROR - Extract1dStep will be skipped.
2024-06-24 15:18:38,968 - stpipe.Tso3Pipeline.extract_1d - INFO - Step extract_1d done
2024-06-24 15:18:38,969 - stpipe.Tso3Pipeline - WARNING - extract_1d step could not be completed for any integrations
2024-06-24 15:18:38,969 - stpipe.Tso3Pipeline - WARNING - x1dints products will not be created.
2024-06-24 15:18:38,969 - stpipe.Tso3Pipeline - WARNING - Could not create a photometric catalog; all results are null
2024-06-24 15:18:38,969 - stpipe.Tso3Pipeline - INFO - Step Tso3Pipeline done
```

**Review by hbushouse — APPROVED** [review]
Looks good to me.

**Pull request merged**
