### PR TITLE
JP-2989: Add 'background' to asn types requiring multiple group contributions

### PR DESCRIPTION
**Pull request by tapastro**
Resolves [JP-2989](https://jira.stsci.edu/browse/JP-2989)

Closes #

This PR addresses a residual c1xxx level 3 association created despite containing members from only one observation. The c1xxx association was of type 'background', while only 'group' types were being subjected to the additional requirement added in #6886. Additionally, a function used to prevent background associations from being generated was turned off ~3 years ago but never removed, so this tidies that up as well.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by stscieisenhamer — APPROVED** [review]
Code-part LGTM.

**Comment by tapastro** [comment]
Jenkins test running here: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/453/

**Comment by hbushouse** [comment]
20 of the 21 regtest failures are unrelated (fixed elsewhere). The 1 remaining appears to be expected due to this change in asn rules.

**Review by hbushouse — APPROVED** [review]
If @stscieisenhamer thinks is an OK solution, then that's good enough for me.

**Pull request merged**
