### PR TITLE
JP-2066: Add srctype to Combine1D headers

### LINKED ISSUE #6000: Propagate SRCTYPE to c1d headers
_Issue [JP-2066](https://jira.stsci.edu/browse/JP-2066) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

Now that JP-1917 has been implemented to give the SRCTYPE keyword meaningful values for WFSS exposures, that keyword should be propagated to the headers of c1d products created by the combine_1d step.

### PR DESCRIPTION
**Pull request by tapastro**
Closes #6000 🎉 

Resolves [JP-2066](https://jira.stsci.edu/browse/JP-2066)

**Description**

This PR adds source_type information to combine1d extensions of c1d.fits files, pulled from the x1d inputs to the Combine1D step.

Checklist
- [ ] Tests
- [ ] Documentation
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Comment by tapastro** [comment]
I'll be honest that I never really looked into why there are a few different CI test runs - any explanation why the SDP deps version failed here? I poked around a bit, and it seems like things might be out of date in that run, but I don't fully grok what's going on here.

**Review by hbushouse — APPROVED** [review]
LGTM

**Comment by hbushouse** [comment]
> I'll be honest that I never really looked into why there are a few different CI test runs - any explanation why the SDP deps version failed here? I poked around a bit, and it seems like things might be out of date in that run, but I don't fully grok what's going on here.

Unfortunately the previous CI results seem to have disappeared, as a result of the latest commit using [skip ci]

**Comment by tapastro** [comment]
> > I'll be honest that I never really looked into why there are a few different CI test runs - any explanation why the SDP deps version failed here? I poked around a bit, and it seems like things might be out of date in that run, but I don't fully grok what's going on here.
> 
> Unfortunately the previous CI results seem to have disappeared, as a result of the latest commit using [skip ci]

Under the checks tab, you should be able to select the checks of the previous commit with a dropdown - it failed one of them.

**Comment by hbushouse** [comment]
Hmmm, same set of tests failed in my PR for the CI run using SDP dependencies. No clue.

**Comment by hbushouse** [comment]
CI failure for "SDP dependencies" test is due to use of the latest CRDS context that has a bad NIRCam specwcs rmap in it. Redcat folks are fixing. So you can ignore.

**Pull request merged**
