### PR TITLE
JP-2497: Create valid lamp paths with lamp<->filter equivalency

### LINKED ISSUE #6686: Make level2b ASN rules treat NRS lamp exposures same as science
_Issue [JP-2497](https://jira.stsci.edu/browse/JP-2497) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

Test suites have shown failures in calwebb_spec2 processing of some NIRSpec lamp exposures in fixed-slit mode, because there's no reference data or actual spectral data for the NRS2 detector when using the prism or medium-resolution gratings. There's already an ASN rule that excludes the creation of level2b associations for science exposures on the NRS2 detector in these situations. The same rules should apply for lamp exposures too.

See JWSTDMS-622 for more info.

### PR DESCRIPTION
**Pull request by tapastro**
Closes #6686 
Resolves [JP-2497](https://jira.stsci.edu/browse/JP-2497)

**Description**

This PR adds the NRS_LAMP equivalent valid optical paths to validate associations using the combination of grating, lamp, and detector.

Checklist
- [ ] Tests
- [ ] Documentation
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Review by stscieisenhamer — APPROVED** [review]
LGTM

**Review by hbushouse — APPROVED** [review]
LGTM

**Comment by hbushouse** [comment]
Did the CI tests pass on a previous run? Latest commit used "[skip ci]", which wipes out status of previous run.

**Comment by tapastro** [comment]
> Did the CI tests pass on a previous run? Latest commit used "[skip ci]", which wipes out status of previous run.

Under the Checks tab where the test links direct you, you can select which commit to see the test results for, on the upper left of the panel. That said, the first commit had the astropy 5.0.1 issue, so I'll trigger another run.

**Comment by hbushouse** [comment]
CI failures are all can't load file errors, due to connection issues.

**Pull request merged**
