### PR TITLE
remove end in ami log messages

### PR DESCRIPTION
**Pull request by braingram**
Several log calls in the ami code use an `end` keyword argument that is not supported. As the formatting only occurs if the log is to be displayed this only appears if the log level is changed (to force the message to be formatted).

```python
import logging, numpy as np, jwst.ami.leastsqnrm
img = np.arange(1, 5, dtype='f4').reshape((2, 2))
model = np.arange(8, dtype='f4').reshape((2, 2, 2))
dq = np.zeros((2, 2), dtype='int32')
dq[1, 1] = 1
jwst.ami.leastsqnrm.log.setLevel(logging.DEBUG)
jwst.ami.leastsqnrm.matrix_operations(img, model, dqm=dq)
```
Results in an error, with this PR no errors are seen.

The error can be seen during some test runs (depending on test order):
https://github.com/spacetelescope/stpipe/actions/runs/9445531594/job/26087417184#step:10:189

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by hbushouse — APPROVED** [review]

**Comment by braingram** [comment]
Shoot. I had an "un-pushed" commit that fixed a few more of the log messages. I just pushed it to this PR.

**Comment by braingram** [comment]
Regtests running at:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1538/

**Comment by braingram** [comment]
Regression tests passed with no errors.

**Review by hbushouse — APPROVED** [review]
LGTM

**Pull request merged**
