### PR TITLE
Remove hard-coded MRS outlier detection parameters

### PR DESCRIPTION
**Pull request by drlaw1558**
Removing hard-coded MRS outlier detection parameters that we inserted as a stopgap until parameter reference files were available (PR # 4778).  Now those files have been delivered, we should remove the stopgap code.

### CODE REVIEW

**Comment by drlaw1558** [comment]
@jemorrison @hbushouse

**Comment by jemorrison** [comment]
@drlaw1558  Can you remind me exactly which parameter reference file you updated to put these numbers in

**Comment by drlaw1558** [comment]
New outlier rejection parameter reference file: https://jira.stsci.edu/browse/JWSTMIRI-195

**Review by hbushouse — APPROVED** [review]

**Comment by jemorrison** [comment]
@drlaw1558 Is the reason NIRSPEC does not need a special parameter reference file is because the detaults  in the code spec : scale = string(default='0.5 0.4') are fine for NIRSPEC ?

**Comment by drlaw1558** [comment]
@jemorrison To my knowledge NIRSpec have not tested the defaults in the code spec, but I doubt that those values would perform well given the undersampling of the instrument.

**Review by jemorrison — APPROVED** [review]
Looks good.

**Comment by jemorrison** [comment]
@drlaw1558 before we forget we should probably ping a NIRSpec team member to study the outlier detection routine and decide if they also need a parameter reference file for NIRSpec IFU outlier detection. I just want to make sure the NIRSpec team is aware of this issue.

**Pull request merged**
