### PR TITLE
Update set_telescope_pointing to convert FSMCORR units

### LINKED ISSUE #3300: FSMCORR: Add conversion from arcseconds to radians to set_telescope_pointing
Issue [JP-604](https://jira.stsci.edu/browse/JP-604) was created by Jonathan Eisenhamer:

Add the new conversion, introduced in the engineering telemetry, to convert the FSMCORR mnemonics, SA_ZADUCMDX and SA_ZADUCMDY, from arcseconds to radians in the transformation equations used by the `set_telescope_pointing.py` script. The conversion is

FSMCORR * Degree-to-radian / 3600.

The suggested function to modify is [`jwst.lib.set_telescope_pointing.calc_sifov_fsm_delta_matrix`|https://github.com/spacetelescope/jwst/blob/4fbc26378b00626075b010bed72e39c62cbfe74f/jwst/lib/set_telescope_pointing.py#L855].

### PR DESCRIPTION
**Pull request by hbushouse**
Updated ``set_telescope_pointing`` to convert the input FSM correction values from units of arcsec to radians. Added the switch ``fsmcorr_units`` to allow for the possibility of processing older data that still had these values in radians to begin with.

Fixes #3300.

### CODE REVIEW

**Comment by hbushouse** [comment]
Closing and reopening to retrigger Jenkins CI.

**Comment by stscieisenhamer** [comment]
Ummm, good question. So, doing a quick removal of the except from the test, the initial error seems to be at [this point](https://github.com/spacetelescope/jwst/blob/8f7ee1eee834852dc23b7f2f50e564e7fc7de394/jwst/lib/set_telescope_pointing.py#L264). If the `else` is taken, `siaf` is left undefined but passed to `update_wcs_from_telem`. A default siaf should be assigned here. Methinks the statement should be `siaf = SIAF()`.

**Comment by hbushouse** [comment]
You're right (as usual). Right now it's throwing an error because ``siaf`` is undefined, whereas if we add the line ``siaf = SIAF()`` it then makes it to the point where ``set_telescope_pointing`` raises the expected ``ValueError``, which is then trapped as an exception in the test module.

However, that only solves the first part of the problem with that test module. It then goes on to execute a list of ``assert`` statements on attributes that don't exist and hence throws yet another error.

**Comment by hbushouse** [comment]
Jenkins failure due to server reboot. Travis CI passed, so I'm merging.

**Pull request merged**
