### PR TITLE
Add unit test for 1d residual fringing

### PR DESCRIPTION
**Pull request by drlaw1558**
This PR adds an additional unit test for the 1d residual fringe correction routine.

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by drlaw1558** [comment]
@jemorrison I thought it would be instructive for me to foray into unit tests by adding one for 1d residual fringing, let me know what you think.

**Review by jemorrison — COMMENTED** [review]
David why do you expect outflux and outflux2 to be the same ?
Outflow2 is 1D residual fringe corrected.
Is it that Outflux does not have any residual fringes to correct

**Comment by drlaw1558** [comment]
> David why do you expect outflux and outflux2 to be the same ? Outflow2 is 1D residual fringe corrected. Is it that Outflux does not have any residual fringes to correct

outflux is the version of the input that I've already fringe-corrected, so this test would fail if something started to go wrong in the rf1d routine such that it no longer gave the expected output.

**Comment by drlaw1558** [comment]
> I think this test falls more in line with regression testing than unit testing. We try to avoid adding data files to the repository, and the architecture in place for regression testing allows for comparison to a truth file. I see that we have a residual fringe regression test already - does this test offer different coverage to that one?

The previous test tests the 1d core of the 2d residual fringe correction code (fit_1d_background_complex) while the new tests evaluate the 1d residual fringe correction code (fit_1d_background_complex_1d) as wrapped by the main calling function (fit_residual_fringes_1d).  Since I've never added a unit test before I can't speak to how those are usually structured- in this case I copied what I saw already existed for testing the step.  If there's a better way I'd be curious to know how to implement it.

**Comment by hbushouse** [comment]
I agree with @tapastro that we try to avoid putting data files for testing into the code repo, unless it's absolutely unavoidable. So most unit tests that need to use something like one of our actual data products just build a data model on the fly within the test itself. An example that builds a `SpecModel`, which I think is the kind of model you need here (the output of `extract_1d`, is at https://github.com/spacetelescope/jwst/blob/master/jwst/white_light/tests/test_white_light.py

**Comment by drlaw1558** [comment]
In this case it isn't actually a SpecModel; it's really just arrays of wavelength and flux, the test bypasses the dealing with datamodels and just tests the core algorithm itself.

**Comment by emolter** [comment]
> In this case it isn't actually a SpecModel; it's really just arrays of wavelength and flux, the test bypasses the dealing with datamodels and just tests the core algorithm itself.

I think this should be a regtest because the data arrays themselves can't be programmatically generated, i.e., they are "real data".  IMO unit tests should be idealized cases for which you can determine the input and output analytically or trivially.  They are good for catching edge cases where you know the output should be zero, or NaN, or an error should be raised.  If there is a nontrivial example (something like, input a noise-free sinusoid and output a flat line) then that's great for a unit test too, because you can easily make arrays representing the input and output from scratch.

**Comment by drlaw1558** [comment]
@melanieclarke If this doesn't fit the bill for a unit test we can just close it.  I don't think I've got the time to move it to a regression test, nor is it essential since it's part of the INS testing.

**Comment by melanieclarke** [comment]
Okay, thanks for following up!

**Pull request closed without merging**
