### PR TITLE
update pull request checklist

### PR DESCRIPTION
**Pull request by zacharyburnett**
using points from @nden 's email

# old checklist 

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

# new checklist

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [ ] add a build milestone, i.e. `Build 11.3` (use the [latest build](https://github.com/spacetelescope/jwst/milestones) if not sure)
- [ ] Does this PR change user-facing code / API?
  - [ ] add an entry to `CHANGES.rst` within the relevant release section (otherwise add the `no-changelog-entry-needed` label to this PR)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by zacharyburnett** [comment]
new pull request template looks like this:

```
<!-- If this PR closes a JIRA ticket, make sure the title starts with the JIRA issue number,
for example JP-1234: <Fix a bug> -->
Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)

<!-- If this PR closes a GitHub issue, reference it here by its number -->
Closes #

<!-- describe the changes comprising this PR here -->
This PR addresses ...

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] this PR changes user-facing code / API
      - [ ] added an entry to `CHANGES.rst` within the relevant release section
      - [ ] updated or added relevant tests
      - [ ] updated relevant documentation
- [ ] started a [regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and included a link to the running job
      - [ ] do truth files need to be updated ("okified")?
            - [ ] **after a maintainer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] added a milestone, if relevant
- [ ] this change addresses a corresponding JIRA ticket
      - [ ] JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)
```


Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)


Closes #


This PR addresses ...

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] this PR changes user-facing code / API
      - [ ] added an entry to `CHANGES.rst` within the relevant release section
      - [ ] updated or added relevant tests
      - [ ] updated relevant documentation
- [ ] started a [regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and included a link to the running job
      - [ ] do truth files need to be updated ("okified")?
            - [ ] **after a maintainer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] added a milestone, if relevant
- [ ] this change addresses a corresponding JIRA ticket
      - [ ] JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

**Review by melanieclarke — COMMENTED** [review]
A couple questions/comments:
- Can we make it clear that these are tasks for PR authors who are also pipeline developers?  Some of these tasks can't be done without developer permissions on the repo - we should still note that, or separate those out, so external PR authors are not confused.
- Can we link to the docs for "start a regression test" instead of, or in addition to, the workflow page?

**Comment by zacharyburnett** [comment]
> A couple questions/comments:
> 
> * Can we make it clear that these are tasks for PR authors who are also pipeline developers?  Some of these tasks can't be done without developer permissions on the repo - we should still note that, or separate those out, so external PR authors are not confused.
> * Can we link to the docs for "start a regression test" instead of, or in addition to, the workflow page?

How's this:


### Tasks (if you can't perform these due to permissions, please ask a maintainer to do them)
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [ ] add a build milestone, i.e. `Build 11.3` (use the [latest build](https://github.com/spacetelescope/jwst/milestones) if not sure)
- [ ] Does this PR change user-facing code / API?
  - [ ] add an entry to `CHANGES.rst` within the relevant release section (otherwise add the `no-changelog-entry-needed` label to this PR)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

**Comment by melanieclarke** [comment]
That looks better.  Thanks!

**Review by nden — APPROVED** [review]
@zacharyburnett I'm approving this and assuming you will take care of the item about CHANGES.rst when towncrier is enabled.

**Pull request merged**
