### PR TITLE
JP-2996: Remove duplicate application of pixel area to NRS_IFU extended data

### PR DESCRIPTION
**Pull request by tapastro**
Resolves [JP-2996](https://jira.stsci.edu/browse/JP-2996)

Closes #

This PR addresses an issue seen when corrections to the NRS_IFU pixel area reference file were tested. Changes to the pixel area of scale N were seen applied to the data array at scale N**2, indicating that the pixel areas were being divided out twice.

In testing edits to the code, it was noticed that the pixel area was being divided out of all NRS_IFU data, but because the current dummy files are filled with values of 1, it went unnoticed. Additionally, the pixel area division was being done in units of square arcseconds, which required adding a factor of A2_TO_SR to the code where the pixel area is divided out slice-by-slice. 

The duplicate removed was dividing the conversion factor by the mean pixel area across all slices, which was redundant but also imprecise.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by tapastro** [comment]
Regtests: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/456/

**Review by hbushouse — APPROVED** [review]
I think this appears to make sense now. Instead of dividing by the average pixel area when source_type is extended, it now divides by the area of individual pixels (and in the proper units). And only does the division once.

**Comment by hbushouse** [comment]
The only failures in the regtest run were unrelated changes due to updated MIRI reference files. I guess this suggests that we don't have any NIRSpec IFU extended source data in our regtests?

**Comment by tapastro** [comment]
I think our IFU regressions only cover extended source extraction, actually - but this issue only becomes apparent when the area reference file was changed. It would have also become a problem for point sources, had the area reference files not been filled with ones.

This looks like a good test to update with in-flight data...

**Pull request merged**
