### PR TITLE
JP-2671 Update slit model to include var_flat

### PR DESCRIPTION
**Pull request by jemorrison**
JP-2671 has four issues and this PR resolves only first issue:  LRS data does not have a value for var_flat for s2d or x1d. 
Resolves  only part 1 pf [JP-2671](https://jira.stsci.edu/browse/JP-2671)

Closes a portion of #7223 

This PR adds var_flat to the slit.py model, which appears to have been unintentionally omitted. The products after the cal files now contain valid var_flat values.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by hbushouse — APPROVED** [review]
LGTM

**Comment by hbushouse** [comment]
Have you done a regression test run? I imagine it'll reveal differences, due to the now populated var_flat array, but shouldn't cause any errors.

**Review by tapastro — APPROVED** [review]
LGTM - started regtest here: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/494/

**Comment by hbushouse** [comment]
Regtest results at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/498/ show expected differences due to var_flat (and consequently err) having new values. They also show actual regressions that are simply due to this PR branch not containing some recent updates to master. I think it's OK to merge as-is and we'll immediately due another regtest run from master and hopefully we'll only see the var_flat and err differences.

**Pull request merged**
