### PR TITLE
JP-3424 Extend engineering coverage time for guiding modes

### LINKED ISSUE #7963: STP: Guide star determination fails when using actual engineering db
_Issue [JP-3424](https://jira.stsci.edu/browse/JP-3424) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Reported during JWST Build 10.0 integration by m.swam; see below.

Initial debugging indicates two issues:
* The engineering db is returning slightly different amounts of data, but should not be a concern.
* the set_telescope_pointing interface is not handling the results from the actual DB correctly.

bq. Hi Jonathan!
bq.  
bq. We are seeing some msgs come out of set_telescope_pointing under the new DMS 10.0 (SCSB 1.12.0) release for certain guide star acq datasets that are a concern to us.   They don’t fail in set_telescope_pointing directly, but the FITS files come away without an ASDF extension, where other gs-acq output files that don’t show these msgs do have an ASDF extension present.   Later on, when our Ingest code tries to convert the FITS content into XML for the ingest catalog, we get bad FITS extension information in the XML, and the concern is that the msgs below might be related to the bad FITS/XML content later on, where the cases that have a present ASDF extension have no problem in the ingest XML generation.  It seems the msgs below, might be related to the missing ASDF extension, and then later, the ingest XML generation problems.
bq.  
bq. Do you have a guess at what could cause these msgs from set_telescope_pointing?
bq. Thanks,
bq. Mike
bq.  
bq.  
bq. set_telescope_pointing.py --force-level1bmodel --allow-default /ifs/archive/test/jwst/store/rspencer/tests/fgs001/dtest2/JWSTDP-2023.3.0-54~1e68b4de/2023-09-20-153536/sdp/gs_fits/jw01019006001_gs-acq2_2022122031145_uncal.fits
bq. 2023-09-20 15:53:18,555 - stpipe - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.0.20230918-py3.11/lib/python3.11/site-packages/jwst/scripts/set_telescope_pointing.py:203: UserWarning: usage of `set_telescope_pointing.py` is deprecated; use `set_telescope_pointing` instead
bq. 2023-09-20 15:53:18,555 - stpipe - WARNING - warnings.warn(
bq. 2023-09-20 15:53:18,555 - stpipe - WARNING -
bq. set_telescope_pointing called with args Namespace(exposure=['/ifs/archive/test/jwst/store/rspencer/tests/fgs001/dtest2/JWSTDP-2023.3.0-54~1e68b4de/2023-09-20-153536/sdp/gs_fits/jw01019006001_gs-acq2_2022122031145_uncal.fits'], verbose=0, allow_any_file=False, force_level1bmodel=True, allow_default=True, dry_run=False, method=<Methods.OPS_TR_202111: 'ops_tr_202111'>, save_transforms=False, override_transforms=None, fgsid=1, tolerance=60, siaf=None, prd=None, engdb_url=None, transpose_j2fgs=True)
bq. ------Setting pointing for /ifs/archive/test/jwst/store/rspencer/tests/fgs001/dtest2/JWSTDP-2023.3.0-54~1e68b4de/2023-09-20-153536/sdp/gs_fits/jw01019006001_gs-acq2_2022122031145_uncal.fits
bq. Updating WCS info for file /ifs/archive/test/jwst/store/rspencer/tests/fgs001/dtest2/JWSTDP-2023.3.0-54~1e68b4de/2023-09-20-153536/sdp/gs_fits/jw01019006001_gs-acq2_2022122031145_uncal.fits
bq. Input /ifs/archive/test/jwst/store/rspencer/tests/fgs001/dtest2/JWSTDP-2023.3.0-54~1e68b4de/2023-09-20-153536/sdp/gs_fits/jw01019006001_gs-acq2_2022122031145_uncal.fits is an unknown model, opening as a Level1bModel.
bq. 2023-09-20 15:53:19,795 - stpipe - WARNING - ***WARNING***: LOCAL JWST PRD VERSION PRDOPSSOC-062 CANNOT BE CHECKED AGAINST ONLINE VERSION
bq. pysiaf: Using SIAF XML folder /dms/local/jwst/pipeline/jwstdp/JWSTDP-2023.3.0-54~1e68b4de/defs/SIAFXML
bq. Updating WCS for aperture FGS1_FULL
bq. Setting basic FITS WCS keywords for imaging
bq. Updating WCS for Fine Guidance.
bq. Determining pointing between observations times (mjd):
bq. obsstart: 59701.133155034724 obsend: 59701.13317697917
bq. Telemetry search tolerance: 60
bq. Reduction function: functools.partial(<function gs_position_acq at 0x2b403139c220>, exp_type='fgs_acq2')
bq. Querying engineering DB: <http://pwjwdmsemwebag.stsci.edu/JWDMSEngSpAcc/TlmMnemonicDataSrv.svc/>
bq. 2023-09-20 15:53:20,232 - stpipe - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.0.20230918-py3.11/lib/python3.11/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
bq. 2023-09-20 15:53:20,232 - stpipe - WARNING - avg = a.mean(axis, **keepdims_kw)
bq. 2023-09-20 15:53:20,232 - stpipe - WARNING -
bq. 2023-09-20 15:53:20,233 - stpipe - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.0.20230918-py3.11/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
bq. 2023-09-20 15:53:20,233 - stpipe - WARNING - ret = ret.dtype.type(ret / rcount)
bq. 2023-09-20 15:53:20,233 - stpipe - WARNING -
bq. Reduced set of pointings:
bq. GuideStarPosition(position=(nan, nan), corner=(1078, 1142), size=(32, 32))
bq. WCS info:
bq. crpix1: nan crpix2: nan
bq. crval1: 269.8767320430929 crval2: 66.58682886944868
bq. pc_matrix: [-0.9997653641994049, -0.02166140686177685, -0.02166140686177685, 0.9997653641994049]
bq. Saving updated model /ifs/archive/test/jwst/store/rspencer/tests/fgs001/dtest2/JWSTDP-2023.3.0-54~1e68b4de/2023-09-20-153536/sdp/gs_fits/jw01019006001_gs-acq2_2022122031145_uncal.fits
bq. Cannot determine pointing information: Floating point nan values are not allowed in FITS headers.
bq. set savestatus = 0

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [JP-3424](https://jira.stsci.edu/browse/JP-3424)

Closes #7963 

This PR addresses an issue discovered during Build 10.0 integration with WCS determination in set_telescope_pointing. A new algorithm for the various guider products has been implemented, which require more engineering coverage than science exposures. Turns out that not enough leeway being given. This PR extends the coverage time to use when retrieving engineering data.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- ~updated relevant documentation~
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by tapastro — APPROVED** [review]
As far as my extremely limited knowledge of STP goes, this looks good to me. 🙃

**Comment by stscieisenhamer** [comment]
[Regression test](https://plwishmaster.stsci.edu:8081/job/RT/job/eisenhamer-dev/353/)

**Review by hbushouse — APPROVED** [review]
Code looks find, but the tests are failing.

**Comment by stscieisenhamer** [comment]
[Yet Another Regression Run](https://plwishmaster.stsci.edu:8081/job/RT/job/eisenhamer-dev/357/). This one is limited to the pointing and engineering tests, but now they do all pass.

**Pull request merged**
