### PR TITLE
Changed good_bits from 4 to 6 to exclude SATURATION and JUMP_DET flags (JP-765)

### PR DESCRIPTION
**Pull request by stscirij**
Pixels with just either of these flags set won't be excluded from weight calculation.

### CODE REVIEW

**Comment by stscirij** [comment]
The good_bits flag is also used in resample and resample_spec - do we want to change it from 4 to 6 there too?

**Comment by jdavies-st** [comment]
I think that makes sense to make the change in `resample` too.  It will suffer from the same problem.

**Comment by stscicrawford** [comment]
Let's do it in one PR and then please add a change log to this one as well.  This addresses the problem raised in #3596 though a ticket should be created to look at potential other ways to address the issue as discussed today.

**Comment by hbushouse** [comment]
https://jira.stsci.edu/browse/JP-787 has been filed to do the future work of redesigning the way flags are used in these steps.

**Pull request merged**
