### PR TITLE
Remove TPCorr

### PR DESCRIPTION
**Pull request by mcara**
This PR removes `TPCorr` WCS correction model. This model is now a compound model defined in `tweakwcs` using fundamental models defined in `astropy` and `gwcs`.

Until a new release of `gwcs` is made (and `tweakwcs`), `jwst` will need to depend on `dev` versions of these two packages if this PR is merged.

CC: @nden @hbushouse @jdavies-st

### CODE REVIEW

**Comment by nden** [comment]
The next gwcs release will be at the end of February with a tweakwcs release following.

**Comment by jdavies-st** [comment]
I'm seeing a failure in our current regression tests for this PR.  It happens when the `tweakreg` step is run.

```
$ pytest --bigdata -v --basetemp=/Users/jdavies/scratch jwst/regtest/test_nircam_image.py::test_nircam_image_stage3_i2d
============================================================ test session starts ============================================================
platform darwin -- Python 3.7.6, pytest-5.3.4, py-1.8.1, pluggy-0.13.1 -- /Users/jdavies/miniconda3/envs/jwst/bin/python
cachedir: .pytest_cache
rootdir: /Users/jdavies/dev/jwst, inifile: setup.cfg
plugins: requests-mock-1.7.0, openfiles-0.4.0, ci-watson-0.4, asdf-2.5.1, doctestplus-0.5.0, cov-2.8.1
collected 1 item                                                                                                                            

jwst/regtest/test_nircam_image.py::test_nircam_image_stage3_i2d ERROR                                                                 [100%]

================================================================== ERRORS ===================================================================
______________________________________________ ERROR at setup of test_nircam_image_stage3_i2d _______________________________________________

self = <asdf.type_index._AsdfWriteTypeIndex object at 0x12ec69e50>, custom_type = <class 'numpy.float64'>

    def from_custom_type(self, custom_type):
        """
        Given a custom type, return the corresponding `ExtensionType`
        definition.
        """
        asdftype = None
    
        # Try to find an exact class match first...
        try:
>           asdftype = self._type_by_cls[custom_type]
E           KeyError: <class 'numpy.float64'>

../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/type_index.py:159: KeyError

During handling of the above exception, another exception occurred:

self = <asdf.type_index._AsdfWriteTypeIndex object at 0x12ec69e50>, custom_type = <class 'numpy.float64'>

    def from_custom_type(self, custom_type):
        """
        Given a custom type, return the corresponding `ExtensionType`
        definition.
        """
        asdftype = None
    
        # Try to find an exact class match first...
        try:
            asdftype = self._type_by_cls[custom_type]
        except KeyError:
            # ...failing that, match any subclasses
            try:
>               asdftype = self._type_by_subclasses[custom_type]
E               KeyError: <class 'numpy.float64'>

../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/type_index.py:163: KeyError

During handling of the above exception, another exception occurred:

run_image2pipeline = None
rtdata_module = {'input': '/Users/jdavies/scratch/test_nircam_image_run_detector1pipeline0/jw42424-o002_20191220t214154_image3_001_asn...01_asn.json',
 'output': None,
 'remote_results_path': None,
 'traceback': None,
 'truth': None,
 'truth_remote': None}
jail = local('/Users/jdavies/scratch/test_nircam_image_run_detector1pipeline0')

    @pytest.fixture(scope="module")
    def run_image3pipeline(run_image2pipeline, rtdata_module, jail):
        """Run calwebb_image3 on NIRCam imaging long data"""
        rtdata = rtdata_module
        # Grab rest of _rate files for the asn and run image2 pipeline on each to
        # produce fresh _cal files for the image3 pipeline.  We won't check these
        # or look at intermediate products, including the resampled i2d
        rate_files = [
        "nircam/image/jw42424001001_01101_00001_nrcb5_rate.fits",
        "nircam/image/jw42424001001_01101_00002_nrca5_rate.fits",
        "nircam/image/jw42424001001_01101_00002_nrcb5_rate.fits",
        "nircam/image/jw42424001001_01101_00003_nrca5_rate.fits",
        "nircam/image/jw42424001001_01101_00003_nrcb5_rate.fits",
        ]
        for rate_file in rate_files:
            rtdata.get_data(rate_file)
            args = ["config/calwebb_image2.cfg", rtdata.input,
                "--steps.resample.skip=True"]
            Step.from_cmdline(args)
    
        # Get the level3 assocation json file (though not its members) and run
        # image3 pipeline on all _cal files listed in association
        rtdata.get_data("nircam/image/jw42424-o002_20191220t214154_image3_001_asn.json")
        args = ["config/calwebb_image3.cfg", rtdata.input,
            # Comment out following lines, as the dataset is currently broken
            # "--steps.tweakreg.save_results=True",
            # "--steps.skymatch.save_results=True",
            "--steps.source_catalog.snr_threshold=20",
            ]
>       Step.from_cmdline(args)

../../dev/jwst/jwst/regtest/test_nircam_image.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../dev/jwst/jwst/stpipe/step.py:155: in from_cmdline
    return cmdline.step_from_cmdline(args)
../../dev/jwst/jwst/stpipe/cmdline.py:338: in step_from_cmdline
    step.run(*positional)
../../dev/jwst/jwst/stpipe/step.py:391: in run
    step_result = self.process(*args)
../../dev/jwst/jwst/pipeline/calwebb_image3.py:70: in process
    input_models = self.tweakreg(input_models)
../../dev/jwst/jwst/stpipe/step.py:391: in run
    step_result = self.process(*args)
../../dev/jwst/jwst/tweakreg/tweakreg_step.py:208: in process
    imcat.meta['image_model'].meta.wcs = imcat.wcs
../../dev/jwst/jwst/datamodels/properties.py:321: in __setattr__
    if node._validate():
../../dev/jwst/jwst/datamodels/properties.py:263: in _validate
    self._ctx._asdf)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py:234: in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:206: in walk_and_modify
    return recurse(top)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:158: in recurse
    result = callback(result)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py:231: in walker
    return tag.to_tree_tagged(node, ctx)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/types.py:313: in to_tree_tagged
    obj = cls.to_tree(node, ctx)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/gwcs/tags/wcs.py:54: in to_tree
    'steps': yamlutil.custom_tree_to_tagged_tree(steps, ctx)}
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py:234: in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:206: in walk_and_modify
    return recurse(top)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:145: in recurse
    contents = [recurse(val) for val in tree]
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:145: in <listcomp>
    contents = [recurse(val) for val in tree]
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:137: in recurse
    val = recurse(val)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:158: in recurse
    result = callback(result)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py:231: in walker
    return tag.to_tree_tagged(node, ctx)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/compound.py:107: in to_tree_tagged
    cls._to_tree_base_transform_members(model, node, ctx)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/basic.py:60: in _to_tree_base_transform_members
    model._user_inverse, ctx)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py:234: in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:206: in walk_and_modify
    return recurse(top)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:158: in recurse
    result = callback(result)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py:231: in walker
    return tag.to_tree_tagged(node, ctx)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/compound.py:107: in to_tree_tagged
    cls._to_tree_base_transform_members(model, node, ctx)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/basic.py:60: in _to_tree_base_transform_members
    model._user_inverse, ctx)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py:234: in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:206: in walk_and_modify
    return recurse(top)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py:158: in recurse
    result = callback(result)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py:231: in walker
    return tag.to_tree_tagged(node, ctx)
E   RecursionError: maximum recursion depth exceeded in __subclasscheck__
!!! Recursion detected (same locals & position)
----------------------------------------------------------- Captured stdout setup -----------------------------------------------------------
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    maximum recursion depth exceeded in __subclasscheck__
Traceback (most recent call last):
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/type_index.py", line 159, in from_custom_type
    asdftype = self._type_by_cls[custom_type]
KeyError: <class 'numpy.float64'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/type_index.py", line 163, in from_custom_type
    asdftype = self._type_by_subclasses[custom_type]
KeyError: <class 'numpy.float64'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jdavies/dev/jwst/jwst/stpipe/cmdline.py", line 338, in step_from_cmdline
    step.run(*positional)
  File "/Users/jdavies/dev/jwst/jwst/stpipe/step.py", line 391, in run
    step_result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_image3.py", line 70, in process
    input_models = self.tweakreg(input_models)
  File "/Users/jdavies/dev/jwst/jwst/stpipe/step.py", line 391, in run
    step_result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/tweakreg/tweakreg_step.py", line 208, in process
    imcat.meta['image_model'].meta.wcs = imcat.wcs
  File "/Users/jdavies/dev/jwst/jwst/datamodels/properties.py", line 321, in __setattr__
    if node._validate():
  File "/Users/jdavies/dev/jwst/jwst/datamodels/properties.py", line 263, in _validate
    self._ctx._asdf)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 234, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 206, in walk_and_modify
    return recurse(top)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 158, in recurse
    result = callback(result)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 231, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/types.py", line 313, in to_tree_tagged
    obj = cls.to_tree(node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/gwcs/tags/wcs.py", line 54, in to_tree
    'steps': yamlutil.custom_tree_to_tagged_tree(steps, ctx)}
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 234, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 206, in walk_and_modify
    return recurse(top)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 145, in recurse
    contents = [recurse(val) for val in tree]
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 145, in <listcomp>
    contents = [recurse(val) for val in tree]
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 137, in recurse
    val = recurse(val)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 158, in recurse
    result = callback(result)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 231, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/compound.py", line 107, in to_tree_tagged
    cls._to_tree_base_transform_members(model, node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/basic.py", line 60, in _to_tree_base_transform_members
    model._user_inverse, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 234, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 206, in walk_and_modify
    return recurse(top)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 158, in recurse
    result = callback(result)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 231, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/compound.py", line 107, in to_tree_tagged
    cls._to_tree_base_transform_members(model, node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/basic.py", line 60, in _to_tree_base_transform_members
    model._user_inverse, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 234, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 206, in walk_and_modify
    return recurse(top)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 158, in recurse
    result = callback(result)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 231, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/compound.py", line 107, in to_tree_tagged
    cls._to_tree_base_transform_members(model, node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/basic.py", line 60, in _to_tree_base_transform_members
    model._user_inverse, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 234, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 206, in walk_and_modify
    return recurse(top)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 158, in recurse
    result = callback(result)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 231, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/compound.py", line 107, in to_tree_tagged
    cls._to_tree_base_transform_members(model, node, ctx)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/astropy/io/misc/asdf/tags/transform/basic.py", line 60, in _to_tree_base_transform_members
    model._user_inverse, ctx)

<SNIP>

  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 234, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 206, in walk_and_modify
    return recurse(top)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 137, in recurse
    val = recurse(val)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/treeutil.py", line 158, in recurse
    result = callback(result)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/yamlutil.py", line 229, in walker
    tag = ctx.type_index.from_custom_type(type(node), ctx.version_string)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/type_index.py", line 258, in from_custom_type
    return write_type_index.from_custom_type(custom_type)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/type_index.py", line 170, in from_custom_type
    return self._process_dynamic_subclass(custom_type)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/asdf/type_index.py", line 143, in _process_dynamic_subclass
    if issubclass(custom_type, key):
RecursionError: maximum recursion depth exceeded in __subclasscheck__
```
So there's an infinite recursion happening in there somewhere.

**Comment by jdavies-st** [comment]
Also, in order to use the pipeline now, developers will have to create a new conda environment or uninstall `tweakwcs` and `gwcs` before installing the package.  So the latter:
```
pip uninstall tweakwcs gwcs
pip install -e .[test]
```
will allow the dev versions of `tweakwcs` and `gwcs` to be installed.

Pip has no way of determining whether or not a git hash is earlier or later than the installed release version.

**Comment by nden** [comment]
@mcara Didn't the test pass locally? If you can reproduce the error we should consider reverting this PR.

**Comment by jdavies-st** [comment]
I can reproduce this with a simple example:
```python
import asdf
from astropy.modeling import models

transform = models.Shift(4) | models.Shift(3)
transform_inv = models.Shift(-3) | models.Shift(-4)

transform_inv.inverse = transform
transform.inverse = transform_inv

tree = {"transform": transform}

with asdf.AsdfFile(tree) as af:
    af.write_to("test.asdf")
```
This produces `RecursionError: maximum recursion depth exceeded in comparison`

The solution is to remove the line
```
transform_inv.inverse = transform
```
as it is the culprit.

**Comment by nden** [comment]
Right, don't do this!

**Comment by mcara** [comment]
Why not? CC: @perrygreenfield

**Comment by mcara** [comment]
I would suggest moving this discussion to https://github.com/spacetelescope/tweakwcs/issues/97

**Pull request merged**
