### PR TITLE
JP_3100  move straylight before flat fielding

### PR DESCRIPTION
**Pull request by jemorrison**
Resolves [JP-3100](https://jira.stsci.edu/browse/JP-3100)

This PR moves the MIRI MRS straylight step before flat fielding in the calwebb_spec2 pipeline. 

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by jemorrison** [comment]
This change was made in calwebb_spec2 in the module _process_common.
Only MRS IFU data has the straylight step and MRS data is processed in the module. 

BTY - the straylight step is called other places in the code - which does not make sense to me because it is only an
MRS step. For example _process_grism and _process_niriss_soss. But I guess it does not matter because in these cases it will just get skipped - so no harm done.

**Review by hbushouse — APPROVED** [review]
LGTM.

**Review by drlaw1558 — APPROVED** [review]
Looks fine to me too.

**Comment by hbushouse** [comment]
Regression test started at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/595/

**Comment by hbushouse** [comment]
Regtest results look fine. Only expected differences due to S_STRAY keyword now showing up in flat_field step outputs, because the step has now been run before flat_field.

**Pull request merged**
