### PR TITLE
JP-2530 Further restrict default models that can be updated

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [JP-2530](https://jira.stsci.edu/browse/JP-2530)

**Description**

PR#6735 allowed any datamodel to be modified, with warnings if an unexpected model was found. This had the unintended side effect in ground processing for failing on certain observatory products that were not intended to be used. This PR re-instates some of the restrictions, but allow the option of modifying anything.

Checklist
- [x] Tests
- [x] Documentation
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Review by tapastro — APPROVED** [review]
LGTM - seems clear that the new default is to allow only the expected file/model types through, unless explicitly flagged to try allowing everything through?

**Comment by stscieisenhamer** [comment]
@tapastro Yes, that is the intent: Default is restricted because otherwise it is "your mileage may vary".

**Review by hbushouse — APPROVED** [review]
LGTM

**Comment by stscieisenhamer** [comment]
failing test is the usual crds/CI issue and is a non-blocker.

**Pull request merged**
