### PR TITLE
JP-3037 Modify entrypoint functions to not return anything unless failure

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [JP-3037](https://jira.stsci.edu/browse/JP-3037)

This PR addresses and issue found during SDP integration testing where the `ans_generate` command was always returning a non-zero shell status. This was a side effect of the moving to the use of entrypoints. The main function was actually an object instantiation, hence there was always something returned, resulting in a non-zero shell status.

The cli api for both `ans_generate` and `asn_from_list` are modified to be functions which return nothing, thus ensuring a proper shell status value of zero.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [x] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
[Regressions](https://plwishmaster.stsci.edu:8081/job/RT/job/eisenhamer-dev/299/)

**Review by hbushouse — APPROVED** [review]
LGTM

**Review by kmacdonald-stsci — APPROVED** [review]

**Review by zacharyburnett — APPROVED** [review]
LGTM; should more test(s) be added to catch this issue as a regression in the future?

**Comment by stscieisenhamer** [comment]
Regarding adding tests: It is probably lost in the refactoring, but this is the [added test](https://github.com/spacetelescope/jwst/blob/bc08d9108904b45e711459546786b45d916912c5/jwst/associations/tests/test_main.py#L47) for command-line return.

**Pull request merged**
