### PR TITLE
TST: JenkinsfileRT will open issue on failure

### PR DESCRIPTION
**Pull request by pllim**
JenkinsfileRT (nightly run) will open issue on failure with this patch. cc @rendinam

### CODE REVIEW

**Comment by jdavies-st** [comment]
Ooh, that looks cool.  Guess I should get those tests passing!  :joy:

**Comment by pllim** [comment]
> You’re not authorized to merge this pull request.

Where is the love? 😢

**Comment by jdavies-st** [comment]
We definitely don't want this merged right now.

**Comment by pllim** [comment]
Why don't you want to merge? It is working and it is awesome. Thanks, @rendinam !

spacetelescope/hstcal#378

**Comment by jdavies-st** [comment]
I love the idea, but we will have to change our workflow here in `jwst`-land if want to avoid getting a new issue opened every day (or twice a day).  So I would like to hold off on implementing this for now until we have a chance to discuss this as a group.

**Comment by pllim** [comment]
Are we there yet?

**Comment by jdavies-st** [comment]
I think so!  Let's do it.

**Comment by jdavies-st** [comment]
Other opinions amongst `jwst` developers?

**Comment by pllim** [comment]
> Other opinions

No objections in the past 13 hours. :shipit:

**Comment by nden** [comment]
:+1: to try this. We can always revert if we don't like it for some reason.

**Comment by philhodge** [comment]
I don't like this idea; regression tests are too fragile.

**Comment by stscieisenhamer** [comment]
Not desired functionality, closing!

**Pull request closed without merging**
