### PR TITLE
JP-2581: allow multiprocessing for jump detection

### PR DESCRIPTION
**Pull request by cshanahan1**
Re-enable multiprocessing for jump detection. 

required for https://github.com/spacetelescope/stcal/pull/87

### CODE REVIEW

**Review by hbushouse — APPROVED** [review]
Looks good. 

I seem to recall, however, that the code over in stcal allows for integer values of `max_cores`, so I'm just curious why all of these tests needed to have the value changed from 1 to `none`?

**Comment by cshanahan1** [comment]
> Looks good.
> 
> I seem to recall, however, that the code over in stcal allows for integer values of `max_cores`, so I'm just curious why all of these tests needed to have the value changed from 1 to `none`?

I changed it from allowing integer values to just allowing strings. JumpStep spec only allows this to be strings so I just kept that there to avoid confusion.

**Comment by hbushouse** [comment]
The CI tests all passed, when using your stcal branch. So that can be changed back now and we'll go ahead and merge.

By the way, how does this relate to PR #6815 ? Looks like it duplicates the code updates, but diverges in terms of unit tests.

**Comment by cshanahan1** [comment]
I just updated the existing unit tests here, it looks like that PR adds a new one.

**Comment by hbushouse** [comment]
> > Looks good.
> > I seem to recall, however, that the code over in stcal allows for integer values of `max_cores`, so I'm just curious why all of these tests needed to have the value changed from 1 to `none`?
> 
> I changed it from allowing integer values to just allowing strings. JumpStep spec only allows this to be strings so I just kept that there to avoid confusion.

OK, sounds good.

**Pull request merged**
