### PR TITLE
JP-3321: NRS IRS2 refpix bad pixel updates

### LINKED ISSUE #7805: IRS2 intermittently bad pixels algorithm fix
_Issue [JP-3321](https://jira.stsci.edu/browse/JP-3321) was created on JIRA by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena):_

This ticket is related to JP-3157. The algorithm is a dynamic check on the reference pixel values. The previous overcorrection mitigation factor is turned into the number of sigmas away from the mean (more intuitive quantity). This is what the algorithm does:
 # Loop through the reference pixel sequences and calculates per column the mean, standard deviation, and differences between even and odd, and store these in their corresponding array.
 # Calculate the means and standard deviations for each of these 3 arrays
 # Flag anything  >  mean_of_array + FACTOR * standard_deviation_of_array
 # Replace these flagged (suspicious) pixels with the nearest good ref pix

### PR DESCRIPTION
**Pull request by penaguerrero**
This PR is prompted by help desk ticket INC0191416. It is a minor improvement on the new implementation to fix the intermittently bad reference pixels.

Resolves [JP-3321](https://jira.stsci.edu/browse/JP-3321)

Closes #7805 

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by hbushouse — COMMENTED** [review]
Code updates look fine. Please run regression tests on the PR branch using the "JWST-Developers-Pull-Requests" Jenkins instance.

**Comment by penaguerrero** [comment]
ok, regression tests ran. The test shows very small differences expected due to the changes made.

**Comment by hbushouse** [comment]
> ok, regression tests ran. The test shows very small differences expected due to the changes made.

Please post a link to the regression test run, so that the results can be reviewed.

**Review by hbushouse — APPROVED** [review]
Looks good to me.

**Comment by penaguerrero** [comment]
regression test link: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/836/

**Pull request merged**
