### PR TITLE
JP-3233: Combine NRS S200A1+S200A2 data and update source_id handling

### LINKED ISSUE #7701: Combine S200A1 and S200A2 spectra in level 3 products
_Issue [JP-3233](https://jira.stsci.edu/browse/JP-3233) was created on JIRA by [Jeff Valenti](https://jira.stsci.edu/secure/ViewProfile.jspa?name=valenti):_

{*}Request{*}: For fixed slit spectroscopy with NIRSpec H gratings, enhance the association generator so that spec3 will combine exposures with the target in the S200A1 and S200A2 slits. From a data quality perspective, this will double the number of exposures being combined, substantially improving outlier rejection. From a usability perspective, the user will get one product with complete wavelength coverage, rather than two products each with a detector gap in a different wavelength range. Depending on the implementation, spec2 may be changed to encode in SOURCEID the slit containing the target and the slit being extracted. This would help users identify which level 3 products contain the target and may simplify association logic at level 3.

{*}Context{*}: For fixed slit spectroscopy with NIRSpec H gratings, [JDox](https://jwst-docs.stsci.edu/jwst-near-infrared-spectrograph/nirspec-observing-strategies/nirspec-dithering-recommended-strategies#NIRSpecDitheringRecommendedStrategies-NIRSpecdecisiontreeinfixedslitsmode) recommends taking exposures with the target in S200A1 and S200A2, if the observer wants complete wavelength coverage. [APT](https://jwst-docs.stsci.edu/jppom/nirspec-templates/nirspec-fixed-slit-spectroscopy-template-parameters#NIRSpecFixedSlitSpectroscopyTemplateParameters-Slit) provides an "S200A1 and S200A2" option for this purpose.

### PR DESCRIPTION
**Pull request by hbushouse**
Resolves [JP-3233](https://jira.stsci.edu/browse/JP-3233)

Closes #7701 

This PR fulfills all of the requests outlined in JP-3233, which now include:
1) Creating Level 3 ASN's for NIRSpec fixed-slit observations that combine the data from the S200A1 and S200A2 slits when the primary target has been observed in both of those slits, rather than creating separate products for each slit.
2) Reworking the "source_id" numbering scheme for all NRS FS products. Instead of hardwiring the source_id value based on the slit name (which used S200A1=s00001, S200A2=s00002, S400A1=s00003, S1600A1=s00004, S200B1=s00005), the slit containing the primary target (designated by the value of the FXD_SLIT keyword) is always assigned source_id=00001, regardless of which slit it's in. Data from the other slits get assigned a 2-digit source_id that follows the convention 10*primary_slit_id + secondary_slit_id, such that, for example, an exposure that uses S400A1 as primary has a source_id of 31 for data in the S200A1 slit.
3) Reworking the level-3 product name convention for all NRS FS products, so that instead of always containing the name of the primary slit, they now contain the name of the slit from the data were extracted. This requires an update to the way the product name template is created in the Level 3 ASN file, such that the slit name is no longer pre-assigned by the ASN generator, but instead is left as a variable ("slit_name") to be populated by the calwebb_spec3 pipeline at the time of execution, in the same way "source_id" is populated at execution time.

This PR incorporates and extends the updates previously contained in #7795 and #7863 and completely supersedes them (they will be closed).

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by hbushouse** [comment]
Reviewers: In order to incorporate the changes in ASN rules, I felt it best to no longer include the "fxd_slit" info in the "opt_elem" info, but rather keep them separate. So now "opt_elem" only includes filter and pupil wheel info, while any NRS FS slit names are handled in a separate constraint. I've also created a new "dms_product_name_nrsfs_sources" function, based on the existing "dms_product_name_sources", that works with both "source_id" and "slit_name" in the output products. This is only used for NRS FS mode. All other multi-source modes (e.g. NIRCam and NIRISS WFSS, NIRSpec MOS) continue to use the existing "dms_product_name_sources" routine, which only works with "source_id" in the product names.

All of these changes lead to LOTS of differences in regression tests, due to the new product name template syntax contained in spec3 ASN files for NRS FS data, the changes in actual output file names for all NRS FS tests, and of course the changes in "source_id" values both within the datasets themselves and in the output file names.

**Comment by hbushouse** [comment]
Initial regression test run started at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/913  This will likely take several iterations to get a run that doesn't crash, because input data to some of the tests will likely need updating to conform to the new expectations of source_id assignments during level-2b processing of NRS FS exposures.

**Comment by hbushouse** [comment]
All CI failures are now down to unrelated mismatches between stcal/main and stcal released (CI tests use stcal release).

**Comment by hbushouse** [comment]
Latest regression test run results are at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/915/testReport/ and it all looks good. Lots of expected changes in asn product name results, as well as source_id values in calibrated data products. All truths will be updated after this gets merged. Declaring this ready for review.

**Review by stscieisenhamer — APPROVED** [review]

**Review by kmacdonald-stsci — APPROVED** [review]

**Pull request merged**
