### PR TITLE
switch to sphinx rtd theme

### PR DESCRIPTION
**Pull request by braingram**
This PR switches the docs to use the sphinx readthedocs theme (instead of the stsci rtd theme).

Currently jwst docs depend on both `sphinx-rtd-theme` and `stsci-rtd-theme`:
https://github.com/spacetelescope/jwst/blob/87770e3f97c96422af6d3f30569ef7124acf6d5b/pyproject.toml#L127-L128

The `stsci-rtd-theme` has not been updated in 2 years and contains css changes that no longer appear compatible with the current `sphinx-rtd-theme`. Some issues (solved by this PR are):

- side menu expand/collapse buttons do not render
- disappearing list bullets (see example below)

Docs rendered with this PR: https://jwst-pipeline--8224.org.readthedocs.build/en/8224/
Existing docs: https://jwst-pipeline.readthedocs.io/en/latest/

Bulleted list differences
----

As seen here, under some conditions bullets for lists disappear:
https://jwst-pipeline.readthedocs.io/en/latest/jwst/user_documentation/running_pipeline_python.html#saving-final-pipeline-results
With the theme change in this PR the list appears bulleted:
https://jwst-pipeline--8224.org.readthedocs.build/en/8224/jwst/user_documentation/running_pipeline_python.html#saving-final-pipeline-results

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [x] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by drlaw1558** [comment]
Nice, looks like the color scheme changes subtly as well in a way that helps with the nav bar.

**Comment by tapastro** [comment]
It appears that the side frame no longer has an independent scroll bar - current builds allow a user to navigate the expanded Package Index while keeping the same text on the screen in the main frame, while this one locks both frames to the same scroll bar. 

I also don't see a "bar" in the scroll bar on Safari, though that may just be a Safari problem. On Firefox I see the bar and am to click and drag.

**Comment by braingram** [comment]
> It appears that the side frame no longer has an independent scroll bar - current builds allow a user to navigate the expanded Package Index while keeping the same text on the screen in the main frame, while this one locks both frames to the same scroll bar.
> 
> I also don't see a "bar" in the scroll bar on Safari, though that may just be a Safari problem. On Firefox I see the bar and am to click and drag.

Interesting. Thanks for taking a look.

Odd, on mac and firefox (and on safari) I'm not seeing a bar and scrolling appears the same for both themes (I can scroll up and down on the menu, scrolling the page causes the side menu to also scroll).

There is 'sticky_navigation' option that we could try turning off:
https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-sticky_navigation

I think that should make the scrolling of the side menu independent of the main contents. Should I make that change and we can see what the docs look like?

**Comment by braingram** [comment]
I opened a test pr with "sticky_navigation" turned off: https://github.com/spacetelescope/jwst/pull/8226

Here are the docs with that setting disabled: https://jwst-pipeline--8226.org.readthedocs.build/en/8226/

**Comment by hbushouse** [comment]
Using Chrome browser on a Mac I don't see a scroll bar on either panel for either setting of "sticky navigation", but I do see the difference in the results. The first results (with sticky navigation on) do result in the content of both panels moving up or down when you scroll in only one of them. With sticky nav turned off, the right panel stays unmoved when scrolling in the left panel, and vice versa. I like it!  And it's great to finally have bullets rendered again.

So, what's the consensus here? Shall we close this PR and accept #8226 in its place?

**Comment by braingram** [comment]
I'm personally a fan of "sticky_navigation" turned off (https://github.com/spacetelescope/jwst/pull/8226).

@tapastro what are your thoughts on this "sticky" situation? Also, I can't explain why your system is showing a scroll bar on firefox. If it's helpful I'd be happy to do a slack huddle and try to inspect the page while you share screen.

**Comment by tapastro** [comment]
I'd also vote for sticky off.

I'm not sure what I was seeing with scroll bars previously, but 8226 has the scroll bar I'd expect on the right, so I think it's good to go.

**Comment by braingram** [comment]
Thanks! I updated this PR to disable sticky navigation and rebased it to bring it up to date. I'll close #8226

**Review by hbushouse — APPROVED** [review]

**Pull request merged**
