### PR TITLE
JP-3112 Ensure matched exposures generated by list of candidates continue processing

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [JP-3112](https://jira.stsci.edu/browse/JP-3112)

This PR addresses issue discovered in operations very shortly after jwst 1.9.4 was installed. Associations were not being created when multiple candidates were specified for generation. The issue was that exposures, once matched to one candidate association, were not available to be matched with other candidates' associations. The fix ensures that all other combinations of (exposure, candidate) continue to process against all other associations.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] ~updated relevant documentation~
- [ ] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by hbushouse — APPROVED** [review]
Code updates look fine to me. Just curious, since the refactoring that caused this problem was done to increase processing speed, does this change have any noticeable impact (back in the bad direction) on processing speed?

**Comment by stscieisenhamer** [comment]
[Association-only test regression run](https://plwishmaster.stsci.edu:8081/job/RT/job/eisenhamer-dev/313/)

**Comment by stscieisenhamer** [comment]
About speed: I haven't had a chance to test in detail. However, I haven't noticed any significant change.

**Comment by hbushouse** [comment]
> Short run succeeded. [Full regression run](https://plwishmaster.stsci.edu:8081/job/RT/job/eisenhamer-dev/314/) underway.

Yikes! Run 314 has a lot of E's showing up in the log.

**Comment by hbushouse** [comment]
> [Full regression](https://plwishmaster.stsci.edu:8081/job/RT/job/eisenhamer-dev/315/) with the current edit context and a code rebase which should include the `opencv` fix.

It appears to be using context 1063, which is based on 1062 and 1062 did NOT include the pars ref files to turn on the snowball correction. So I don't think this is testing the snowball correction, which we would want to do to make sure it works OK when Cal 1.9.6 gets installed in Ops and Ops (eventually) turns on snowball.

**Comment by hbushouse** [comment]
Just for grins I started a RT run at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/587/ that uses your PR branch and context 1061, just to see what happens when we turn on snowball correction.

**Comment by hbushouse** [comment]
> Just for grins I started a RT run at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/587/ that uses your PR branch and context 1061, just to see what happens when we turn on snowball correction.

D'oh!  That was a waste. I forgot that the update to dependencies to include opencv was only made to the 1.9.5 branch, not master. So my run against master was a total bust.  Sigh.  Let's try that again ...

**Comment by stscieisenhamer** [comment]
Except for two LRS referernece file changes, my [regression](https://plwishmaster.stsci.edu:8081/job/RT/job/eisenhamer-dev/315/) ran clean, against 1065. Still does need a run against 1061.

**Comment by stscieisenhamer** [comment]
I think this PR is good to go. Probably best to then add to the 1.9.5x branch and do any further testing there.

**Pull request merged**
