### PR TITLE
Update jwst to updated astropy.modeling api

### PR DESCRIPTION
**Pull request by jdavies-st**
This is a fork of 

https://github.com/spacetelescope/jwst/tree/inputs-outputs-transforms

with a couple tests fixed and the dependency hashes in `requirements-sdp.txt` and `setup.py` updated.  Using to see what fails in unit and regression tests.

The astropy URL will need to be changed from `nden/astropy` to `astropy/astropy` with the approriate hash once that bugfix PR is merged into master.

Standard regression test being run on this branch here

https://plwishmaster.stsci.edu:8081/job/RT/job/jdavies-dev/148/

### CODE REVIEW

**Comment by jdavies-st** [comment]
Running regression tests again

https://plwishmaster.stsci.edu:8081/job/RT/job/jdavies-dev/149/

**Comment by jdavies-st** [comment]
Currently seeing a failure in the unit test
```
_________________________ test_spatial_transform_miri __________________________

    def test_spatial_transform_miri():
        wcsinfo = {
            'dec_ref': -0.00601415671349804,
            'ra_ref': -0.02073605215697509,
            'roll_ref': -0.0,
            'v2_ref': -453.5134,
            'v3_ref': -373.4826,
            'v3yangle': 0.0,
            'vparity': -1}
    
        instrument = {
            'detector': 'MIRIMAGE',
            'filter': 'P750L',
            'name': 'MIRI'}
    
        observation = {
            'date': '2019-01-01',
            'time': '17:00:00'}
    
        subarray = {
            'fastaxis': 1,
            'name': 'SLITLESSPRISM',
            'slowaxis': 2,
            'xsize': 72,
            'xstart': 1,
            'ysize': 416,
            'ystart': 529}
    
        exposure = {
            'duration': 11.805952,
            'end_time': 58119.85416,
            'exposure_time': 11.776,
            'frame_time': 0.11776,
            'group_time': 0.11776,
            'groupgap': 0,
            'integration_time': 11.776,
            'nframes': 1,
            'ngroups': 100,
            'nints': 1,
            'nresets_between_ints': 0,
            'nsamples': 1,
            'readpatt': 'FAST',
            'sample_time': 10.0,
            'start_time': 58119.8333,
            'type': 'MIR_LRS-SLITLESS',
            'zero_frame': False}
    
        im = ImageModel((416, 72))
        im.data = np.random.rand(416, 72)
        im.error = np.random.rand(416, 72) / 100
    
        im.meta.wcsinfo._instance.update(wcsinfo)
        im.meta.instrument._instance.update(instrument)
        im.meta.observation._instance.update(observation)
        im.meta.exposure._instance.update(exposure)
        im.meta.subarray._instance.update(subarray)
    
>       out = AssignWcsStep.call(im)

jwst/resample/tests/test_resample_spec.py:143: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
jwst/stpipe/step.py:561: in call
    return instance.run(*args)
jwst/stpipe/step.py:398: in run
    step_result = self.process(*args)
jwst/assign_wcs/assign_wcs_step.py:83: in process
    result = load_wcs(input_model, reference_file_names, slit_y_range)
jwst/assign_wcs/assign_wcs.py:53: in load_wcs
    pipeline = mod.create_pipeline(input_model, reference_files)
jwst/assign_wcs/miri.py:43: in create_pipeline
    pipeline = exp_type2transform[exp_type](input_model, reference_files)
jwst/assign_wcs/miri.py:171: in lrs
    dettotel = lrs_distortion(input_model, reference_files)
jwst/assign_wcs/miri.py:335: in lrs_distortion
    v2v3toxrot = subarray_dist.inverse | xysubtoxyrot | models.Mapping([0], n_inputs=2)
src/astropy/astropy/modeling/core.py:59: in <lambda>
    return lambda left, right: CompoundModel(oper, left, right, **kwargs)
src/astropy/astropy/modeling/core.py:2486: in __init__
    inverse=self)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'NoneType' object has no attribute 'param_names'") raised in repr()] CompoundModel object at 0x10e22bcd0>
op = '|'
left = <CompoundModel(angle_0=-0.24155757, offset_1=37.5, offset_2=300.)>
right = None, name = None
inverse = <[AttributeError("Attribute "name" not found") raised in repr()] CompoundModel object at 0x10ce0c3d0>

    def __init__(self, op, left, right, name=None, inverse=None):
        self.__dict__['_param_names'] = None
        self._n_submodels = None
        self.op = op
        self.left = left
        self.right = right
        self._bounding_box = None
        self._user_bounding_box = None
        self._leaflist = None
        self._opset = None
        self._tdict = None
        self._parameters = None
        self._parameters_ = None
        self._param_metrics = None
        self._has_inverse = False  # may be set to True in following code
        if inverse:
            self.inverse = inverse
    
>       if op != 'fix_inputs' and len(left) != len(right):
E       TypeError: object of type 'NoneType' has no len()

src/astropy/astropy/modeling/core.py:2431: TypeError
```

**Comment by nden** [comment]
Indeed this is a real error. I pushed a possible fix and will look into it more later today. Can you run this test again?

**Comment by nden** [comment]
I pushed another commit to the astropy branch. This test passes now locally.

**Comment by jdavies-st** [comment]
I incremented the astropy hash and kicked off another regression test run.

https://plwishmaster.stsci.edu:8081/job/RT/job/jdavies-dev/150/

One nice thing is that running the test suite seems to be ~30% faster now using the new `astropy.modeling` changes in the pipeline.  Is that expected?

**Comment by jdavies-st** [comment]
Closing this PR in favor of #4216.

**Pull request closed without merging**
