### PR TITLE
remove global multiprocessing.set_start_method

### PR DESCRIPTION
**Pull request by braingram**
Fixes: https://github.com/spacetelescope/jwst/issues/8306

Without setting a multiprocessing start method (using the default) on linux with python 3.12 results in a `DeprecationWarning`.

Warnings for python 3.12:
```
  jwst/jump/tests/test_detect_jumps.py: 9 warnings
  jwst/jump/tests/test_jump_step.py: 24 warnings
    /opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=2483) is multi-threaded, use of fork() may lead to deadlocks in the child.
      self.pid = os.fork()
  
  jwst/ramp_fitting/tests/test_ramp_fit.py::test_multiprocessing
  jwst/ramp_fitting/tests/test_ramp_fit.py::test_multiprocessing2
  jwst/ramp_fitting/tests/test_ramp_fit_step.py::test_ramp_fit_step[2]
  jwst/ramp_fitting/tests/test_ramp_fit_step.py::test_ramp_fit_step[2]
  jwst/ramp_fitting/tests/test_ramp_fit_step.py::test_ramp_fit_step[half]
  jwst/ramp_fitting/tests/test_ramp_fit_step.py::test_ramp_fit_step[half]
  jwst/ramp_fitting/tests/test_ramp_fit_step.py::test_ramp_fit_step[all]
  jwst/ramp_fitting/tests/test_ramp_fit_step.py::test_ramp_fit_step[all]
    /opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=2486) is multi-threaded, use of fork() may lead to deadlocks in the child.
      self.pid = os.fork()
```
This is due to `fork` being unsafe for applications that use threads. This warning was previously silenced using a global `set_start_method` which can cause issues for other packages (see https://github.com/spacetelescope/jwst/issues/8306).

stcal (which is the primary user of multiprocessing in the pipeline) was updated:
https://github.com/spacetelescope/stcal/pull/249

~This PR temporarily uses stcal main (that can be removed prior to merge or after a stcal release is made) to pick up the changes in the above PR and updates the remaining multiprocessing usage in wfss_contam to only set `forkserver` in a context (to not impact other packages).~ EDIT: stcal 1.7.0 (now the required version) contains the required changes

### CODE REVIEW

**Comment by braingram** [comment]
Regtests running at: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1310/

**Comment by braingram** [comment]
Note: prior to merge the dev dependency on stcal should be removed.

**Comment by braingram** [comment]
The 3.9 and oldestdeps failures look like they'd be addressed in:
https://github.com/spacetelescope/jwst/pull/8365

**Comment by braingram** [comment]
@emolter this PR has some minor overlap with https://github.com/spacetelescope/jwst/pull/8417 I gave #8417 a skim and it looks like it would make the wfss changes in this PR unecessary. However this PR has additional related changes in `jump` and `ramp_fitting`. What would you recommend for sequencing these? As the changes in this PR are minor compared to #8417 can we get this one merged first? I'll rebase and let me know if you'd like to see a newer regtest run.

**Review by emolter — COMMENTED** [review]
The code changes look good to me.  Are there any regtests that test the multiprocessing modes for these steps?  Not sure what that would even look like...

RE my PR for the wfss_contam step, I think it's completely fine to merge this right away.  It will be a while before that PR gets merged as there are lots of outstanding issues.

**Comment by braingram** [comment]
Thanks for taking a look!

> The code changes look good to me. Are there any regtests that test the multiprocessing modes for these steps? Not sure what that would even look like...

Not that I'm aware of. The main motivation for adding the `set_start_method` in https://github.com/spacetelescope/jwst/pull/8093 is the `DeprecationWarning`s that will be seen if using `fork` (the default on linux) and python 3.12. I'm happy to go into more details but the tldr is that we need to set a non-fork set start method to avoid these warnings.

> RE my PR for the wfss_contam step, I think it's completely fine to merge this right away. It will be a while before that PR gets merged as there are lots of outstanding issues.

Good to know. Let me if there's anything I can do to help.

**Pull request merged**
