### PR TITLE
JP-1748 Refactor DataTypes handling of ModelContainer

### LINKED ISSUE #5405: cube build crashes writing out files
_Issue [JP-1748](https://jira.stsci.edu/browse/JP-1748) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

Cube build has recently started crashing when I run it in spec3; in the example directory provided typing

'strun cube_build.cfg l3asn.json'

produces a crash:

2020-10-14 08:59:16,509 - stpipe.cube_build - INFO - Total # of holes for IFU cube is : 0
2020-10-14 08:59:16,510 - stpipe.cube_build - INFO - Time to find Cube Flux = 0.1 s
----------------------------------------------------------------------
ERROR RUNNING STEP 'CubeBuildStep':
 I/O operation on closed file
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/Users/drlaw/jwcode/jwst/scripts/strun", line 26, in <module>
 step = Step.from_cmdline(sys.argv[1:])
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 163, in from_cmdline
 return cmdline.step_from_cmdline(args)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
 step.run(*positional)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 399, in run
 step_result = self.process(*args)
 File "/Users/drlaw/jwcode/jwst/jwst/cube_build/cube_build_step.py", line 342, in process
 cube_result = thiscube.build_ifucube()
 File "/Users/drlaw/jwcode/jwst/jwst/cube_build/ifu_cube.py", line 809, in build_ifucube
 result = self.setup_final_ifucube_model(ifile_ref)
 File "/Users/drlaw/jwcode/jwst/jwst/cube_build/ifu_cube.py", line 2183, in setup_final_ifucube_model
 self.blend_output_metadata(ifucube_model)
 File "/Users/drlaw/jwcode/jwst/jwst/cube_build/ifu_cube.py", line 2357, in blend_output_metadata
 blendmeta.blendmodels(IFUCube, inputs=self.input_models,
 File "/Users/drlaw/jwcode/jwst/jwst/model_blender/blendmeta.py", line 110, in blendmodels
 newmeta, newtab = get_blended_metadata(inputs, verbose=verbose)
 File "/Users/drlaw/jwcode/jwst/jwst/model_blender/blendmeta.py", line 229, in get_blended_metadata
 new_meta, newtab = final_rules.apply(input_models)
 File "/Users/drlaw/jwcode/jwst/jwst/model_blender/blendrules.py", line 257, in apply
 new_model = models[0].copy()
 File "/Users/drlaw/jwcode/jwst/jwst/datamodels/model_base.py", line 362, in copy
 self.clone(result, self, deepcopy=True, memo=memo)
 File "/Users/drlaw/jwcode/jwst/jwst/datamodels/model_base.py", line 341, in clone
 instance = copy.deepcopy(source._instance, memo=memo)
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/copy.py", line 172, in deepcopy
 y = _reconstruct(x, memo, *rv)
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/copy.py", line 296, in _reconstruct
 value = deepcopy(value, memo)
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/copy.py", line 151, in deepcopy
 copier = getattr(x, "*_deepcopy_*", None)
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/site-packages/asdf/tags/core/ndarray.py", line 362, in *_getattr_*
 return getattr(self._make_array(), attr)
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/site-packages/asdf/tags/core/ndarray.py", line 260, in _make_array
 self._shape, self._strides, self._dtype, len(block))
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/site-packages/asdf/fits_embed.py", line 39, in *_len_*
 return self._hdu.data.nbytes
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/site-packages/astropy/utils/decorators.py", line 758, in *_get_*
 val = self.fget(obj)
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/site-packages/astropy/io/fits/hdu/image.py", line 230, in data
 data = self._get_scaled_image_data(self._data_offset, self.shape)
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/site-packages/astropy/io/fits/hdu/image.py", line 699, in _get_scaled_image_data
 raw_data = self._get_raw_data(shape, code, offset)
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 520, in _get_raw_data
 return self._file.readarray(offset=offset, dtype=code, shape=shape)
 File "/Users/drlaw/anaconda3/envs/jwst/lib/python3.8/site-packages/astropy/io/fits/file.py", line 286, in readarray
 filepos = self._file.tell()
ValueError: I/O operation on closed file

Per input from [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) it sounds like this is related to recent changes to the datamodel I/O.

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [JP-1748](https://jira.stsci.edu/browse/JP-1748)
Resolves #5405 

Refactored `DataTypes` handling of `ModelContainer` to be more simplified and avoid premature closing of models before usage is completed.

### CODE REVIEW

**Review by jdavies-st — COMMENTED** [review]
You will want to put the new regression test into its own module.  Currently the `test_miri_mrs.py` module already takes forever to run, and all the tests in a given module run serially on one core.  Better to have it parallelized across different cores than all on one core.

Also, that test uses separate input data from the other tests in that module, so it really should be using a different `rtdata` instance if you're going to module scope the fixture.

**Review by hbushouse — COMMENTED** [review]
Looks OK to me, but I agree with @jdavies-st that the new test should probably be in a separate module, just to allow for multiple processes to get through them all faster.

Requisite reminder about change log entry ...

**Review by hbushouse — COMMENTED** [review]
So now it looks like the new regtest is in both modules. Forgot to remove it from the existing one?

**Review by jemorrison — APPROVED** [review]
The changes to cube_build look fine to me.

**Comment by stscieisenhamer** [comment]
> So now it looks like the new regtest is in both modules. Forgot to remove it from the existing one?

DOH!

**Comment by hbushouse** [comment]
I was going to point out the unused imports in the old test module, but now you have the Travis pep8 check doing that for me.

**Review by hbushouse — APPROVED** [review]

**Pull request merged**
