### PR TITLE
JP-2284 New residual fringe  updating background fitting  

### LINKED ISSUE #6350: Refactor initial background spline fit to use astropy
_Issue [JP-2284](https://jira.stsci.edu/browse/JP-2284) was created on JIRA by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson):_

Currently, the residual fringe correction step relies on the external dependency [BayesicFitting](https://github.com/dokester/BayesicFitting). This library is a mathematical modeling and data fitting library intended for astronomy applications based on the Herschel Common Science System. This library is largely incompatible with astropy and its modeling package, which is the common mathematical modeling and fitting package used throughout the rest of the JWST pipeline. Moreover, BayesicFitting is not as well supported or maintained as astropy. Thus it is undesirable to include another external dependency on a less well maintained library, when much of that functionality can be derived directly from astropy.

The first step of the residual fringe correction involves fitting a spline model to the data in order to fit the background of the data. This step relies entirely on models and fitters included in the BayesicFitting package. Thus this background step must be refactored so that it only relies on astropy derived or compatible models and fitters instead.

### PR DESCRIPTION
**Pull request by jemorrison**
Closes #6350 
Resolves [JP-2284](https://jira.stsci.edu/browse/JP2284)
This PR replaces #6739 which replaced #6475
**Description**

PR 6739 got confused with conflicts so I pulled down a clean version and made this PR. 
This PR includes the updates in JP-2284 plus additional changes provided by the MIRI instrument team (Patrick Kavanagh). Updates to the residual_fringe code were needed to support changing to astropy fitting of the background for columns with less than ideal data.
The description in JP-2284 is "This PR switches the residual fringe background fit step from using BayesicFitting based splines to the new astropy based splines. This is part of the effort to remove the dependency of jwst on BayesicFitting. Note that this will change the results of the residual fringe correction slightly due to numerical differences in how astropy (scipy based) splines are computed/fit vs how BayesicFitting splines are computed/fit.
Note that the bugfix https://github.com/astropy/astropy/pull/12523 is required for this code to function properly."

The astropy updates in 12523 have already been included into astropy.

This ticket is closes the step 1 in the parent ticket JP-2344.

A few unit tests were added to this PR. One of them is the test the background fitting. 
Checklist
- [x] Tests
- [ ] Documentation
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Comment by jemorrison** [comment]
@eslavich @WilliamJamieson @hbushouse 
This PR is essentially the same as #6739 . I had too many conflicts to figure out what how to fix them and I could not get a CI test to pass (Oldest dependency versions) . So I created this PR with a fresh branch. The unit test that gives an error in the CI test  runs on my local branch with pytest. 
Is this a case that someone with the "power" can just merge this into master - or is this unit test error a real error ?

**Comment by jemorrison** [comment]
@eslavich #6739 had conflicts (rebase problems) in my local branch. William and I were working on it at the same time and I can not figure out how to pull in the branch to get his updates - I had too many rebase issues. That is what I meant by conflicts (probably a poor word choice). 
So if we can use this PR it would be best since #6739 has a bunch of other CI failures - which I could not fix cause I could not get my branch rebase clean.

**Comment by WilliamJamieson** [comment]
> @eslavich #6739 had conflicts (rebase problems) in my local branch. William and I were working on it at the same time and I can not figure out how to pull in the branch to get his updates - I had too many rebase issues. That is what I meant by conflicts (probably a poor word choice). So if we can use this PR it would be best since #6739 has a bunch of other CI failures - which I could not fix cause I could not get my branch rebase clean.

I still don't see the difference running `git diff fringe_testing_1_18..new_fringe_test` only shows differences in `CHANGES.rst` (PR number) and the addition of a new line in `jwst/resdual_fringe/tests/test_background_fit.py`. Neither of these should change the CI. I believe the vast majority of the failures are related to the `GAIADR2` related tests. I think this PR was created and passed the CI prior is issue appearing (its related to remote data).

**Comment by tapastro** [comment]
I tested this in a new environment - after creating the env and `pip install ".[test]"`, I ran `minimum_deps` and ran `pip install -r requirements-min.txt` to run on those deps. I can reproduce the two failures and one error in residual_fringe/test_background_fit.py. Log here:
```
==================================================== ERRORS ====================================================
___________________________ ERROR at teardown of test_background_fit[good_col.fits] ____________________________

item = <Function test_background_fit[good_col.fits]>, nextitem = <Function test_background_fit[edge_col.fits]>

    def pytest_runtest_teardown(item, nextitem):
        # a "skipped" test will not have been called with
        # pytest_runtest_setup, so therefore won't have an
        # "open_files" member
        if (not item.config.getvalue('open_files') or not hasattr(item, 'open_files')):
            return
    
        start_open_files = item.open_files
        del item.open_files
    
        # We now force garbage collection - we need to do this because e.g. in cases
        # where a memory mapped array was opened in the test and then goes out of
        # scope at the end of the test, the original file may still be open but
        # can be properly closed by forcing gc.collect(). This was found to be
        # needed for astropy.io.fits under certain circumstances.
        gc.collect()
    
        open_files = _get_open_file_list()
    
        # This works in tandem with the test_open_file_detection test to
        # ensure that it creates one extra open file.
        if item.name == 'test_open_file_detection':
            assert len(start_open_files) + 1 == len(open_files)
            return
    
        not_closed = set()
        open_files_ignore = item.config.getini('open_files_ignore')
        for filename in open_files:
            ignore = False
    
            for ignored in open_files_ignore:
    
                # Note that we use fnmatch rather than re for simplicity since
                # we are dealing with file paths - fnmatch works with the standard
                # * and ? wildcards in paths.
    
                if not os.path.isabs(ignored):
                    # Since the path is not absolute, we convert it to
                    # */<original_path> to make sure it matches absolute paths.
                    ignored = os.path.join('*', ignored)
    
                if fnmatch.fnmatch(filename, ignored):
                    ignore = True
                    break
    
            if ignore:
                continue
    
            if filename not in start_open_files:
                not_closed.add(filename)
    
        if len(not_closed):
            msg = ['File(s) not closed:']
            for name in not_closed:
                msg.append('  {0}'.format(name))
>           raise AssertionError('\n'.join(msg))
E           AssertionError: File(s) not closed:
E             /Users/tpauly/PycharmProjects/jwst/jwst/residual_fringe/tests/good_col.fits

../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/pytest_openfiles/plugin.py:137: AssertionError
_____________________________ ERROR at setup of test_background_fit[edge_col.fits] _____________________________

cls = <class '_pytest.runner.CallInfo'>, func = <function call_runtest_hook.<locals>.<lambda> at 0x7fe8e9a8a040>
when = 'setup', reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        """Call func, wrapping the result in a CallInfo.
    
        :param func:
            The function to call. Called without arguments.
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/_pytest/runner.py:340: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/_pytest/runner.py:261: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/pluggy/_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/pluggy/_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/_pytest/runner.py:156: in pytest_runtest_setup
    item.session._setupstate.setup(item)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_pytest.runner.SetupState object at 0x7fe8e90c7310>
item = <Function test_background_fit[edge_col.fits]>

    def setup(self, item: Item) -> None:
        """Setup objects along the collector chain to the item."""
        needed_collectors = item.listchain()
    
        # If a collector fails its setup, fail its entire subtree of items.
        # The setup is not retried for each item - the same exception is used.
        for col, (finalizers, exc) in self.stack.items():
>           assert col in needed_collectors, "previous item was not torn down properly"
E           AssertionError: previous item was not torn down properly

../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/_pytest/runner.py:489: AssertionError
=================================================== FAILURES ===================================================
______________________________________ test_background_fit[good_col.fits] ______________________________________

file = 'good_col.fits'

    @pytest.mark.parametrize("file", ['good_col.fits', 'edge_col.fits'])
    def test_background_fit(file):
        """ test fit_1d_background_complex"""
    
        (col_data, col_weight, col_wnum, bg_fit, store_freq) = read_fit_column(file)
    
>       bg_fit2, _ = utils.fit_1d_background_complex(col_data, col_weight,
                                                     col_wnum, ffreq=store_freq)

tests/test_background_fit.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
utils.py:368: in fit_1d_background_complex
    bg_model = robust_fitter(spline_model, x, y, weights=w)
fitter.py:70: in __call__
    nparams, deg_of_freedom = self._deg_of_freedom(new_model, x, weights)
fitter.py:51: in _deg_of_freedom
    nparams = len(self._params(model))
fitter.py:41: in _params
    return _model_to_fit_params(model)[0]
../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/astropy/modeling/fitting.py:1671: in _model_to_fit_params
    params = list(model.parameters)
../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/astropy/modeling/core.py:1183: in parameters
    self._parameters_to_array()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Spline1D(knot0=1., knot1=1., knot2=1., knot3=1.00106096, knot4=1.00306157, knot5=1.00507703, knot6=1.00710748, knot7=..., coeff68=0.87897773, coeff69=0.62760651, coeff70=-0.46302731, coeff71=0.16760849, coeff72=0., coeff73=0., coeff74=0.)>

    def _parameters_to_array(self):
        # Now set the parameter values (this will also fill
        # self._parameters)
        param_metrics = self._param_metrics
        for name in self.param_names:
            param = getattr(self, name)
            value = param.value
            if not isinstance(value, np.ndarray):
                value = np.array([value])
>           self._parameters[param_metrics[name]['slice']] = value.ravel()
E           KeyError: 'slice'

../../../../miniconda3/envs/oldest-deps/lib/python3.8/site-packages/astropy/modeling/core.py:2549: KeyError
```

pip list:
```
(oldest-deps) wintermute:residual_fringe tpauly$ pip list
Package                       Version
----------------------------- ---------------------
alabaster                     0.7.12
asdf                          2.8.2
asdf-astropy                  0.1.2
asdf-coordinates-schemas      0.1.0
asdf-standard                 1.0.1
asdf-transform-schemas        0.2.2
asdf-wcs-schemas              0.1.1
astropy                       5.0
astropy-sphinx-theme          1.1
attrs                         21.4.0
Babel                         2.9.1
BayesicFitting                2.7.2
certifi                       2021.10.8
chardet                       3.0.4
charset-normalizer            2.0.12
ci-watson                     0.6.0
codecov                       2.1.12
colorama                      0.4.4
coverage                      6.3.2
crds                          11.6.0
cycler                        0.11.0
docutils                      0.17.1
drizzle                       1.13.4
filelock                      3.6.0
flake8                        4.0.1
fonttools                     4.29.1
future                        0.18.2
getch                         1.0
gwcs                          0.18.0
idna                          2.8
imagesize                     1.3.0
importlib-metadata            4.11.2
importlib-resources           5.4.0
iniconfig                     1.1.1
Jinja2                        3.0.3
jmespath                      0.10.0
jsonschema                    3.0.2
jwst                          1.4.3.dev62+g821ce2c3
kiwisolver                    1.3.2
lxml                          4.8.0
MarkupSafe                    2.1.0
matplotlib                    3.5.1
mccabe                        0.6.1
mistune                       0.8.4
numpy                         1.19.0
numpydoc                      1.2
packaging                     21.3
Parsley                       1.3
photutils                     1.2.0
Pillow                        9.0.1
pip                           21.2.4
pluggy                        1.0.0
poppy                         1.0.1
psutil                        5.7.2
py                            1.11.0
pycodestyle                   2.8.0
pyerfa                        2.0.0.1
pyflakes                      2.4.0
Pygments                      2.11.2
pyparsing                     2.2.1
pyrsistent                    0.18.1
pytest                        7.0.1
pytest-cov                    3.0.0
pytest-doctestplus            0.12.0
pytest-openfiles              0.5.0
python-dateutil               2.8.2
pytz                          2021.3
PyYAML                        6.0
requests                      2.22.0
requests-mock                 1.9.3
scipy                         1.6.0
semantic-version              2.9.0
setuptools                    60.9.3
six                           1.16.0
snowballstemmer               2.2.0
spherical-geometry            1.2.22
Sphinx                        4.4.0
sphinx-asdf                   0.1.2
sphinx-astropy                1.7.0
sphinx-automodapi             0.14.1
sphinx-bootstrap-theme        0.8.1
sphinx-gallery                0.10.1
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stcal                         0.6.1
stdatamodels                  0.4.0
stpipe                        0.3.1
stsci.image                   2.3.5
stsci.imagestats              1.6.3
stsci-rtd-theme               0.0.2
stsci.stimage                 0.2.5
tomli                         2.0.1
tweakwcs                      0.7.2
urllib3                       1.25.11
wheel                         0.37.1
zipp                          3.7.0
```

**Comment by tapastro** [comment]
Update: they pass when upgrading the installed version of astropy to 5.0.1, so this might require an update to the minimum dependencies.

**Comment by WilliamJamieson** [comment]
> Update: they pass when upgrading the installed version of astropy to 5.0.1, so this might require an update to the minimum dependencies.

You are exactly correct. I did a fix a long time ago for this work in astropy for this exact bug, and backported it to 5.0.1. I forgot all about this. Thanks for reminding me.

Note I cannot reproduce the bug easily because I am not running python 3.8 (I'll need to create a 3.8 environment to fix it) so the minimum requirements create a polyfit error.

**Review by hbushouse — APPROVED** [review]
LGTM.

The oldest dependencies CI failure is understood and unrelated to this PR. So I'm OK with merging. What say the rest of you?

**Comment by WilliamJamieson** [comment]
> LGTM.
> 
> The oldest dependencies CI failure is understood and unrelated to this PR. So I'm OK with merging. What say the rest of you?

@hbushouse I put all the fixes in #6739 as this one was an unnecessary duplicate of it.

**Comment by hbushouse** [comment]
Closing, because it's a duplicate of #6739

**Pull request closed without merging**
