### PR TITLE
JP-3019: Remove code trimming zero-valued cube planes

### PR DESCRIPTION
**Pull request by drlaw1558**
Resolves [JP-3019](https://jira.stsci.edu/browse/JP-3019)

Given other updates in the past couple years this is no longer necessary, and always producing cubes of known size is helpful for both science analyses and MAST.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [x] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by jemorrison — COMMENTED** [review]
Looks good to me

**Review by jemorrison — APPROVED** [review]

**Comment by hbushouse** [comment]
So, just curious, instead of trimming out wavelength planes and/or spaxels that have no good data, they are now kept and all set to NaN?

**Comment by hbushouse** [comment]
Is there any mention of trimming wavelength planes in the docs that now needs updating to indicate that they are NOT trimmed?

**Comment by drlaw1558** [comment]
@hbushouse That's right, now they will be NaNs instead.  There is thus the possibility that we have some all-NaN cubes, but that it itself should be informative.  I looked for any documentation that might need to be updated already- the only relevant section was the one changed above (specifying NaN values aren't exclusively outside the footprint if there's bad data).

**Comment by hbushouse** [comment]
Looks like @jemorrison ran regression tests against this PR branch at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/489/ and I'd say all of the differences look like they're expected based on these code changes. So I think this is ready for prime time.

**Pull request merged**
