### PR TITLE
drop support for Python 3.8

### PR DESCRIPTION
**Pull request by zacharyburnett**
This PR drops support for Python 3.8 from CI and package metadata.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by hbushouse — APPROVED** [review]
Looks OK to me. I guess the change log entry will need to be moved, now that 1.10.2 is about to go out.

**Review by nden — CHANGES_REQUESTED** [review]
RTD configuration file needs to be updated as well.

**Comment by zacharyburnett** [comment]
It looks like there are a few deprecation errors in the RTD build:
https://readthedocs.org/projects/jwst-pipeline/builds/20117878/
```
/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/envs/7552/lib/python3.11/site-packages/sphinx_asdf/connections.py:25: RemovedInSphinx70Warning: sphinx.io.read_doc() is deprecated.
  doctree = read_doc(env.app, env, env.doc2path(docname))
```

**Comment by nden** [comment]
@zacharyburnett I wonder if it's the dot command that's tripping the build
` dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting`

**Review by nden — APPROVED** [review]
I suggest we merge this PR, since it's blocking PRs in other repositories and figure out the RTD issue separately.

**Comment by braingram** [comment]
> @zacharyburnett I wonder if it's the dot command that's tripping the build ` dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting`

The missing 'dot' might be fixed by apt installing graphviz (this was needed for asdf):
https://github.com/asdf-format/asdf/pull/1504/files#diff-03efc769b870804394632e45d7885272b44c16939517fb31c9d7c614d2ffae57R4-R5
as some of the readthedocs docker images no longer have graphviz:
https://github.com/readthedocs/readthedocs.org/issues/8800#issuecomment-1007261093

**Comment by hbushouse** [comment]
Don't we have statements in the README and/or pypi stating the min python required? If so, those need updating too.

**Comment by nden** [comment]
Let's try the change suggested by @braingram. Seems pretty straightforward.

**Comment by nden** [comment]
I think the latest error can be fixed by bumping scikit-image to > 0.19 or may be better just removing a version and letting photutils handle it.

**Pull request merged**
