### PR TITLE
Fix test warnings and files left behind

### LINKED ISSUE #7128: Unit tests polluting the repository working directory
_Issue [JP-2822](https://jira.stsci.edu/browse/JP-2822) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

After running `pytest`, the following files show up in the current working directory, which is usually the top level of the `jwst` repository.

Such files should be in a temp folder.

foo1_median.fits
foo1_outlier_i2d.fits
foo1_outlier_median.fits
foo2_outlier_i2d.fits
foo3_outlier_i2d.fits
step_OutlierDetectionStep_foo1_blot.fits
step_OutlierDetectionStep_foo2_blot.fits
step_OutlierDetectionStep_foo3_blot.fits

### PR DESCRIPTION
**Pull request by jdavies-st**
Closes #7128 

Resolves [JP-2822](https://jira.stsci.edu/browse/JP-2822)

This PR fixes 2 deprecations seen in the current unit test suite with pytest and scipy.

```python
jwst/assign_wcs/tests/test_schemas.py: 21 warnings
  /Users/jdavies/miniconda3/envs/jwst/lib/python3.8/site-packages/_pytest/python.py:195: PytestRemovedIn8Warning: Passing None has been deprecated.
  See https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests for alternatives in common use cases.
    result = testfunction(**testargs)

```

```python
jwst/wfs_combine/tests/test_wfs_combine.py: 25 warnings
  /home/runner/work/jwst/jwst/jwst/wfs_combine/wfs_combine.py:740: DeprecationWarning: Please use `center_of_mass` from the `scipy.ndimage` namespace, the `scipy.ndimage.measurements` namespace is deprecated.
  centroid = scipy.ndimage.measurements.center_of_mass(central_cutout)
```

Also, it fixes `outlier_detection` tests that littered the working dir (often the repo) with intermediate files that were written out.  Fixed by removing the problematic fixture, simplifying the one test that used the fixture, and using the `_jail` fixture for it, as for all the other tests that write out results.

**Checklist for maintainers**
- [ ] ~added entry in `CHANGES.rst` within the relevant release section~
- [x] updated or added relevant tests
- [ ] ~updated relevant documentation~
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by stscieisenhamer — APPROVED** [review]

**Comment by stscieisenhamer** [comment]
[regression run](https://plwishmaster.stsci.edu:8081/job/RT/job/eisenhamer-dev/287/)

**Comment by jdavies-st** [comment]
`_jail` is a pytest fixture provided by `ci-watson`:

https://github.com/spacetelescope/ci_watson/blob/57df82132b3977decae820187d3e53d5323225b8/ci_watson/plugin.py#L69-L77

When the test runs, the setup is to change dir to a tempdir, run the test, and then cd back out on teardown.  A different pristine temp dir for each test function.

**Comment by hbushouse** [comment]
I agree about the naming. Maybe "purgatory" would've been better ...

**Comment by jdavies-st** [comment]
Yeah, something like `temp_chdir` and `temp_chdir_module` would have been better.  Eventually it would be good to update these anyway to use `pathlib.Path` instead of `os.path`.  Pytest provides the infrastructure already via the `tmp_path` and `tmp_path_factory` fixtures.  Low priority.

https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html

**Comment by hbushouse** [comment]
Hmmm, sounds like another regtest hackathon project for us to tackle between Christmas and New Years!  ;-)

**Comment by jdavies-st** [comment]
I'll make 🍿 !

**Pull request merged**
