### PR TITLE
Jp 580 miri reset

### PR DESCRIPTION
**Pull request by jemorrison**
@cracraft  take at look at this PR - this should close JP-580

### CODE REVIEW

**Review by stscieisenhamer — APPROVED** [review]

**Comment by jemorrison** [comment]
DO NOT MERGE. AWAITING new MIRI dark reference files with reset anomaly effect removed.

**Comment by jemorrison** [comment]
I think we can go ahead and merge this and get in build 7.7. I did more testing yesterday and it works as expected.

**Comment by hbushouse** [comment]
OK. We're iterating on regtests due to the merge of the SIP coeffs work, so as soon as that's settled out I'll merge this and start a new round of regtests.

**Review by hbushouse — APPROVED** [review]
Are there any docs that need updating, e.g. the description of calwebb_detector1?

**Pull request merged**
