### PR TITLE
Split NIRSpec IFU regtests

### PR DESCRIPTION
**Pull request by hbushouse**
Split the spec2 and spec3 tests contained in `test_nirspec_ifu.py` into separate test modules, so that they can run in parallel, thus saving execution time for the whole regtest suite (these are the 2 longest running tests of all).

### CODE REVIEW

**Comment by jdavies-st** [comment]
The way these tests are set up, running the spec3 pipeline depends on having run the spec2 pipeline, just like our miri and nircam imaging tests.  I don't think this will work.

The solution probably lies in either having them not depend on each other (i.e. separate fixtures for separate input) or just `@pytest.mark.skip` until we can sort out why cube build is taking forever.  Or turning off `outlier_detection`.

**Comment by hbushouse** [comment]
I don't think that's the case. The spec3 test uses inputs that are independent from the spec2 run and the fixtures also don't depend on one another. I successfully ran each of them, one at a time, locally. They have independent inputs and outputs.

**Comment by hbushouse** [comment]
Ah, you're correct that `run_spec3` has `run_spec2` as an argument, but that test is the one that's being skipped. The only spec3 test that's running is `run_spec3_multi`, which has no dependencies on `run_spec2`.

**Comment by hbushouse** [comment]
Perhaps I should just remove the code for `run_spec3` and `test_spec3` (leaving only the `multi` versions), as opposed to having it set to skip. If anyone ever removed the skip, it would then have problems because of the dependency on `run_spec2`.

**Comment by jdavies-st** [comment]
Thanks for the clarification.  And yeah, this looks good.

We should remove the data from bytesalad for the test that was removed as well.

**Comment by hbushouse** [comment]
I'll figure out which dataset(s) need to be removed and will do that.

I've also been promised a brand new set of recent NIRSpec IFU simulations from INS sometime this week, so I may end up replacing everything that's currently used in these tests.

**Pull request merged**
