### PR TITLE
Remove soon-to-be-deprecated usage of AsdfFile.open

### LINKED ISSUE #2795: AsdfFile.open will be deprecated
`AsdfFile.open` will be deprecated in asdf v2.2.0 (no due date) spacetelescope/asdf#579. jwst will need the corresponding changes after asdf 2.2.0 is released.

### PR DESCRIPTION
**Pull request by drdavella**
This will take effect once https://github.com/spacetelescope/asdf/pull/579 is merged, but there's no harm in making this change now.

This closes #2795.

### CODE REVIEW

**Comment by drdavella** [comment]
Seems like the Jenkins job is hung...

**Comment by nden** [comment]
The `wcs` tags were removed from asdf as they are now (and have been for quite a while) in gwcs. Something must be using an old tag or it's a bug. I'll investigate.

**Comment by drdavella** [comment]
I think the problem is files in `jwst/exp_to_source/tests/data` that contain references to `!wcs/...`. We just removed the old WCS tags and schemas from ASDF, so these tags won't resolve anymore.

I suspect that a simple search and replace of these for the corresponding tag name in `gwcs` should fix the problem. For example, `!wcs/step-1.0.0` should become `tag:stsci.edu:gwcs/step-1.0.0`.

**Comment by drdavella** [comment]
@jdavies-st the short answer is yes. Of course, you could grab an older version of `asdf`, but that's not ideal, is it?

@nden we made this change expecting that there would be no residual uses of ASDF WCS, but maybe we should go with a deprecation period instead.

We're in a tricky place here because if we don't try to be diligent about cleaning these things up, ASDF is going to become a giant crapball of spaghetti code that mostly supports legacy uses. We should handle this better going forward, but I don't think we were expecting this particular change to have any  impact.

Unfortunately, making this change has exposed some other issues that will need to be addressed (see #2849).

Considering the hour, I think the best course of action is probably to sit down with a tall scotch and forget all about of this for a little while.

**Comment by stscieisenhamer** [comment]
hold it...wait...i'm in the wrong conversations....

**Comment by philhodge** [comment]
Is it (theoretically) possible to edit the ASDF extension to change the tags, as an alternative to rebuilding the extension?

**Comment by drdavella** [comment]
@philhodge if I understand correctly, it's probably possible in theory, but I'm not sure we want to support this for the general case since it will probably be fairly difficult to maintain. It would probably be easier just to write a one-off script to convert files like these, but at that point it might just be easier to regenerate them.

**Comment by drdavella** [comment]
Looks like we're good now!

**Comment by jdavies-st** [comment]
Thanks @drdavella!

**Pull request merged**
