### PR TITLE
JP-3077: Change the Computation in Ramps with only One Good Group in the 0th Group

### PR DESCRIPTION
**Pull request by kmacdonald-stsci**
Resolves [JP-3077](https://jira.stsci.edu/browse/JP-3077)

This PR addresses the incorrect usage of group_time for ramps that have non-zero groupgap and the 0th group the only good group in the ramp. Because of the readout pattern, the time for the 0th group alone is computed using (NFrames+1)*TFrame/2, instead.  The code changes for this are in STCAL (https://github.com/spacetelescope/stcal/pull/142).  Those changes affected JWST testing of ramp fit, which have been addressed in this PR.

This PR should not be merged, until the STCAL PR gets merged.

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by hbushouse — APPROVED** [review]

**Comment by hbushouse** [comment]
We'll obviously want to wait to merge this until the stcal PR has been merged and a new stcal release is available.

**Comment by hbushouse** [comment]
Regression test running at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/570

**Review by dmggh — APPROVED** [review]
Looks fine to me.

**Comment by hbushouse** [comment]
Regression test run showed only unrelated failures due to a recent update of MIRI ref files.

**Comment by zacharyburnett** [comment]
> We'll obviously want to wait to merge this until the stcal PR has been merged and a new stcal release is available.

`stcal 1.3.4` includes the analogous changes to `stcal`: https://github.com/spacetelescope/stcal/releases/tag/1.3.4

**Pull request merged**
