### PR TITLE
Make skymatch not fail in match mode when images do not overlap

### PR DESCRIPTION
**Pull request by mcara**
This PR makes `skymatch` not to fail when images do not overlap. This addresses the failure in `skymatch` reported in  https://github.com/spacetelescope/jwst/pull/2796#issue-226360537 likely occurring either because images have all pixels flagged as bad or the parts that are "good" do not overlap.

After this PR, `skymatch` will "succeed" but it will set `meta.cal_step.skymatch = "SKIPPED"` for images for which sky could not have been computed.

### CODE REVIEW

**Comment by mcara** [comment]
CC: @hbushouse @stscicrawford

**Comment by mcara** [comment]
@jdavies-st Thanks for catching this! I fixed this in the new commit.

**Comment by jdavies-st** [comment]
Fixed!  I do notice the following in the log of running that dataset through:
```
2018-11-02 10:40:44,879 - stpipe.Image3Pipeline - INFO - Matching sky values across all input images...
2018-11-02 10:40:44,918 - stpipe.Image3Pipeline.skymatch - INFO - Step skymatch running with args (<ModelContainer>,).
2018-11-02 10:40:45,048 - stpipe.Image3Pipeline.skymatch - INFO -  
2018-11-02 10:40:45,048 - stpipe.Image3Pipeline.skymatch - INFO - ***** jwst.skymatch.skymatch.match() started on 2018-11-02 10:40:45.048614
2018-11-02 10:40:45,048 - stpipe.Image3Pipeline.skymatch - INFO -  
2018-11-02 10:40:45,048 - stpipe.Image3Pipeline.skymatch - INFO - Sky computation method: 'global+match'
2018-11-02 10:40:45,048 - stpipe.Image3Pipeline.skymatch - INFO - Sky matching direction: DOWN
2018-11-02 10:40:45,048 - stpipe.Image3Pipeline.skymatch - INFO - Sky subtraction from image data: OFF
2018-11-02 10:40:45,049 - stpipe.Image3Pipeline.skymatch - INFO -  
2018-11-02 10:40:45,049 - stpipe.Image3Pipeline.skymatch - INFO - ----  Computing differences in sky values in overlapping regions.
2018-11-02 10:40:45,127 - stpipe.Image3Pipeline.skymatch - WARNING - Unable to compute sky: No valid data in common image areas
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - WARNING -    *  Image ID=jw00601012001_02102_00004_nrcblong_cal.fits: Unable to compute sky value
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00004_nrcblong_cal.fits. Sky background: 0
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - WARNING -    *  Image ID=jw00601012001_02102_00005_nrcblong_cal.fits: Unable to compute sky value
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00005_nrcblong_cal.fits. Sky background: 0
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - WARNING -    *  Image ID=jw00601012001_02102_00001_nrcblong_cal.fits: Unable to compute sky value
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00001_nrcblong_cal.fits. Sky background: 0
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - WARNING -    *  Image ID=jw00601012001_02102_00003_nrcblong_cal.fits: Unable to compute sky value
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00003_nrcblong_cal.fits. Sky background: 0
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - WARNING -    *  Image ID=jw00601012001_02102_00002_nrcblong_cal.fits: Unable to compute sky value
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00002_nrcblong_cal.fits. Sky background: 0
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - WARNING -    *  Image ID=jw00601012001_02102_00006_nrcblong_cal.fits: Unable to compute sky value
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00006_nrcblong_cal.fits. Sky background: 0
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - INFO -  
2018-11-02 10:40:45,128 - stpipe.Image3Pipeline.skymatch - INFO - ----  Computing "global" sky - smallest sky value across *all* input images.
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -  
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -    "Global" sky value correction: 26489.250634765624 [not converted]
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -  
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO - ----  Final (match+global) sky for:
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00004_nrcblong_cal.fits. Sky background: 26489.3 (old=0, delta=26489.3)
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00005_nrcblong_cal.fits. Sky background: 26489.3 (old=0, delta=26489.3)
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00001_nrcblong_cal.fits. Sky background: 26489.3 (old=0, delta=26489.3)
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00003_nrcblong_cal.fits. Sky background: 26489.3 (old=0, delta=26489.3)
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00002_nrcblong_cal.fits. Sky background: 26489.3 (old=0, delta=26489.3)
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -    *  Image ID=jw00601012001_02102_00006_nrcblong_cal.fits. Sky background: 26489.3 (old=0, delta=26489.3)
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -  
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO - ***** jwst.skymatch.skymatch.match() ended on 2018-11-02 10:40:45.130556
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO - ***** jwst.skymatch.skymatch.match() TOTAL RUN TIME: 0:00:00.081942
2018-11-02 10:40:45,130 - stpipe.Image3Pipeline.skymatch - INFO -  
2018-11-02 10:40:45,139 - stpipe.Image3Pipeline.skymatch - INFO - Step skymatch done
```
Is this expected?

**Comment by jdavies-st** [comment]
I see that those values are just the values in the images.  So looks good to me.  Merge away.

**Comment by mcara** [comment]
@jdavies-st Given the quality of test data, [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) here is not unexpected.

**Comment by jdavies-st** [comment]
I'm going to add that this dataset now fails in `outlier detection`.  Should it really even be sent through `outlier detection`?  None of the pointings overlap or are even close to one another.  How do we make sure that associations are associating things with clustered pointings in test data?

**Comment by jdavies-st** [comment]
Hold off on merging actually, once we fix our CI builds, it would be nice to kick off another CI run on this PR to at least get one passing.

**Comment by mcara** [comment]
@jdavies-st What is going on?

**Comment by jdavies-st** [comment]
Let's try the CI builds on this one again.  `numpy` and `astropy` are once again playing nice together.

**Comment by jdavies-st** [comment]
Closing the PR and reopening it kicks of the CI builds without having to change anything in the PR.  ;-)

**Comment by jdavies-st** [comment]
I think the failures on `ssbjenkins` are unrelated.  Feel free to squash and merge.

**Pull request merged**
