### PR TITLE
JP-2078: Update flat-field docs for variances

### LINKED ISSUE #6021: Update flat_field intro section on ERR array
_Issue [JP-2078](https://jira.stsci.edu/browse/JP-2078) was created on JIRA by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft):_

The documentation for the Flat field step contains this text in Readthedocs:

At its basic level this step flat-fields an input science data set by dividing by a flat-field reference image. In particular, the SCI array from the flat-field reference file is divided into both the SCI and ERR arrays of the science data set, and the flat-field DQ array is combined with the science DQ array using a bitwise OR operation. Details for particular modes are given in the sections below.

 

And:

 
 * If the science data have been taken using a subarray and the flat-field reference file is a full-frame image, extract the corresponding subarray region from the flat-field data.

 * Find pixels that have a value of NaN or zero in the FLAT reference file SCI array and set their DQ values to “NO_FLAT_FIELD.”

 * Reset the values of pixels in the flat that have DQ=”NO_FLAT_FIELD” to 1.0, so that they have no effect when applied to the science data.

 * Apply the flat by dividing it into the science exposure SCI and ERR arrays.

 * Propagate the FLAT reference file DQ values into the science exposure DQ array using a bitwise OR operation.

 

At the bottom of the page, it does go into more detail about how the ERR arrays are calculated, but the intro text could be updated to make it more clear that the calculation is not as simple as 'divide the flat into both the SCI and ERR arrays.

### PR DESCRIPTION
**Pull request by hbushouse**
Closes #6021

Resolves [JP-2078](https://jira.stsci.edu/browse/JP-2078)

**Description**

This PR updates the docs for the flat-field step to include the latest information on propagation of variance and error arrays.

Checklist
- [ ] Tests
- [x] Documentation
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Review by stscieisenhamer — APPROVED** [review]
still a failing test by LGTM

**Review by nden — APPROVED** [review]

**Review by nden — CHANGES_REQUESTED** [review]
Needs a rebase to resolve conflicts

**Comment by nden** [comment]
Other than the rebase looks good!

**Comment by hbushouse** [comment]
OK, rebase has been done to resolve conflicts and all tests other than codecov now pass.

**Review by nden — APPROVED** [review]

**Pull request merged**
