### PR TITLE
0.12x

### PR DESCRIPTION
**Pull request by nden**
This is release `0.12.2`.

It is based on `0.12.1` and the following were cherry-picked from master: `5e27d7b`, `7df749f` and `8f47c69`. In addition the CI files `.travis.yml`, `Jenkinsfile` and `JenkinsfileRT` were copied from master to allow tests to run with np 1.5.2.

### CODE REVIEW

**Comment by jdavies-st** [comment]
The Travis failures here are`flake8` checks that came with the new version of `flake8` last Friday.  They have been fixed in `master`.  I think they can be ignored here.

**Comment by stscicrawford** [comment]
Agreed they can be ignored.   CRDS context should be set to 495.

**Comment by stscieisenhamer** [comment]
FYI: Works with the jw00711 data.

**Comment by jdavies-st** [comment]
The regression tests are running against the `0.12x` branch right now:

https://boyle.stsci.edu:8081/job/RT/job/JWST-jdavies/47/

**Pull request merged**
