### PR TITLE
JP-2597: Fix call to filteroffset in assign_wcs

### PR DESCRIPTION
**Pull request by nden**
Closes #
Resolves [JP-2597](https://jira.stsci.edu/browse/JP-2597)

**Description**

This PR fixes a typo in parsing the `filteroffset` file for nircam and niriss which resulted in the WCS not using this file.

Checklist
- [ ] Tests
- [ ] Documentation
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Comment by hbushouse** [comment]
Looks like a unit test is failing.

**Review by hbushouse — APPROVED** [review]

**Comment by hbushouse** [comment]
Oy, you just can't win. Now that the unit test works, pycodestyle is unhappy.

**Comment by aliciacanipe** [comment]
Would it be possible to open a JP ticket for this just to link to this github issue, without messing anything up on the SCSB end? There was a request from our NRC team (just for tracking issues we might have with data, WCS, etc.). Thanks for solving this so fast!!

**Comment by hbushouse** [comment]
> Would it be possible to open a JP ticket for this just to link to this github issue, without messing anything up on the SCSB end? There was a request from our NRC team (just for tracking issues we might have with data, WCS, etc.). Thanks for solving this so fast!!

Yes, you can create a JP ticket for this problem. We'll put a reference in it to this PR.

**Comment by hbushouse** [comment]
OK to merge?

**Comment by aliciacanipe** [comment]
K JP ticket here: https://jira.stsci.edu/browse/JP-2597 Thanks for the super fast investigation/fix!

**Pull request merged**
