### PR TITLE
Create regression test okifying tool

### PR DESCRIPTION
**Pull request by eslavich**
https://jira.stsci.edu/browse/JP-854

I had 62 files to update after #3745 and ended up writing a script to parse the Jenkins output and offer files to okify.  The output looks like this:

```
Fitsdiff output:

E            fitsdiff: 3.2.1
E            a: /data1/jenkins/workspace/RT/JWST/clone/test_outputs/popen-gw11/test_coron3_10/jw99999-a3001_t1_nircam_f140m-maskbar_i2d.fits
E            b: /data1/jenkins/workspace/RT/JWST/clone/test_outputs/popen-gw11/test_coron3_10/truth/jw99999-a3001_t1_nircam_f140m-maskbar_i2d_ref.fits
E            HDU(s) not to be compared:
E             ASDF
E            Keyword(s) not to be compared:
E             CAL_VCS CAL_VER CRDS_CTX CRDS_VER DATE FILENAME NAXIS1 TFORM*
E            Table column(s) not to be compared:
E             CAL_VCS CAL_VER CRDS_CTX CRDS_VER DATE FILENAME NAXIS1 TFORM*
E            Maximum number of different data values to be reported: 10
E            Relative tolerance: 1e-05, Absolute tolerance: 1e-05
E
E           Primary HDU:
E
E              Headers contain differences:
E                Keyword         [45] has different values:
E                   a> Resampling parameter information
E                   b> Metadata describing resampling done using this data
E                Keyword NDRIZ    has different comments:
E                   a> Number of groups/pointings included in resample
E                    ?           -------
E                   b> Number of pointings included in resampled produ
E                    ?                                         +++++++
E                Keyword TEXPTIME has different comments:
E                   a> [s] Total exposure time for product
E                    ? ----
E                   b> Total exposure time for product

Artifactory result path: jwst-pipeline-results/2019-07-08_jenkins-RT-JWST-314_0/test_coron3_10/jw99999-a3001_t1_nircam_f140m-maskbar_i2d.fits
Artifactory truth path: jwst-pipeline/dev/nircam/test_coron3/truth/jw99999-a3001_t1_nircam_f140m-maskbar_i2d_ref.fits

Enter 'o' to okify, 's' to skip:
```

### CODE REVIEW

**Comment by dmggh** [comment]
Since there are no array comparisons shown in the output you posted, does that mean that any/all array values are identical (within the tolerance) ? Or were there no arrays ?

**Comment by eslavich** [comment]
That's right, the schema changes in #3745 changed a bunch of keyword titles but nothing of substance.

**Comment by jdavies-st** [comment]
History Eraser Button
:tada:

**Comment by hbushouse** [comment]
Would be useful to add usage instructions to the wiki.

**Comment by jdavies-st** [comment]
This is great.  Already used it on the `0.13.7` snapshot on Artifactory.  Love it.  Thanks Ed!  🚀

**Comment by eslavich** [comment]
Here's the wiki update: https://github.com/spacetelescope/jwst/wiki/Maintaining-Regression-Tests#interactive-okifying

**Pull request merged**
