### PR TITLE
Merge stpipe-transition branch to master

### PR DESCRIPTION
**Pull request by eslavich**
This includes the following PRs:

https://github.com/spacetelescope/jwst/pull/5600
https://github.com/spacetelescope/jwst/pull/5645
https://github.com/spacetelescope/jwst/pull/5648
https://github.com/spacetelescope/jwst/pull/5650
https://github.com/spacetelescope/jwst/pull/5652
https://github.com/spacetelescope/jwst/pull/5665
https://github.com/spacetelescope/jwst/pull/5678
https://github.com/spacetelescope/jwst/pull/5697
https://github.com/spacetelescope/jwst/pull/5698

Regression test run is ~~pending~~ passing here: https://plwishmaster.stsci.edu:8081/job/RT/job/eslavich-dev/58

### CODE REVIEW

**Comment by hbushouse** [comment]
Quick question before even doing a complete review: will merging this take away or change any current behaviors of stpipe that might crash people's existing scripts, etc. (e.g. something like the .call() or .run() methods going away)? Or does it simply start adding new functionality?

**Comment by eslavich** [comment]
> Quick question before even doing a complete review: will merging this take away or change any current behaviors of stpipe that might crash people's existing scripts, etc. (e.g. something like the .call() or .run() methods going away)? Or does it simply start adding new functionality?

I intended for there not to be any breaking changes in these commits.  Our near-term goal is to get the stpipe code into a separate package (where romancal can use it) without negatively impacting jwst in any way.

**Review by jdavies-st — APPROVED** [review]
I'm not going to re-review all the code changes here, as I already reviewed those PR-by-PR as they were merged into the `stpipe-transition` epic branch.  But this looks good.

✅ regression tests pass


@hbushouse to review where we are:

This PR still keeps `jwst.stpipe` internal to `jwst`, and doesn't change any fundamental behavior.

But after this is merged, it will be then possible to copy over all the library parts of `jwst.stpipe` directly to the `stpipe` package, as Ed has already done here

https://github.com/spacetelescope/stpipe/pull/11

And then do one more PR in `jwst` to start using the `stpipe` package, as we've already done for `stdatamodels`.

So this looks great!

**Comment by hbushouse** [comment]
Uh oh. Run away, run away!

**Pull request merged**
