### PR TITLE
JenkinsfileRT: Add unstable deps

### LINKED ISSUE #3880: Start running regression tests with astropy master
Issue [JP-906](https://jira.stsci.edu/browse/JP-906) was created by Nadia Dencheva:

jwst will need to switch to the new astropy.modeling package which is currently only on astropy master. Travis testing already runs with the dev versions of dependencies. We need to start running the regression test suite with dev versions as well.

### PR DESCRIPTION
**Pull request by jhunkeler**
Resolves #3880.

### CODE REVIEW

**Comment by jdavies-st** [comment]
If we take the tack of running these in a matrix on Jenkins, then we're going to have to dial down the `pytest-xdist` parallelization, i.e. change both test builds to `pytest -n 15` so they can share the total number of cores.

The other option is to run them at different times of the day using different JenkinsfileRTs, as in my PR #3747.  This has more overhead on the Jenkins setup and maintenance I feel.

So if the first option works, then let's do it.

**Comment by nden** [comment]
We can start with these hashes in requirements-dev.txt

astropy: a8f496b26
photutils: 99f101be95af67f
gwcs: 3e2bc108ec3a66139

**Comment by jdavies-st** [comment]
I kicked off an RT job to try out the new JenkinsfileRT in this branch

https://plwishmaster.stsci.edu:8081/job/RT/job/jdavies-dev/

Looks like the dev build failed, as it couldn't compile `numpy`.  Do we want `numpy` dev in this build?  Or would it be better to just use the just-released version for now?

**Comment by nden** [comment]
:+1: for a public release of numpy

**Comment by jhunkeler** [comment]
@jdavies-st @nden 
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST_UNSTABLE/

When you click `Build with Parameters` you'll see a big text area. You can populate it with `pip install` arguments

```
somethingA
"somethingB<1.2.3"
git+https://something.com/blah.git
-r a_requirements_file_somewhere_else.txt
--upgrade numpy
# and so on
```

**Comment by nden** [comment]
New hash for modeling is d16e0ff5ff3ba780b. Could we rerun the regression tests with this configuration? If they pass then this is ready to merge.

**Pull request closed without merging**
