### PR TITLE
JP-2031: Add FULLP to NIRCam SUBARRAY enum 

### LINKED ISSUE #5935: Add "FULLP" to list of allowed NIRCam subarray values
_Issue [JP-2031](https://jira.stsci.edu/browse/JP-2031) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

JWSTKD-424 request the addition of the value "FULLP" to the list of allowed NIRCam SUBARRAY values. The SCSB datamodels need the same update.

### PR DESCRIPTION
**Pull request by tapastro**
Closes #5935 
Resolves [JP-2031](https://jira.stsci.edu/browse/JP-2031)

**Description**

This PR adds the requested value to the SUBARRAY enum in both core and subarray schemas.

Checklist
- [ ] Tests
- [ ] Documentation
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Comment by stscirij** [comment]
Does the new entry also need to go into keyword_psubarray.schema.yaml?

**Comment by tapastro** [comment]
> Does the new entry also need to go into keyword_psubarray.schema.yaml?

I'd be willing to bet that it does - failure in process of using 'grep "SUBARRAY" *' to find files to edit!

**Comment by jdavies-st** [comment]
Unrelated to your changes, is there a reason we have the full list of subarray enums in both `core.schema` and `subarray.schema`?  Couldn't `core.schema` reference `subarray.schema` so there's no chance of them getting out of sync?  It seems `subarray.schema` is used mostly (exclusively?) by reference files.

**Review by hbushouse — APPROVED** [review]
LGTM. And kudos on adding a change log entry before a reviewer could mention it.

**Comment by hbushouse** [comment]
> Unrelated to your changes, is there a reason we have the full list of subarray enums in both `core.schema` and `subarray.schema`? Couldn't `core.schema` reference `subarray.schema` so there's no chance of them getting out of sync? It seems `subarray.schema` is used mostly (exclusively?) by reference files.

Yes, consolidating the various sub-schemas to be inherited by top-level schemas is another one of those items on our very long list of "someday" tasks.

**Pull request merged**
