### PR TITLE
[SCSB-169] add user input to specify `CRDS_CONTEXT`

### PR DESCRIPTION
**Pull request by zacharyburnett**
Resolves [SCSB-169](https://jira.stsci.edu/browse/SCSB-169)

[image](https://github.com/zacharyburnett/jwst/actions/workflows/ci.yml)

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by zacharyburnett** [comment]
tested with
- https://github.com/zacharyburnett/jwst/actions/runs/10354845360
- https://github.com/zacharyburnett/jwst/actions/runs/10354846655

**Review by braingram — APPROVED** [review]
LGTM.

Once this is merged it would be helpful to trigger the `ci` `ci_cron` and `tests_devdeps` jobs to make sure they work work with a defined context.

**Comment by braingram** [comment]
Runs started with `jwst_1255.pmap`:
- ci: https://github.com/spacetelescope/jwst/actions/runs/10357731826
- ci_cron: https://github.com/spacetelescope/jwst/actions/runs/10357727841
- test_devdeps: https://github.com/spacetelescope/jwst/actions/runs/10357730367

**Comment by braingram** [comment]
All jobs picked up the 1255 context. I'm not sure why the oldestdeps just reported "This job failed" https://github.com/spacetelescope/jwst/actions/runs/10357731826/job/28670412829

**Pull request merged**
