### PR TITLE
Add pytest.ini file to select correct junit test report family 

### PR DESCRIPTION
**Pull request by rendinam**
The Jenkins test reporting plugin requires a correctly constructed schema of the report produced by pytest. This `pytest.ini` directive provides that.
Honored as of pytest 2.4.

### CODE REVIEW

**Comment by jdavies-st** [comment]
Horray!

Could it pull this from the `[tool:pytest]` section of `setup.cfg`?  Or does it need to by in a `pytest.ini` file?

**Comment by rendinam** [comment]
It should work via a `[tool:pytest]` section of `setup.cfg`. Would you prefer that?

**Comment by jdavies-st** [comment]
I think so.  Currently that's where we have our `pytest` setup.  Would be nice to keep it all in one place.

This is going to fix that `pytest foo || true` Jenkins stuff, right?  If so, fantastic.

**Comment by rendinam** [comment]
Yes. It should correct the errant job `SUCCESS` status when one or more tests fail.

**Pull request merged**
