### PR TITLE
adding tests for changes in JP-3311 and minor fixes

### PR DESCRIPTION
**Pull request by penaguerrero**
Resolves [JP-3311](https://jira.stsci.edu/browse/JP-3311)

Closes #

This PR adds tests for changes made in [https://github.com/spacetelescope/jwst/pull/8464](https://github.com/spacetelescope/jwst/pull/8464,)

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [x] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by penaguerrero** [comment]
running reg test at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1438/

**Comment by penaguerrero** [comment]
reg test running: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1439/

**Review by emolter — COMMENTED** [review]
Code changes look good to me!  Can you run a new regtest on Jenkins, at least for the tests that were previously failing (test_miri_lrs_slit_spec3 and test_nirspec_fs_spec3)?

**Review by hbushouse — APPROVED** [review]
Code changes seem fine to me and latest regtest run showed only 1 unrelated failure. So I think this is good to go.

**Pull request merged**
