### PR TITLE
replace `opencv-python` with pre-built CPU-only `opencv-python-headless`

### PR DESCRIPTION
**Pull request by zacharyburnett**
Closes https://github.com/spacetelescope/stenv/issues/103

This PR tests replacing `opencv-python` with `opencv-python-headless`, a pre-built CPU-only binary, to resolve the issue raised in https://github.com/spacetelescope/stenv/issues/103

**Checklist for maintainers**
- [ ] ~added entry in `CHANGES.rst` within the relevant release section~
- [ ] ~updated or added relevant tests~
- [ ] ~updated relevant documentation~
- [ ] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] ~Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)~

### CODE REVIEW

**Comment by zacharyburnett** [comment]
regression test running at https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/696/pipeline/

**Comment by zacharyburnett** [comment]
upstream tests at https://github.com/spacetelescope/stcal/pull/164

**Comment by hbushouse** [comment]
Looks like the regtest run was aborted. Will there be another?

**Comment by zacharyburnett** [comment]
> Looks like the regtest run was aborted. Will there be another?

yes I ran one at https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/697/pipeline

It looks like there were quite a few failures:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/697/testReport/
with quite a few of them having the following:
```
TypeError: 'Polynomial1D' object is not iterable
```

**Comment by braingram** [comment]
> > Looks like the regtest run was aborted. Will there be another?
> 
> yes I ran one at https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/697/pipeline
> 
> It looks like there were quite a few failures: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/697/testReport/ with quite a few of them having the following:
> 
> ```
> ../miniconda/envs/tmp_env0/lib/python3.9/site-packages/stdatamodels/jwst/transforms/converters/jwst_models.py:34: in to_yaml_tree_transform
>     xll = [list(m) for m in model.xmodels]
> E   TypeError: 'Polynomial1D' object is not iterable
> ```

Those errors also appeared in CI runs for this PR for stdatamodels (where @nden mentioned they should be resolved by new reference files).

https://github.com/spacetelescope/stdatamodels/pull/160#issuecomment-1525708078

and are likely related to: https://github.com/spacetelescope/stdatamodels/pull/124

**Comment by hbushouse** [comment]
That's because you're letting stdatamodels float to the latest. Must pin to "stdatamodels==1.4.0".

**Comment by zacharyburnett** [comment]
> That's because you're letting stdatamodels float to the latest. Must pin to "stdatamodels==1.4.0".

Ah right, I remember your announcement

**Comment by zacharyburnett** [comment]
regtest running at https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/702/pipeline with `stdatamodels==1.4.0`

**Comment by zacharyburnett** [comment]
regression test is all green now 🎉

**Comment by hbushouse** [comment]
> regression test is all green now 🎉

I see that. One caveat though: the regtests only run on Linux. How do we know everything's OK with builds on a Mac?

**Review by hbushouse — APPROVED** [review]

**Comment by zacharyburnett** [comment]
Good point, I started a dev job at https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-devdeps/detail/JWST-devdeps/656/pipeline/ as well with `stdatamodels==1.4.0` to cover the MacOS tests

**Comment by zacharyburnett** [comment]
The MacOS tests are running into the ephemeral socket errors: https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-devdeps/detail/JWST-devdeps/656/pipeline/194#step-196-log-29

However, it looks like there were no import errors (so far), so we'll see if the test failures are just socket errors and precision differences between platforms

**Pull request merged**
