### PR TITLE
Update WCS calculations for the GUIDING modes

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [JP-2658](https://jira.stsci.edu/browse/JP-2658)

This PR addresses an issue where the appropriate algorithms to calculation the CRPIX* values of the WCS for the various GUIDING exposures was not used.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by drlaw1558** [comment]
This is a pretty enormous PR, I hadn't realized just how much work would be necessary to fix the FGS WCS.  Would it be possible to use the corresponding code to reprocess the guider data for a particular Visit and test performance by direct examination of those MAST-like data products?

**Comment by stscieisenhamer** [comment]
@drlaw1558 it was a surprise all around. If you had not gotten a chance to catch up on your original issue, discussions are still ongoing and, in fact, have been postponed until after next week due to vacations, etc. 

So, about testing, yes the code is currently in a "usable" state: The expected calculations will be made. However, the caveats are [listed in this gist](https://gist.github.com/stscieisenhamer/25eecbe8e70f8c60b9a1e6aec887168d), which, through my oversight, you were not included in notification of.

**Comment by nden** [comment]
The last update on this was almost a year ago. Is this work/PR still relevant?

**Comment by nden** [comment]
@stscieisenhamer Is this PR still relevant or was the issue resolved in the latest patch?

**Comment by stscieisenhamer** [comment]
This is still relevant. FGS team members were to answer some questions, but I have had no feedback on that yet. Will make it a point to ping them.

**Pull request closed without merging**
