### PR TITLE
JP-2371 Remove MIR_FLATMRS from Asn_Lv3MIRMRS rule

### LINKED ISSUE #6538: Eliminate flats from spec3 ASN tables
_Issue [JP-2371](https://jira.stsci.edu/browse/JP-2371) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

spec3 type ASN files for MIRI MRS observations that contain flat-field (lamp) exposures currently include entries for the flat exposures, in addition to the science exposures. This is causing problems in SDP workflows, because the flat products are not getting copied to the level-3 input directory and hence ASN completeness is not satisfied, so processing doesn't get triggered for the ASN.

The level-3 ASN rules for spec3 associations should be updated to **not** include the flat exposures to begin with. They are not needed for any level-3 processing anyway.

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Closes #6538
Resolves [JP-2371](https://jira.stsci.edu/browse/JP-2371)

**Description**

Do not add MIR_FLATMRS exposures to the Level 3 associations for MIRI MRS observations.

Checklist
- [x] Tests
- [ ] ~Documentation~
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Review by hbushouse — APPROVED** [review]
Looks good to me, assuming all CI tests pass. Could use a little more explanation of the change in the "description" field of the PR.

**Comment by hbushouse** [comment]
Oh, and what about any related documentation? I wonder if flats are mentioned anywhere in the docs and, if so, are they mentioned in the context of being in level 3 ASN's? (which would need changing now)

**Comment by stscieisenhamer** [comment]
Did go through everything, and there is nothing Level 3 specific. The only extensive set of documentation is for Level 2. There are a number of issue, one of which is JP-1059, to fill out the documentation for individual rules.

**Comment by hbushouse** [comment]
Clean test run (at least for the ones we care about). Merging.

**Comment by stscieisenhamer** [comment]
i've already have okify data...will do so momentarily.

**Pull request merged**
