### PR TITLE
JP-3781: Use center=False for compute_s_region_imaging

### LINKED ISSUE #8896: s_region from header is inconsistent with s_region from wcs.footprint()
_Issue [JP-3781](https://jira.stsci.edu/browse/JP-3781) was created on JIRA by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter):_

During testing of AL-837, it was discovered that the footprint encoded in model.meta.wcsinfo.s_region is not the same as what you get from wcs.footprint().  See the attached Python script. [^sregion_problem.py]

In short, by default the s_region is currently calculated as the center of each corner pixel of the footprint using stcal.alignment.util.compute_sregion_imaging(center=True), but it should calculate the true corners of the footprint using the same function but option center=False.

There is even a [comment in that function](https://github.com/spacetelescope/stcal/blob/dfe1d6d51f0c2a400dff918a52c779328ae19b7d/src/stcal/alignment/util.py#L674) stating that center=False is usually what is desired.

### PR DESCRIPTION
**Pull request by emolter**
Resolves [JP-3781](https://jira.stsci.edu/browse/JP-3781)

Closes #8896 

This PR addresses a bug that makes the s_region for imaging data slightly incorrect.  During testing of [AL-837](https://jira.stsci.edu/browse/AL-837), it was discovered that the footprint encoded in model.meta.wcsinfo.s_region is not the same as what you get from `wcs.footprint()`. By default in the pipeline, the s_region is currently calculated as the center of each corner pixel of the footprint using `stcal.alignment.util.compute_sregion_imaging(wcs, center=True)`, but it should calculate the true corners of the footprint using the same function but using the option `center=False`. There is even a [comment in that function](https://github.com/spacetelescope/stcal/blob/dfe1d6d51f0c2a400dff918a52c779328ae19b7d/src/stcal/alignment/util.py#L674) stating that `center=False` is usually what is desired.

The change is a one-liner, but a fairly large number of regression test failures are expected.

## Tasks
- [x] **request a review from someone specific**, to avoid making the maintainers review every PR
- [x] add a build milestone, i.e. `Build 11.3` (use the [latest build](https://github.com/spacetelescope/jwst/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [x] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types) 
  - [x] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [x] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [x] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

- ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
- ``changes/<PR#>.docs.rst``
- ``changes/<PR#>.stpipe.rst``
- ``changes/<PR#>.datamodels.rst``
- ``changes/<PR#>.scripts.rst``
- ``changes/<PR#>.fits_generator.rst``
- ``changes/<PR#>.set_telescope_pointing.rst``
- ``changes/<PR#>.pipeline.rst``

## stage 1
- ``changes/<PR#>.group_scale.rst``
- ``changes/<PR#>.dq_init.rst``
- ``changes/<PR#>.emicorr.rst``
- ``changes/<PR#>.saturation.rst``
- ``changes/<PR#>.ipc.rst``
- ``changes/<PR#>.firstframe.rst``
- ``changes/<PR#>.lastframe.rst``
- ``changes/<PR#>.reset.rst``
- ``changes/<PR#>.superbias.rst``
- ``changes/<PR#>.refpix.rst``
- ``changes/<PR#>.linearity.rst``
- ``changes/<PR#>.rscd.rst``
- ``changes/<PR#>.persistence.rst``
- ``changes/<PR#>.dark_current.rst``
- ``changes/<PR#>.charge_migration.rst``
- ``changes/<PR#>.jump.rst``
- ``changes/<PR#>.clean_flicker_noise.rst``
- ``changes/<PR#>.ramp_fitting.rst``
- ``changes/<PR#>.gain_scale.rst``

## stage 2
- ``changes/<PR#>.assign_wcs.rst``
- ``changes/<PR#>.badpix_selfcal.rst``
- ``changes/<PR#>.msaflagopen.rst``
- ``changes/<PR#>.nsclean.rst``
- ``changes/<PR#>.imprint.rst``
- ``changes/<PR#>.background.rst``
- ``changes/<PR#>.extract_2d.rst``
- ``changes/<PR#>.master_background.rst``
- ``changes/<PR#>.wavecorr.rst``
- ``changes/<PR#>.srctype.rst``
- ``changes/<PR#>.straylight.rst``
- ``changes/<PR#>.wfss_contam.rst``
- ``changes/<PR#>.flatfield.rst``
- ``changes/<PR#>.fringe.rst``
- ``changes/<PR#>.pathloss.rst``
- ``changes/<PR#>.barshadow.rst``
- ``changes/<PR#>.photom.rst``
- ``changes/<PR#>.pixel_replace.rst``
- ``changes/<PR#>.resample_spec.rst``
- ``changes/<PR#>.residual_fringe.rst``
- ``changes/<PR#>.cube_build.rst``
- ``changes/<PR#>.extract_1d.rst``
- ``changes/<PR#>.resample.rst``

## stage 3
- ``changes/<PR#>.assign_mtwcs.rst``
- ``changes/<PR#>.mrs_imatch.rst``
- ``changes/<PR#>.tweakreg.rst``
- ``changes/<PR#>.skymatch.rst``
- ``changes/<PR#>.exp_to_source.rst``
- ``changes/<PR#>.outlier_detection.rst``
- ``changes/<PR#>.tso_photometry.rst``
- ``changes/<PR#>.stack_refs.rst``
- ``changes/<PR#>.align_refs.rst``
- ``changes/<PR#>.klip.rst``
- ``changes/<PR#>.spectral_leak.rst``
- ``changes/<PR#>.source_catalog.rst``
- ``changes/<PR#>.combine_1d.rst``
- ``changes/<PR#>.ami.rst``

## other
- ``changes/<PR#>.wfs_combine.rst``
- ``changes/<PR#>.white_light.rst``
- ``changes/<PR#>.cube_skymatch.rst``
- ``changes/<PR#>.engdb_tools.rst``
- ``changes/<PR#>.guider_cds.rst``
</details>

### CODE REVIEW

**Comment by emolter** [comment]
[regression tests started here](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1799/)

**Comment by jemorrison** [comment]
Ok interesting. Cube_build does use the S_REGIONS.  S_REGIONS is filled in in assign_wcs right ? Should it be updated there so downstream steps get the correct values ?

**Comment by emolter** [comment]
> Quick question - I believe cube_build already uses S_REGION to get spatial footprints for IFU data. Does this change impact that mode?

This only impacts anything that uses `update_s_region_imaging`, which is called in assign_wcs on IMAGING_TYPES, in ResampleStep but not ResampleSpecStep for the result model(s), and in tweakreg when applying the tweakreg solution.  So I don't believe IFU data are impacted at all.

**Comment by emolter** [comment]
all regression test failures (aside from the 4 also on the main branch) pertain to S_REGION keywords, and all appear to be the magnitude we would expect.  Marking this ready for review.

**Review by mairanteodoro — APPROVED** [review]
Looks good to me.
Thanks, @emolter!

**Review by nden — APPROVED** [review]
LGTM, just aminor comment about the log message.

**Comment by emolter** [comment]
[restarting regression tests here](https://github.com/spacetelescope/RegressionTests/actions/runs/11393813827) on Github Actions, now that the last of the differences have been ok-ified there and the okify script operates there

**Comment by jemorrison** [comment]
I looked over the modules in assign_wcs.py util.py that deal with spectral data. The way they are designed I agree with you that I do not think this is an issue for spectral data. Not IFU nor NIRSpec slit data.

**Review by jemorrison — APPROVED** [review]
Nice catch.
Looks good

**Pull request merged**
