### PR TITLE
Jp 937 Create image3 associations for FGS_IMAGE exposures

### PR DESCRIPTION
**Pull request by ddavis-stsci**
Updated the logic for Constraint_Optical_Path in the level 3 rules to allow filter to be undefined and retain the constraint that subarray be defined.

### CODE REVIEW

**Comment by ddavis-stsci** [comment]
All association tests pass
= 133 passed, 2 xfailed, 1 warnings in 368.27s (0:06:08) =

Three of the regression tests fail and will need 10 image3 json files added for programs jw86600, jw97012, and jw97013.

Fixes JP-937

**Comment by hbushouse** [comment]
I noticed that in the image3 ASN file attached to JP-937 the input members are rate products. The inputs for level-3 ASN's should be cal products.

**Comment by ddavis-stsci** [comment]
I'll take another look. I missed that.

**Comment by hbushouse** [comment]
Results look good now. I approve. 👍

**Pull request merged**
