### PR TITLE
JP-3742: Remove allowed_memory and associated environment variable

### LINKED ISSUE #8775: Reconsider resample allowed_memory and associated environment variable
_Issue [JP-3742](https://jira.stsci.edu/browse/JP-3742) was created on JIRA by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter):_

The utility of the `allowed_memory` parameter to outlier detection and resample is not clear, and the existence of the parameter may lead to confusion.  The same is true of the environment variable `DMODEL_ALLOWED_MEMORY`, which serves as another way of setting that parameter.

The parameter is only used in one place, inside ResampleData, where the available memory is computed as 
```java
// (psutil.virtual_memory().available + psutil.swap_memory().total) * allowed_memory```
That value is compared with the expected array shape of the output wcs, and if the array would be too large, a custom `OutputTooLargeError` is raised.

There are multiple issues here, exposed in part by a conversation with Jesse Doggett about how this might be used in ops
 * It was realized that this OutputTooLargeError is not currently one of the metrics ops uses to check if a step ran out of memory.  The only things checked are: exit status 137 from strun (killed by sigkill); “ValueError: assignment destination is read-only”; and “MemoryErr”.  This OutputTooLargeError has apparently never been encountered.
 * In operations, the available memory read by `psutil` is not very helpful.  Each machine has 10 job slots, but the available memory is (very likely but not yet tested) reading the total for the whole machine.  Operations sets the available_memory equal to 0.7 (using the DMODEL_ALLOWED_MEMORY) environment variable, which is probably not a good idea for a machine running 10 jobs.
 * Checking the `output_wcs.array_shape` is most likely insufficient to know the actual memory usage of the step.  For example, testing has shown that when resample is called via outlier detection, the median computation is often more memory-hungry.  The pixmap calculation may also take lots of memory, as computing it involves lots of array copying and its final size is 2x the input size of float64s.  And the context array has the same height and width as the output but with a depth that is the number of input images divided by 32 (but see also JP-3707).

Soliciting additional input from [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett) and anyone else on team coffee who might have opinions or could provide clarity on what to do here.

### PR DESCRIPTION
**Pull request by emolter**
Resolves [JP-3742](https://jira.stsci.edu/browse/JP-3742)

Closes #8775

This PR removes the `allowed_memory` parameter from the resample and outlier detection steps, the `DMODEL_ALLOWED_MEMORY` environment variable that would set the value of that parameter, and the custom `OutputTooLargeError` that was raised when that memory limit was hit.

There are multiple reasons why this parameter was not working as intended and should be removed, exposed in part by a conversation with Jesse Doggett about how this might be used in operations:

- Checking the `output_wcs.array_shape` is insufficient to know the actual memory usage of the step in almost all cases.  For example, testing has shown that when resample is called via outlier detection, the median computation is often more memory-hungry.  The pixmap calculation may also take lots of memory, as computing it involves lots of array copying and its final size is 2x the input size of float64s.  And the context array has the same height and width as the output but with a depth that is the number of input images divided by 32 (but see also [JP-3707](https://jira.stsci.edu/browse/JP-3707)).  This likely explains why the OutputTooLargeError is never encountered in ops.
- It is not clear that the inclusion of swap memory is a good thing in many cases
- It was realized that this OutputTooLargeError is not currently one of the metrics ops uses to check if a step ran out of memory.  The only things checked are: exit status 137 from strun (killed by sigkill); “ValueError: assignment destination is read-only”; and “MemoryErr”.  This OutputTooLargeError has apparently never been encountered.
- In operations, the available memory read by `psutil` is not very helpful.  Each machine has 10 job slots, but the available memory is (very likely but not yet tested) reading the total for the whole machine.  Operations sets the available_memory equal to 0.7 (using the DMODEL_ALLOWED_MEMORY) environment variable, which is probably not a good idea for a machine running 10 jobs.

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [x] add a build milestone, i.e. `Build 11.3` (use the [latest build](https://github.com/spacetelescope/jwst/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [x] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types) 
  - [x] update or add relevant tests
  - [x] update relevant docstrings and / or `docs/` page
  - [x] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

- ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
- ``changes/<PR#>.docs.rst``
- ``changes/<PR#>.stpipe.rst``
- ``changes/<PR#>.datamodels.rst``
- ``changes/<PR#>.scripts.rst``
- ``changes/<PR#>.fits_generator.rst``
- ``changes/<PR#>.set_telescope_pointing.rst``
- ``changes/<PR#>.pipeline.rst``

## stage 1
- ``changes/<PR#>.group_scale.rst``
- ``changes/<PR#>.dq_init.rst``
- ``changes/<PR#>.emicorr.rst``
- ``changes/<PR#>.saturation.rst``
- ``changes/<PR#>.ipc.rst``
- ``changes/<PR#>.firstframe.rst``
- ``changes/<PR#>.lastframe.rst``
- ``changes/<PR#>.reset.rst``
- ``changes/<PR#>.superbias.rst``
- ``changes/<PR#>.refpix.rst``
- ``changes/<PR#>.linearity.rst``
- ``changes/<PR#>.rscd.rst``
- ``changes/<PR#>.persistence.rst``
- ``changes/<PR#>.dark_current.rst``
- ``changes/<PR#>.charge_migration.rst``
- ``changes/<PR#>.jump.rst``
- ``changes/<PR#>.clean_flicker_noise.rst``
- ``changes/<PR#>.ramp_fitting.rst``
- ``changes/<PR#>.gain_scale.rst``

## stage 2
- ``changes/<PR#>.assign_wcs.rst``
- ``changes/<PR#>.badpix_selfcal.rst``
- ``changes/<PR#>.msaflagopen.rst``
- ``changes/<PR#>.nsclean.rst``
- ``changes/<PR#>.imprint.rst``
- ``changes/<PR#>.background.rst``
- ``changes/<PR#>.extract_2d.rst``
- ``changes/<PR#>.master_background.rst``
- ``changes/<PR#>.wavecorr.rst``
- ``changes/<PR#>.srctype.rst``
- ``changes/<PR#>.straylight.rst``
- ``changes/<PR#>.wfss_contam.rst``
- ``changes/<PR#>.flatfield.rst``
- ``changes/<PR#>.fringe.rst``
- ``changes/<PR#>.pathloss.rst``
- ``changes/<PR#>.barshadow.rst``
- ``changes/<PR#>.photom.rst``
- ``changes/<PR#>.pixel_replace.rst``
- ``changes/<PR#>.resample_spec.rst``
- ``changes/<PR#>.residual_fringe.rst``
- ``changes/<PR#>.cube_build.rst``
- ``changes/<PR#>.extract_1d.rst``
- ``changes/<PR#>.resample.rst``

## stage 3
- ``changes/<PR#>.assign_mtwcs.rst``
- ``changes/<PR#>.mrs_imatch.rst``
- ``changes/<PR#>.tweakreg.rst``
- ``changes/<PR#>.skymatch.rst``
- ``changes/<PR#>.exp_to_source.rst``
- ``changes/<PR#>.outlier_detection.rst``
- ``changes/<PR#>.tso_photometry.rst``
- ``changes/<PR#>.stack_refs.rst``
- ``changes/<PR#>.align_refs.rst``
- ``changes/<PR#>.klip.rst``
- ``changes/<PR#>.spectral_leak.rst``
- ``changes/<PR#>.source_catalog.rst``
- ``changes/<PR#>.combine_1d.rst``
- ``changes/<PR#>.ami.rst``

## other
- ``changes/<PR#>.wfs_combine.rst``
- ``changes/<PR#>.white_light.rst``
- ``changes/<PR#>.cube_skymatch.rst``
- ``changes/<PR#>.engdb_tools.rst``
- ``changes/<PR#>.guider_cds.rst``
</details>

### CODE REVIEW

**Comment by emolter** [comment]
starting regression tests here: https://github.com/spacetelescope/RegressionTests/actions/runs/11976873413

**Comment by braingram** [comment]
Overall LGTM.

I think this means we can drop psutil as a dependency. Is there any other usage of that package?

**Comment by emolter** [comment]
> Overall LGTM.
> 
> I think this means we can drop psutil as a dependency. Is there any other usage of that package?

good catch, looks like no

**Review by braingram — APPROVED** [review]
LGTM. I reran your regtest run with the `psutil` dependency removal and all tests passed.

**Review by tapastro — APPROVED** [review]
LGTM

**Pull request merged**
