### PR TITLE
JP-3667: Add safeguards for NSClean on background/imprint members

### PR DESCRIPTION
**Pull request by melanieclarke**
Resolves [JP-3667](https://jira.stsci.edu/browse/JP-3667)

Follow up to #8786 to fix some unexpected interactions between badpix_selfcal and nsclean, causing a failure in the badpix_selfcal regression tests.  If badpix_selfcal is run, the background members are datamodels instead of filenames.

I also noticed in testing this that setting the output file for nsclean on the background/imprint members caused them to be saved by default, so I added a check for that as well.

## Tasks
- [x] **request a review from someone specific**, to avoid making the maintainers review every PR
- [x] add a build milestone, i.e. `Build 11.3` (use the [latest build](https://github.com/spacetelescope/jwst/milestones) if not sure)
- [ ] Does this PR change user-facing code / API?
  - [x] add an entry to `CHANGES.rst` within the relevant release section (otherwise add the `no-changelog-entry-needed` label to this PR)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [x] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [x] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by melanieclarke** [comment]
Regtests here:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1735/

**Review by emolter — APPROVED** [review]
LGTM pending regression tests showing no unexpected failures

**Review by hayescr — APPROVED** [review]
LGTM as well, sorry I missed this on the last one.

**Comment by melanieclarke** [comment]
Regression tests look good. I will merge when CI is complete.

**Pull request merged**
