### PR TITLE
re-add quick check for alternative engineering database test

### PR DESCRIPTION
**Pull request by braingram**
The test_environmental test when not run on the vpn will fail to contact the alternative engineering database server. This results in the test taking ~10 minutes waiting for a response before turning into a skip.

This commit adds some lines of code that were removed in PR #3022 which changed the skip from a decorator to a pytest.skip when the exception/timeout occurs. This should allow the test to skip quickly when the host is not accessable (and instead skips in <1 second). The pytest.skip call during the except block is left to deal with cases when the host resolves but the url fails to resolve.

As the alternative host appears unresponsive for github CI runs (which run tests in parallel with 2 workers) this should free up one of the workers that without this PR sits waiting for ~10 minutes. As a comparison, the python 3.9 tests for this recent PR took [~22 minutes](https://github.com/spacetelescope/jwst/actions/runs/5692683750/job/15430193293?pr=7772#step:10:16) whereas similar tests for this PR took [~16 minutes](https://github.com/spacetelescope/jwst/actions/runs/5695453779/job/15438646749?pr=7780#step:10:16).

Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)

Closes #

This PR addresses ...

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [x] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by braingram** [comment]
@stscieisenhamer as the author of #3022 do you foresee issues with reintroducing the decorator to skip this test when the host does not respond? If so, are there alternatives you might suggest for allowing this test to skip without waiting for the timeout. Perhaps skipping it for github CI runs (although this also impacts local runs when not on the vpn) or reducing the timeout?

**Comment by braingram** [comment]
Closing and reopening to retrigger docs.

**Comment by braingram** [comment]
Not sure why the docs are failing with:
```
Read the Docs build information
Build id: 21486088
Project: jwst-pipeline
Version: 7780
Commit: aad4c6f4321bf62c286d14fc9a199e8e374df3a4
Date: 2023-08-02T16:48:38.406583Z
State: finished
Success: False


[rtd-command-info] start-time: 2023-08-02T16:48:41.720584Z, end-time: 2023-08-02T16:48:44.742024Z, duration: 3, exit-code: 0
git clone --depth 1 https://github.com/spacetelescope/jwst .
Cloning into '.'...

[rtd-command-info] start-time: 2023-08-02T16:48:45.113008Z, end-time: 2023-08-02T16:48:46.048983Z, duration: 0, exit-code: 0
git fetch origin --force --prune --prune-tags --depth 50 pull/7780/head:external-7780
From https://github.com/spacetelescope/jwst
 * [new ref]         refs/pull/7780/head -> external-7780
 * [new tag]         1.11.0              -> 1.11.0

[rtd-command-info] start-time: 2023-08-02T16:48:46.264652Z, end-time: 2023-08-02T16:48:46.359021Z, duration: 0, exit-code: 128
git checkout --force aad4c6f4321bf62c286d14fc9a199e8e374df3a4
fatal: reference is not a tree: aad4c6f4321bf62c286d14fc9a199e8e374df3a4
```
@zacharyburnett Have you seen any error like this before?

**Comment by braingram** [comment]
The docs seem happy again. I'm going to chalk this up to readthedocs attempting to clone the repo before github was fully updated or something.

**Comment by braingram** [comment]
Regression tests passed with no failures.

Note that the modified test `test_environmental` passed during the regression test run in 3 seconds (so it did not time out and did not skip itself).

**Review by stscieisenhamer — APPROVED** [review]

**Comment by braingram** [comment]
Thanks! I rebased it to grab the most recent changes.

**Pull request merged**
