### PR TITLE
JP-1339: Update default SRCTYPE for NRS_IFU to EXTENDED

### LINKED ISSUE #4623: NIRSpec MOS sources with stellarity=-1 should be treated as POINT
Issue [JP-1330](https://jira.stsci.edu/browse/JP-1330) was created by Howard Bushouse:

The srctype step should be updated to treat NIRSpec MOS sources with stellarity = -1 as POINT type. Currently they are set to UNKNOWN.

### LINKED ISSUE #4652: Change default source_type for NIRSpec IFU to EXTENDED
Issue [JP-1339](https://jira.stsci.edu/browse/JP-1339) was created by Howard Bushouse:

As documented in the comments of JP-1269, the NIRSpec team (with the concurrence of the CalWG) requests that the default source type value (used in the absence of a type specified by the user in the APT) should be changed from POINT to EXTENDED (same as MIRI MRS). Need to update the srctype step accordingly and update the step docs.

### PR DESCRIPTION
**Pull request by hbushouse**
Update the `srctype` step to use a default value of EXTENDED for NIRSpec IFU exposures, same as MIRI MRS. Added a unit test and updated docs.

Fixes #4652 / [JP-1339](https://jira.stsci.edu/browse/JP-1339) 

Fixes #4623 / [JP-1330](https://jira.stsci.edu/browse/JP-1330)

### CODE REVIEW

**Comment by hbushouse** [comment]
Added updates to also address [JP-1330](https://jira.stsci.edu/browse/JP-1330), which updates the `srctype` and `extract_2d` steps to treat NIRSpec MOS slits with stellarity=-1 as POINT source, instead of UNKNOWN.

**Comment by hbushouse** [comment]
@nden are there any docs related to the NIRSpec wavecorr that happens in `extract_2d` that should be updated for this change? I didn't see anything with a quick search.

**Comment by nden** [comment]
@hbushouse There's a ticket to update the docs with how wavecorr works - `AL-190`. Should have been a `JP` ticket.

**Comment by hbushouse** [comment]
> @hbushouse There's a ticket to update the docs with how wavecorr works - `AL-190`. Should have been a `JP` ticket.

OK, I'll leave that one to you.

**Pull request merged**
