### PR TITLE
JP-1822: Update NRS fixed slit association rules for background eligibility

### LINKED ISSUE #5547: Update NRS FS background association rules per JWSTDMS-325
_Issue [JP-1822](https://jira.stsci.edu/browse/JP-1822) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The ASN generator rules for level 2b dedicated background ASN's need to be updated to accommodate the new requirements for NIRSpec Fixed-Slit observations, as described in JWSTDMS-325.

### PR DESCRIPTION
**Pull request by tapastro**
Closes #5547 

Resolves [JP-1822](https://jira.stsci.edu/browse/JP-1822)

**Description**

This PR addresses the usage of science exposures as backgrounds for other science exposures in an observation with fixed slit nods; this is accomplished by using the SPAT_NUM keyword to match exposures with different spatial nod positions for use as backgrounds in each other's associations.

NOTE: Waiting for an up-to-date pool file for testing before merge.

Checklist
- [ ] Tests
- [ ] Documentation
- [ ] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Review by stscieisenhamer — APPROVED** [review]
Obligatory "don't forget the changelog"

**Comment by tapastro** [comment]
> Obligatory "don't forget the changelog"

 I modified the jw00626 pool file to contain SPAT_NUM, and it runs successfully. However, the two unit tests with coverage of this edit are failing, so I think I may have a bit of maintenance to take care of first.

**Review by hbushouse — APPROVED** [review]
Updates to the actual ASN code look good. Of course unit tests need fixing now.

**Review by stscieisenhamer — APPROVED** [review]
obligatory "update changelog" but LGTM.

**Pull request merged**
