### PR TITLE
Rebase nrs deepcopy

### LINKED ISSUE #8338: Modify NIRSpec IFU WCS to improve runtime and usability
_Issue [JP-3564](https://jira.stsci.edu/browse/JP-3564) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

At present, it takes much longer to build NIRSpec IFU cubes than it does to build MIRI cubes.  For a typical single-exposure, cube this is about 9 seconds for an MRS cube and 45 seconds for a NIRSpec cube.  While NIRSpec has more pixels, the runtime is driven by the 36 seconds spent in the subroutine map_nirspec_pixel_to_sky compared to 1 second spent in the corresponding map_miri_pixel_to_sky routine.

At the same time, it is not possible to interact with the NIRSpec IFU WCS in the same manner as for other JWST instruments.  Typically,

model.meta.wcs.transform(‘detector’,’world’,x,y)

would give the world coordinates associated with any pixel.  For NIRSpec though, it’s necessary (both in cube building and anywhere else working with a cal.fits file) to call nirspec.nrs_wcs_set_input for each of the 30 slices in turn on all of the input xx,yy pixels, and save the meaningful results.  This is what cube building does in the map_nirspec_pixel_to_sky routine, querying the bounding box for each to figure out the affected pixels.

This loop is what’s slow; 75% or more of the map_nirspec_pixel_to_sky runtime seems to be spent just opening the relevant distortion model with nirspec.nrs_wcs_set_input for each of 30 slices rather than actually evaluating the model at any given location.

So, can we cut out the loop somehow, perhaps by changing the assign_wcs routine itself?  MIRI uses a regions reference file to assign each detector pixel to a given slice; this is read from a static reference file during assign_wcs, attached to the data, and used to map each pixel to the appropriate slice distortion model.  NIRSpec has no such static file, because the mapping from pixels to slices can change slightly from exposure to exposure, but it should be possible to generate one on the fly during the assign_wcs stage and save it for future use.

This would certainly address the general-purpose usability, though it’s unclear to me offhand whether it would necessarily improve runtime depending on whether it could speed up distortion loading time.

Thoughts?  [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison)

### PR DESCRIPTION
**Pull request by nden**
Resolves [JP-3564](https://jira.stsci.edu/browse/JP-3564)

Closes #8338

This PR is a copy of #8587 with minor changes to the names of functions. Below is a copy of the comment in the original comment by Tim Brandt.

This PR addresses the long run times of calwebb_spec2 for NIRSpec data, primarily in IFU mode, due to deep copying of WCS objects. These deep copies can take about 70% of the run time because they take place within loops over the pseudo-slits. This PR implements helper functions that copy then necessary bits of the WCS objects and then apply them to a single copy, reducing the number of deep copies of full WCS objects by about a factor of 30 in NIRSpec IFU mode. The runtime of calwebb_spec2 for NIRSpec IFU data decreases by almost a factor of 3.

## Tasks
- [ ] **request a review from someone specific**, to avoid making the maintainers review every PR
- [x] add a build milestone, i.e. `Build 11.3` (use the [latest build](https://github.com/spacetelescope/jwst/milestones) if not sure)
- [ ] Does this PR change user-facing code / API?
  - [x] add an entry to `CHANGES.rst` within the relevant release section (otherwise add the `no-changelog-entry-needed` label to this PR)
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by tapastro** [comment]
Regtest run started after the okify work was completed: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1727/

**Comment by nden** [comment]
@melanieclarke Yes, please point me to the nsclean code change and I'll include it here.

**Comment by melanieclarke** [comment]
The changes from Tim are these ones:
https://github.com/spacetelescope/jwst/pull/8587/files#diff-2f4a109d4d47eb6cd2e20de128cbce6fcba1bc6c255b765b8f4834bd1586476a

They should be ported in to the `mask_ifu_slices` and `mask_slits` functions in the clean_flicker_noise.py file, here, in your branch:
https://github.com/nden/jwst/blob/1826b7a954e955ecda66ba0deb33a67d700ce9a7/jwst/clean_flicker_noise/clean_flicker_noise.py#L143

I can't directly add a suggested change, but I can send a PR to your branch if that's not enough information.

**Comment by nden** [comment]
Thanks @melanieclarke. Made a commit with the changes.

**Comment by nden** [comment]
Failures in the latest run are unrelated.
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1730/

**Comment by nden** [comment]
Done

**Comment by tapastro** [comment]
Most recent regtests show matching failures to main, so I'm merging. Thanks! https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1736/

**Pull request merged**
