### PR TITLE
Write user provided x1d background expanded to 2d if save_background=True

### LINKED ISSUE #7715: Allow the user to save the expanded 2D master background when a user background is provided.
_Issue [JP-3303](https://jira.stsci.edu/browse/JP-3303) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

If a user provided a user master background and sets save_background=True then the expanded 2d master background for each file is written to disk. Before this was only allowed if the master background step determined the master background

### PR DESCRIPTION
**Pull request by jemorrison**
Resolves [JP-3303](https://jira.stsci.edu/browse/JP-3303)

Closes #7715

This PR addresses allows the user to print to disk the user provided x1d file that is expand to 2D for each file in the association. 

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by hbushouse** [comment]
Have you done a regression test run? Shouldn't have any effect, since we don't have any tests that exercise this new option, but can't hurt.

**Comment by jemorrison** [comment]
Running regression tests now: #787

**Comment by jemorrison** [comment]
@hbushouse I don't understand the regression tests ? Not sure where these differences are coming from. Maybe I need to git fetch and then git rebase - maybe I have old code  and I don't have the most recent stuff on master ?

**Comment by jemorrison** [comment]
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/787/

**Review by hbushouse — APPROVED** [review]

**Comment by hbushouse** [comment]
Another regtest run started at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/815

**Comment by hbushouse** [comment]
Finally got a complete and clean regtest run: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/819/

**Pull request merged**
