### PR TITLE
created 3rd party package bayesicfitting

### PR DESCRIPTION
**Pull request by jemorrison**
Closes #

Resolves JP-1273

**Description**
The 3rd party package BayesFitting used by the MIRI residual_fringe step has been packaged and put into jwst/extern/bayesicfitting.
The url for the original code is https://www.bayesicfitting.nl
This PR addresses the fitting used in residual_fringe step.

Checklist
- [ ] Tests

- [ ] Documentation

- [ ] Change log

- [ ] Milestone

- [ ] Label(s)

### CODE REVIEW

**Comment by jemorrison** [comment]
@jdavies-st  are the CI failures something I need to fix ?
Do I need to add this directory to another place in setup.cfg

**Comment by eslavich** [comment]
Adding an empty `__init)__.py` to the jwst/extern and jwst/extern/bayesicfitting directories will fix the ImportErrors.

**Comment by jemorrison** [comment]
@eslavich  Do you know what the CI/SDP dependencies fail means - can you see what I am missing ?

**Comment by eslavich** [comment]
I think it's running docstring tests in the new module?  I don't think we need to do that, those can be excluded in setup.cfg by adding `jwst/extern` here: https://github.com/spacetelescope/jwst/blob/master/setup.cfg#L121

Probably should also exclude that directory in the coverage config:

https://github.com/spacetelescope/jwst/blob/master/setup.cfg#L142

**Comment by eslavich** [comment]
Here too the doc build can be fixed by rebasing on master.

**Pull request closed without merging**
