### PR TITLE
TST: Remove custom CI skip

### PR DESCRIPTION
**Pull request by pllim**
See https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

### CODE REVIEW

**Comment by jdavies-st** [comment]
Whoa!  They listened to the users!

Now if they would just implement `allowed_failure`.  😅

**Comment by pllim** [comment]
Bad news is that currently the built-in CI skipping skips everything in `.github/workflow` but that isn't a problem for your current use case.

**Comment by jdavies-st** [comment]
Ah, so if you have a commit at HEAD that has `[ci skip]`, then it will skip the merged job on `master` plus any cron jobs?

**Comment by jdavies-st** [comment]
Btw, is there a reason to keep the `cancel_ci` job in this workflow?  Or can all of that be removed now?

**Comment by pllim** [comment]
Actually, I just merged the equivalent PR on `astropy` and it looks like the merge commit only has PR title, not the individual commit messages, so the merge ran the CI. I suspect cron would behave the same (I'll find out tomorrow). But if you have `[ci skip]` in the PR title, you deserve it (LoL).

Well, I have a fix in for cancelling at styfle/cancel-workflow-action#55 but it is just sitting there. You can choose to remove this altogether, keep it as is until my PR is merged (if ever), or use my forked branch; but I think that is out of scope here.

**Comment by jdavies-st** [comment]
I see.  Cool.  We'll just leave it here then.

I suspect you would run into the problem if you did "Rebase and merge" which would put that rebased commit with `[ci skip]` in the title at the HEAD of master.  So I see where this could be a problem.  We had the same problem back when we had our own Jenkins per-PR CI.  Nothing changes.

**Review by jdavies-st — APPROVED** [review]
Looks good.  Thanks!

**Comment by pllim** [comment]
Yeah... at this point, the rule is server side now and out of our control. The only thing we can do is workaround it.

**Pull request merged**
