### PR TITLE
New firstframe unit test added

### PR DESCRIPTION
**Pull request by cracraft**
Updated firstframe test to see if full step properly skips NIR data and runs MIR data to get 100% code coverage.

### CODE REVIEW

**Comment by cracraft** [comment]
An extra copy of the lastframe step was attached to this request, and that is already covered in the pull request for the lastframe step. It can be ignored/deleted here.

**Comment by jdavies-st** [comment]
Thanks for this PR @cracraft.  If you can remove the lastframe test from this PR, that would be great.  You'll want to make sure it tracks `jwst/master`, so something like:
```
git fetch upstream
git branch newfirstframe -u upstream/master
```
if `upstream` is the pointer to this repository.  `git diff` will then show the differences between your branch and `jwst/master`.

You'll also want to rebase the branch to get rid of the 133abca commit.

One trick for making sure that you always branch from `jwst/master` is when you checkout a new branch, do the following:
```
git fetch upstream
git checkout -b my_new_branch upstream/master
```
If you leave off that last `upstream/master`, your new branch will be a branch from whatever existing branch you happen to have checked out, which in this case was probably your `lastframe` branch.

Anyway, finally when you're all done, you can `git push -f origin` to push it to your fork on Github, and that will automatically update this PR.

Ping me on slack if you need some help.

**Comment by cracraft** [comment]
Can we re-run the jenkins/travis tests and get this merged in?

**Comment by jdavies-st** [comment]
Closing and reopening to kick off the tests again.

**Comment by jdavies-st** [comment]
Jenkins CI test failure is unrelated and known.  Travis CI passes.  Merging.

**Pull request merged**
