### PR TITLE
Fix suffix list test for new nsclean step

### PR DESCRIPTION
**Pull request by hbushouse**
This PR fixes a failing unit test, due to the recent addition of the new "nsclean" step.

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by hbushouse** [comment]
Latest commit also fixes codestyle failures and updates the README for the B10.0.1 installation in Ops yesterday.

**Comment by tapastro** [comment]
> > Do we know why the nsclean PR didn't catch this?
> > LGTM
> 
> Which problem: the unit test or the codestyle? The codestyle error showed up in the original PR and I just ignored it. Don't recall seeing the unit test failure.

I meant the unit test - I went back and looked at the PR and the unit tests passed then. Seems strange.

**Comment by hbushouse** [comment]
> > > Do we know why the nsclean PR didn't catch this?
> > > LGTM
> > 
> > 
> > Which problem: the unit test or the codestyle? The codestyle error showed up in the original PR and I just ignored it. Don't recall seeing the unit test failure.
> 
> I meant the unit test - I went back and looked at the PR and the unit tests passed then. Seems strange.

It's one of those little mysteries of life.

**Comment by braingram** [comment]
Looks like I was too slow :)

LGTM. Thanks for the request for a review as a good excuse to look at the suffix code. It looks pretty straightforward to add a new one.

**Comment by hbushouse** [comment]
> LGTM. Thanks for the request for a review as a good excuse to look at the suffix code. It looks pretty straightforward to add a new one.

Well, it may *look* that way on the surface, but it's always taken me a couple of tries to get it right.

**Comment by jdavies-st** [comment]
It would be really good to make the suffix replacement code more flexible.  Either a registry, or dynamic based on registered steps in the `stpipe` entry_points.  Currently, if I add a new step, register it via entry points, and specify a `class_alias` and `suffix`, it's suffixes are still not replaced properly, and there's no way as a user to fix this except for explicit string replacement.

Also, having `_nsclean` and `_nscleanstep` be default suffixes for the same step, and the path through `stpipe` being the only thing that triggers one vs the other, is not great.  Better for most steps to have a defined, default suffix.  And in fact, for that defined, default stuffix to be the same as `class_alias` for the step or pipeline.  This won't be possible for all steps and pipelines due to historic usage, but it will be possible be for most, and certainly for new steps.

Also, it would be really good to standardize that the `step_defs` dict in pipelines have keys that are the same as `class_alias` for each step, for consistency.

I'll file a separate issue on this.

**Pull request merged**
