### PR TITLE
JP-629: Adding msaflagopen unit tests

### LINKED ISSUE #3343: MSA flag open pipeline step needs unit-testing
Issue [JP-629](https://jira.stsci.edu/browse/JP-629) was created by Macarena Garcia Marin:

The MSA flag open step in the JWST calibration pipeline does currently not have any test in the GitHub repository. To ensure the robustness of the pipeline and have a lower level of risk, the pipeline testing focus group is requesting unit tests to be included and routinely executed. Verifying individual code components will make easier the process of validating the pipeline. The requested code-coverage is 90%.

### PR DESCRIPTION
**Pull request by mfixstsci**
Adding unit tests for `msaflagopen` pipeline step.

Fixes #3343

### CODE REVIEW

**Comment by mfixstsci** [comment]
If anyone has suggestions on how to point to files without having specify the explicit paths, that would be great!

**Comment by jdavies-st** [comment]
`__file__` can help you.  See how it is done here:

https://github.com/spacetelescope/jwst/blob/fe85e1da6e5bb7eb606ec3f5dac612ad5e32135d/jwst/assign_wcs/tests/test_nirspec.py#L287

**Comment by mfixstsci** [comment]
All of the Travis tests are passing, this is ready for review.

**Comment by hbushouse** [comment]
Fixes #3343

**Comment by mfixstsci** [comment]
Hey @jdavies-st, I just removed the data files and I updated the tests.

**Comment by jdavies-st** [comment]
Looks good.  Just fix the whitespace issues

https://travis-ci.org/spacetelescope/jwst/jobs/593543013#L453-L454

and it should be ready to merge.  Thanks!

**Comment by mfixstsci** [comment]
@jdavies-st fixed the flake8 issue, should be good to go!

**Pull request merged**
