### PR TITLE
JP-2012: Add aliases for each step

### LINKED ISSUE #5910: Add aliases to all steps
_Issue [JP-2012](https://jira.stsci.edu/browse/JP-2012) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Currently, alias entry-points are defined for all pipeline classes, so that the alias can be used with `strun`. Do this also for all steps.

Consider creating a utility to create the entry-point list from the code, similar to how the suffix list is created.

### PR DESCRIPTION
**Pull request by tapastro**
Closes #5910 
Resolves [JP-2012](https://jira.stsci.edu/browse/JP-2012)

**Description**

This PR attempts to add back the aliases that were proposed in #6158 and #6321 - their addition is contingent on an update to CRDS ([CRDS-535](https://jira.stsci.edu/browse/CRDS-535)).

Checklist
- [ ] Tests
- [x] Documentation
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Review by hbushouse — COMMENTED** [review]
Looks good to me! Does any of it work?  ;-)

**Comment by hbushouse** [comment]
Of course I can't give my approval until there's a change log entry and documentation.

**Review by stscieisenhamer — COMMENTED** [review]
Code changes look good.

However, are there any tests of the alias infrastructure?

**Comment by tapastro** [comment]
> Code changes look good.
> 
> However, are there any tests of the alias infrastructure?

I believe this test covers step alias usage: https://github.com/spacetelescope/jwst/blob/36f30e9a4cea72967953348a775e4c2c09468a49/jwst/stpipe/tests/test_step.py#L384-L397

**Review by stscieisenhamer — APPROVED** [review]

**Review by hbushouse — APPROVED** [review]
@stscieisenhamer has verified that this PR produces a clean regression run using the contents of the CRDS test server. Hereby approving for merger.

**Pull request merged**
