### PR TITLE
fix standard error of the mean

### PR DESCRIPTION
**Pull request by benjaminpope**
This PR addresses a bug in the fork of ImPlaneIA that constitutes calwebb_ami3. 

## Tasks
- [ ] Review: 
- [ ] add a build milestone, i.e. `Build 11.3` (use the [latest build](https://github.com/spacetelescope/jwst/milestones) if not sure)
- [ ] Does this PR change user-facing code / API? (if not, label with `no-changelog-entry-needed`)
  - [x] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types) 
  - [ ] update or add relevant tests
  - [ ] update relevant docstrings and / or `docs/` page
  - [ ] [start a regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) and include a link to the running job ([click here for instructions](https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
    - [ ] Do truth files need to be updated ("okified")?
      - [ ] **after the reviewer has approved these changes**, run `okify_regtests` to update the truth files
- [ ] if a JIRA ticket exists, [make sure it is resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

<details><summary>news fragment change types...</summary>

    - ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
    - ``changes/<PR#>.docs.rst``
    - ``changes/<PR#>.stpipe.rst``
    - ``changes/<PR#>.datamodels.rst``
    - ``changes/<PR#>.scripts.rst``
    - ``changes/<PR#>.fits_generator.rst``
    - ``changes/<PR#>.set_telescope_pointing.rst``

    ## stage 1
    - ``changes/<PR#>.group_scale.rst``
    - ``changes/<PR#>.dq_init.rst``
    - ``changes/<PR#>.emicorr.rst``
    - ``changes/<PR#>.saturation.rst``
    - ``changes/<PR#>.ipc.rst``
    - ``changes/<PR#>.firstframe.rst``
    - ``changes/<PR#>.lastframe.rst``
    - ``changes/<PR#>.reset.rst``
    - ``changes/<PR#>.superbias.rst``
    - ``changes/<PR#>.refpix.rst``
    - ``changes/<PR#>.linearity.rst``
    - ``changes/<PR#>.rscd.rst``
    - ``changes/<PR#>.persistence.rst``
    - ``changes/<PR#>.dark_current.rst``
    - ``changes/<PR#>.charge_migration.rst``
    - ``changes/<PR#>.jump.rst``
    - ``changes/<PR#>.ramp_fitting.rst``
    - ``changes/<PR#>.gain_scale.rst``

    ## stage 2
    - ``changes/<PR#>.assign_wcs.rst``
    - ``changes/<PR#>.msaflagopen.rst``
    - ``changes/<PR#>.nsclean.rst``
    - ``changes/<PR#>.imprint.rst``
    - ``changes/<PR#>.background.rst``
    - ``changes/<PR#>.extract_2d.rst``
    - ``changes/<PR#>.master_background.rst``
    - ``changes/<PR#>.wavecorr.rst``
    - ``changes/<PR#>.srctype.rst``
    - ``changes/<PR#>.straylight.rst``
    - ``changes/<PR#>.wfss_contam.rst``
    - ``changes/<PR#>.flatfield.rst``
    - ``changes/<PR#>.fringe.rst``
    - ``changes/<PR#>.pathloss.rst``
    - ``changes/<PR#>.barshadow.rst``
    - ``changes/<PR#>.photom.rst``
    - ``changes/<PR#>.pixel_replace.rst``
    - ``changes/<PR#>.resample_spec.rst``
    - ``changes/<PR#>.residual_fringe.rst``
    - ``changes/<PR#>.cube_build.rst``
    - ``changes/<PR#>.extract_1d.rst``
    - ``changes/<PR#>.resample.rst``

    ## stage 3
    - ``changes/<PR#>.assign_mtwcs.rst``
    - ``changes/<PR#>.mrs_imatch.rst``
    - ``changes/<PR#>.tweakreg.rst``
    - ``changes/<PR#>.skymatch.rst``
    - ``changes/<PR#>.exp_to_source.rst``
    - ``changes/<PR#>.outlier_detection.rst``
    - ``changes/<PR#>.tso_photometry.rst``
    - ``changes/<PR#>.stack_refs.rst``
    - ``changes/<PR#>.align_refs.rst``
    - ``changes/<PR#>.klip.rst``
    - ``changes/<PR#>.spectral_leak.rst``
    - ``changes/<PR#>.source_catalog.rst``
    - ``changes/<PR#>.combine_1d.rst``
    - ``changes/<PR#>.ami.rst``

    ## other
    - ``changes/<PR#>.wfs_combine.rst``
    - ``changes/<PR#>.white_light.rst``
    - ``changes/<PR#>.cube_skymatch.rst``
    - ``changes/<PR#>.engdb_tools.rst``
    - ``changes/<PR#>.guider_cds.rst``
</details>

### CODE REVIEW

**Comment by benjaminpope** [comment]
Re tests - there is not a current unit test for `oifits.py`. Testing this would require making a test dataset available in the repo. Do let me know your preferred course of action.

**Review by anand0xff — COMMENTED** [review]
I'm good with sigma-clipped means... rcooper@stsci.edu should be an owner perhaps, maybe instead of me?
Stats are being changed to use the standard error of the mean (by rcooper@).

**Comment by anand0xff** [comment]
Re test outfits files - we have to resolve how we write in covariances of cvs,  triple products, and the closure quads (all complex or  2d observable) into outfits files.  The standard is vaguely defined (or I don't understand it)

**Comment by benjaminpope** [comment]
Do you need anything on the tests in this PR / from me? I've tested the updated uncertainties locally and they work fine, but best practice would have this be a full unit test.

**Comment by rcooper295** [comment]
Hi Ben, thanks for putting this in! We have gone back and forth on using the standard error of the mean vs. standard deviation a few times and at some point settled on taking the (sigma-clipped) median & standard deviation over the integrations, but I'm in the midst of updating the code to calculate covariances for various observables for each [baseline/triangle/quad] and use those for the error bars. You can see those changes [here](https://github.com/rcooper295/jwst/tree/observable_update), though I'm still getting everything working. I can certainly change the default to use the mean rather than median if that's the consensus but I'm not sure if I should still be dividing those by sqrt(n_integrations)?

**Comment by benjaminpope** [comment]
Hi Rachel,

If we're distilling a whole bunch of integrations to a single mean and uncertainty, the right mean to choose is the SEM (ie 1/sqrt(N) not the standard deviation. This closely matches eg AMICAL.

**Comment by rcooper295** [comment]
Thanks Ben, I've updated the code to default to take the mean rather than median, and to take the SEM rather than just sqrt([co]variance). Hopefully this will address the issues raised here. Draft PR is here: https://github.com/spacetelescope/jwst/pull/8846

**Pull request closed without merging**
