### PR TITLE
JP-3702: Fix filenames for level3 NIRSpec

### LINKED ISSUE #8688: NIRSpec TSO filenames may be missing the slitname
_Issue [JP-3702](https://jira.stsci.edu/browse/JP-3702) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

DMS Ops reported a data product has had its filename change:

<https://stsci.slack.com/archives/C9KF4MVEV/p1722348421168879>
```
I just noticed an issue where a JWST observation that had been included in a DOI was no longer available in the MAST portal. The original observation was:
jw02512-o008_t007_nirspec_f290lp-g395h-s1600a1-sub2048
and the observation that I think is equivalent is:
jw02512-o008_t007_nirspec_f290lp-g395h-sub2048
```

It looks like work completed for JP-3233 may have altered behavior for NIRSpec TSO data - it was not given the new product name generation, and the change to _get_opt_element removed the slit name from the concatenated list of elements. 

Work should include new test coverage of NIRSpec BOTS - this should have been caught by regressions.

### PR DESCRIPTION
**Pull request by melanieclarke**
Resolves [JP-3702](https://jira.stsci.edu/browse/JP-3702)

Closes #8688

Restore slit names to level 3 filenames for NIRSpec products that do not get planned as fixed slit reductions.  This primarily impacts BOTS mode, which has a FXD_SLIT defined, but does not get planned for spec3 with Asn_Lv3NRSFSS rules: these data are planned for tso3 with Asn_Lv3TSO rules.  It also impacts background targets for fixed slit, planned with Asn_Lv3SpecAux rules.

In JP-3233 (#7879), association rules were changed for fixed slits to allow S200A1 and S200A2 targets to be reduced together in spec3.  Part of this change removed a check for fixed slit as one of the 'opt_elem' fields in the filename.  This had the unintended effect of removing the fixed slit from the name for BOTS and auxiliary NIRSpec data.

The fix here is to restore the check for FXD_SLIT in all level3 product names that might apply to NIRSpec data and add the value to the filename if present.

It looks like this regression was reported in the regression tests for JP-3233, e.g. the last entry in this report:
[test_against_standard_pool_010_spec_nirspec_lv2bkg](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/915/testReport/jwst.regtest/test_associations_standards/_stable_deps__test_against_standard_pool_010_spec_nirspec_lv2bkg_/), but it was buried in some other expected changes.  There were also some unit tests for level3 product names, but they were not specific enough to catch this regression.

I have updated the unit tests (test_level3_product_names.py) to catch this case specifically, and verified that it fails on master and passes with this PR branch.  I think the regression tests should be sufficient as is.

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [x] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by melanieclarke** [comment]
Regression tests here:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1641/

**Comment by melanieclarke** [comment]
Regression tests look correct.  Only NIRSpec associations are affected, and the only change in each case is that the product name now contains the slit, in between the grating and the subarray (if present).

**Review by tapastro — CHANGES_REQUESTED** [review]
It looks like the pool 010 regression test has a duplicated slitname entry in the product name. Other than that, this looks good to me.

**Comment by melanieclarke** [comment]
> It looks like the pool 010 regression test has a duplicated slitname entry in the product name. Other than that, this looks good to me.

I saw that too -- it's actually just because of some weird input data in the synthetic pools.  The slit and subarray are set to the same value, and it is appropriately listing them both.

**Pull request merged**
