### PR TITLE
AL-479: Move ramp fit code from JWST to STCAL. 

### PR DESCRIPTION
**Pull request by kmacdonald-stsci**
Resolves [AL-479](https://jira.stsci.edu/browse/AL-479)

**Description**

Moved ramp fitting code from JWST to STCAL.  All unit tests and regression tests are passing, using ramp fitting path to STCAL.

Checklist
- [x] Tests
- [ ] Documentation
- [x] Change log
- [x] Milestone
- [x] Label(s)

### CODE REVIEW

**Review by jdavies-st — COMMENTED** [review]
Looks good.  Regression tests on this branch and the one on `stcal` look good:

https://plwishmaster.stsci.edu:8081/job/RT/job/jdavies-dev/241/

This PR depends on https://github.com/spacetelescope/stcal/pull/6 being merged and a release of `stcal` happening.  This PR should then be updated to specify that version or greater of `stcal` in `setup.cfg`.  Then it can be merged.

🚀

**Comment by nden** [comment]
spacetelescope/stcal#6 was merged and I pointed this branch to stcal/main. Once tests pass we need an stcal release and can merge this one.

**Review by nden — APPROVED** [review]
lgtm

**Comment by nden** [comment]
stcal 0.2.0 was released on PyPi

**Review by hbushouse — APPROVED** [review]
So the various JWST instrument-specific hooks for special handling of a few things like MIRI first and last frames, etc. are now all in the supposedly "common" code over in stcal?

**Comment by nden** [comment]
They are because the common code works on data models.

**Comment by kmacdonald-stsci** [comment]
I am happy to remove it from STCAL and put it into JWST.  Are there other parts of the ramp fit code that are JWST specific that should be removed from the ramp fitting code in STCAL?

**Comment by nden** [comment]
This now points to the stcal release and can be merged.

**Comment by hbushouse** [comment]
> I am happy to remove it from STCAL and put it into JWST. There is only one specific MIRI reference in the STCAL code, so moving it should be easy.
> 
> Are there other parts of the ramp fit code that are JWST specific that should be removed from the ramp fitting code in STCAL?

No need to unmove any of the code. I was just curious. I guess the assumption is that Roman will use the same `RampModel` and `ImageModel` models?

**Comment by kmacdonald-stsci** [comment]
The assumption is that both pipelines will only use a JWST-like input RampModel containing expected values and kewords.  The `model` input variable to `ramp_fit` is the only variable that depends is a data model.  I've removed usage of data models everywhere else in the code.  All returned values from the ramp fitting code in STCAL returns tuples of computed arrays the pipeline step code is then responsible for putting into their respective data models, like an ImageModel.

**Comment by dmggh** [comment]
I think that this may have already been discussed, but as this is a change in the design and code structure (and the first of these changes among several calibration steps) this should be described in the docs for ramp fitting. The restructuring to use common code should probably also be described in other, more general sections of the docs.

**Comment by nden** [comment]
@dmggh good point and agreed!

**Pull request merged**
