### PR TITLE
JP-3494: write tweakreg source catalogs into user-specified output_dir 

### LINKED ISSUE #8144: Put output gaia catalog in specified directory
_Issue [JP-3494](https://jira.stsci.edu/browse/JP-3494) was created on JIRA by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft):_

When running the pipeline in a notebook in one directory, pointing to data in another directory, the tweakreg step puts the output gaia (or other source) catalog in the directory where the notebook is run, not the directory where the data is running. Specifying the output_dir as part of the tweakreg step should tell the pipeline to put all output into that directory. This ticket is to ask for an update in the pipeline code to have the abs_refcat code check the output_dir path and send output to that specified directory. This prevents the full run of a notebook due to the need to manually move the file from one location to another before it can be finished.

### PR DESCRIPTION
**Pull request by emolter**
Resolves [JP-3494](https://jira.stsci.edu/browse/JP-3494)

Closes #8144

This PR addresses an issue where the `output_dir` parameter was not respected when writing source catalogs in the `tweakreg` step.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by emolter** [comment]
started regression tests [here](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1356/)

**Review by hbushouse — COMMENTED** [review]
Code updates look good to me. Just holding final approval until there's a more recent regtest run to look at.

**Comment by emolter** [comment]
new regtest run [started here](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1365/)

**Comment by hbushouse** [comment]
Failures in latest regtest run are all benign and unrelated to this PR.

**Review by hbushouse — APPROVED** [review]

**Pull request merged**
