### PR TITLE
JP-3228: Remove 'grow' param from outlier_detection

### LINKED ISSUE #8062: Remove unused "grow" parameter from outlier_detection step definition
_Issue [JP-3228](https://jira.stsci.edu/browse/JP-3228) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

Back in #5822 the use of the "grow" parameter was removed from the outlier_detection step, yet the parameter itself is still defined for the step and appears in the step docs. The code and docs need to be updated to remove the "grow" param (and any others that may have been rendered obsolete by that PR).

### PR DESCRIPTION
**Pull request by hbushouse**
Resolves [JP-3228](https://jira.stsci.edu/browse/JP-3228)

Closes #8062 

This PR does the final work for JP-3228 by removing the "grow" param from the "spec" block of the outlier_detection step module, since it's now been removed in the latest MIRI parameter reference files delivered to CRDS. Note, however, that as of this writing, the updated pars files have only been delivered to CRDS-Ops. So this leaves us in a bit of quandary regarding execution of code on the jwst/master branch. CRDS-TEST is the only place where "emicorr" is defined and CRDS-OPS is the only place that has the updated ref files to get rid of "grow". So you can only run Stage 1 pipelines/steps using CRDS-TEST and you can only run Stage 3 pipelines/steps using CRDS-OPS. Sigh. 

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by hbushouse** [comment]
Started a regtest run at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1144

**Comment by hbushouse** [comment]
Regression test results are clean.

**Comment by braingram** [comment]
The changes look good to me. Is CRDS-TEST currently still in need of an update? I'm not seeing any miri ` pars-outlierdetectionstep` files with a `grow` parameter but perhaps I am looking at the wrong files? If I'm looking in the wrong place, what files on CRDS are in need of an update?

**Review by braingram — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
