### PR TITLE
JP-3500 Create WFSS Pure-Parallel associations

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves [JP-3500](https://jira.stsci.edu/browse/JP-3500)

This PR addresses the issue that WFSS pure parallel observations are enabled but not handled by the current association rules. The major issue was that parallel observations have no target to constrain by. For WFSS pure parallel, this is rectified on the APT-side by creating a new association candidate type, DIRECT-IMAGE. All the necessary components of the WFSS data are now encapsulated within this candidate. The new rule Asn_Lv2WFSSParallel handles this candidate. Since target id is an integral part of the Stage 3 filenames, a default of "t000" has been chosen as the default value,

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [x] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
[Regression try 1](https://plwishmaster.stsci.edu:8081/job/RT/job/eisenhamer-dev/377/)

**Review by hbushouse — APPROVED** [review]
Code looks great, all types of tests pass, and it's easy to dance to. I give it a 93.

**Comment by hbushouse** [comment]
Just curious, do we know if the updates to APT to create "direct image" candidates is also in place and ready to go?

**Comment by stscieisenhamer** [comment]
About APT: All the related issues are closed, many in the 2023 versions. Also, at some meeting it was explicitly stated that it is in the wild already, but I do not know exactly which version.

**Pull request merged**
