### PR TITLE
Implement source naming for NIRISS WFSS Level3 associations

### LINKED ISSUE #2438: NIS_WFSS not using source_id in Level3 product name
# Issue
`Asn_WFSS_NIS` not using the source product naming in the Level3 product

# Resources
- Example is the SDP test proposal jw87800

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Resolves #2438

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
@jhunkeler Just alerting to the Jenkins build issue.

**Comment by rendinam** [comment]
Conda dropped the ball, somehow. A re-run of the job was successful.

**Comment by stscieisenhamer** [comment]
Matt,


Thanks!


I think I asked this before: Is there a way for us lowly users to be able to restart Jenkins jobs? If not, will there be?


jde


________________________________

**Comment by rendinam** [comment]
That's a reasonable request. Restarting jobs currently requires an account on the Jenkins instance hosting the CI builds. As this is not sustainable for the collection of users of the CI system, a different authentication model is required. One such model exists, but it still needs to be configured and tested thoroughly before we know if it is appropriate. We will explore this as time allows.

**Comment by stscicrawford** [comment]
@stscieisenhamer This needs a change log entry and it would be good to add a unit test (or open an issue) for `dms_product_name_sources`

**Comment by stscieisenhamer** [comment]
@hbushouse The diff skipped the class name, but the addition was to the `Asn_WFSS_NIS` rule also. [See the whole class](https://github.com/spacetelescope/jwst/blob/57a96c6cf5a485046b558a354d8b9c8afb8db0e9/jwst/associations/lib/rules_level3.py#L408).

**Comment by hbushouse** [comment]
OK, so now I see the new `Asn_WFSS_NIS` rule, which immediately begs the question: Is there a corresponding `Asn_WFSS_NRC` rule for the NIRCam WFSS mode?

**Comment by stscieisenhamer** [comment]
See #655.

**Pull request merged**
