### PR TITLE
Expose tweakreg_catalog params in tweakreg

### LINKED ISSUE #6995: TweakReg: More catalog parameters should be exposed
The make_tweakreg_catalog part in TweakReg has parameters that currently aren't exposed (e.g. roundness limits, background median box size). I've noticed for some cases that having the background box size too large in images full of extended emission will end up with a very low number detected sources, so it would be useful to have these exposed to the user

### PR DESCRIPTION
**Pull request by thomaswilliamsastro**
Closes #6995 

This PR exposes the tweakreg_catalog parameters in the tweakreg step. Particularly for observations with extended emission, adjusting something like the bkg_boxsize can be useful to detect sources

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [x] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, link: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/403/
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by thomaswilliamsastro** [comment]
As a non-STSci person, it seems like I can't run the regression tests. I think this is everything I can do on my end

**Comment by mcara** [comment]
Please rebase to resolve conflicts. Thanks!

**Comment by thomaswilliamsastro** [comment]
@mcara Done!

**Comment by mcara** [comment]
This PR looks good to me but let's wait for all tests (unit and regression) to run.

**Comment by mcara** [comment]
There are two failures in tests related to alignment to gaia. I do not see how this PR might cause those failures (some differences in world coordinates computed with the tweaked WCS). Could these failures be related to https://github.com/spacetelescope/jwst/pull/6987?

CC: @mairanteodoro @stsci-hack

**Comment by thomaswilliamsastro** [comment]
@mcara I suspect this is right -- the defaults to match to Gaia are not the same as the defaults to match between tiles in that PR. I took the tweakreg_catalog defaults so this PR shouldn't change any tests

**Review by mcara — APPROVED** [review]
LGTM! Thanks!

**Comment by thomaswilliamsastro** [comment]
I'm not authorised to merge... @mcara / @hbushouse?

**Review by hbushouse — APPROVED** [review]

**Pull request merged**
