### PR TITLE
RampFitStep - accept integer values for `maximum_cores`

### PR DESCRIPTION
**Pull request by izkgao**
This PR allows `maximum_cores` of `RampFitStep` to accept integer values for the number of cores to be used in multiprocessing. Documentation updates follow the changes in #7871.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [x] updated relevant documentation
- [ ] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by kmacdonald-stsci — APPROVED** [review]

**Comment by hbushouse** [comment]
@mwregan2 What are your thoughts on this suggested update?  If it's OK for ramp_fit, we should probably make the same change to jump too.

**Comment by izkgao** [comment]
@hbushouse The same change has been done to jump by #7871.

**Comment by mwregan2** [comment]
> @mwregan2 What are your thoughts on this suggested update? If it's OK for ramp_fit, we should probably make the same change to jump too.

I am confused with this. We seem to have lost the change that I put in for ramp fit at the same time I did it for jump.

**Comment by mwregan2** [comment]
Well, I did make JWST changes but they seem to have been lost. I probably was at fault.

**Comment by hbushouse** [comment]
Given that this change was intended to be implemented before (but apparently got lost) and appears to be exactly the same updates made to the jump step to enable the use integer values for the number of cores, I think this all seems very reasonable and we should adopt it. I've started a regression test run against this PR branch at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1113 to make sure it's all working OK.

**Comment by hbushouse** [comment]
Regression test differences are all unrelated (related to MIRI emicorr).

**Pull request merged**
