### PR TITLE
JP-3268: Fix pixel_replace step status error

### PR DESCRIPTION
**Pull request by hbushouse**
Resolves [JP-3268](https://jira.stsci.edu/browse/JP-3268)

This PR fixes the `pixel_replace` step code so that it properly updates the step status keyword on completion. Previously a data model object was being updated that was not the model returned from the step, so the update was lost.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by hbushouse** [comment]
regtest started at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/761

**Review by nden — APPROVED** [review]
lgtm

**Comment by tapastro** [comment]
🙈

**Comment by hbushouse** [comment]
regtest run intentionally used CRDS_TEST, which contains an updated pars-spec2pipeline ref file for MIRI LRS that turns on the pixel_replace step. The LRS tests show that the S_PXREPL keyword is now present and populated. All other failures are due to the differences in ref files in CRDS_TEST vs. CRDS_OPS (which is what the truth files are based on). So this looks good.

**Pull request merged**
