### PR TITLE
replace usages of `np.int()` with `int()`

### PR DESCRIPTION
**Pull request by zacharyburnett**
This PR addresses Numpy deprecations in `numpy>=1.24.0`

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by hbushouse** [comment]
Is there more to be done with this or can it be converted from draft and made ready for review?

**Comment by zacharyburnett** [comment]
> Is there more to be done with this or can it be converted from draft and made ready for review?

I think this is pretty much ready, I'll undraft it

**Comment by hbushouse** [comment]
Started a regtest run at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/508

**Comment by hbushouse** [comment]
The regtest run (linked in previous comment) shows what look like asdf-related errors in one test module. Any clues?

**Review by stscieisenhamer — COMMENTED** [review]
Code changes LGTM. Reserving judgement until the regression issue is resolved.

**Comment by hbushouse** [comment]
I've started another regtest run at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/513/ just to see if the previous failures were a fluke.

**Comment by hbushouse** [comment]
Sigh. Regtest run https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/513/ failed with the same 4 errors as the previous attempt, so it does not appear to be a fluke. I'm going to try running that regtest module locally, first without these np.int -> int changes in the extract_1d code and then with those changes, and see what happens. I just want to make sure the failures aren't related to some other change in 3rd-party pkg versions or something.

**Comment by zacharyburnett** [comment]
<details>
  <summary>error example in regtest</summary>
  ```
______________ ERROR at setup of test_niriss_soss_extras[calints] ______________
[gw16] linux -- Python 3.9.15 /data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/bin/python

jail = local('/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/clone/test_outputs/popen-gw16/test_niriss_soss_rtdata_module0')
rtdata_module = {'input': '/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/clone/test_outputs/popen-gw16/test_niriss_soss_...mote': 'jwst-pipeline/dev/truth/test_niriss_soss_stages/jw01091-o002_t001_niriss_clear-gr700xd-substrip256_whtlt.ecsv'}

    @pytest.fixture(scope="module")
    def run_atoca_extras(jail, rtdata_module):
        """Run stage 2 pipeline on NIRISS SOSS data using enhanced modes via parameter settings."""
        rtdata = rtdata_module
    
        # Run spec2 pipeline on the second _rateints file, using wavegrid generated from first segment.
        rtdata.get_data("niriss/soss/seg001_wavegrid.fits")
        rtdata.get_data("niriss/soss/atoca_extras_rateints.fits")
        args = ["calwebb_spec2", rtdata.input,
                "--steps.extract_1d.soss_modelname=atoca_extras",
                "--steps.extract_1d.soss_wave_grid_in=seg001_wavegrid.fits",
                "--steps.extract_1d.soss_bad_pix=model",
                "--steps.extract_1d.soss_rtol=1.e-3",
                ]
>       Step.from_cmdline(args)

/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/clone/jwst/regtest/test_niriss_soss.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/stpipe/step.py:179: in from_cmdline
    return cmdline.step_from_cmdline(args)
/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/stpipe/cmdline.py:343: in step_from_cmdline
    step.run(*positional)
/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/stpipe/step.py:443: in run
    step_result = self.process(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <jwst.pipeline.calwebb_spec2.Spec2Pipeline object at 0x7f243fffe100>
data = '/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/clone/test_outputs/popen-gw16/test_niriss_soss_rtdata_module0/atoca_extras_rateints.fits'

    def process(self, data):
        """Entrypoint for this pipeline
    
        Parameters
        ----------
        input: str, Level2 Association, or ~jwst.datamodels.DataModel
            The exposure or association of exposures to process
        """
        self.log.info('Starting calwebb_spec2 ...')
    
        # Setup step parameters required by the pipeline.
        self.resample_spec.save_results = self.save_results
        self.resample_spec.suffix = 's2d'
        self.cube_build.output_type = 'multi'
        self.cube_build.save_results = False
        self.cube_build.skip_dqflagging = True
        self.extract_1d.save_results = self.save_results
    
        # Retrieve the input(s)
        asn = self.load_as_level2_asn(data)
    
        # Each exposure is a product in the association.
        # Process each exposure.  Delay reporting failures until the end.
        results = []
        failures = []
        for product in asn['products']:
            self.log.info('Processing product {}'.format(product['name']))
            self.output_file = product['name']
            try:
                getattr(asn, 'filename')
            except AttributeError:
                asn.filename = "singleton"
            try:
                result = self.process_exposure_product(
                    product,
                    asn['asn_pool'],
                    asn.filename
                )
            except NoDataOnDetectorError as exception:
                # This error merits a special return
                # status if run from the command line.
                # Bump it up now.
                raise exception
            except Exception:
                traceback.print_exc()
                failures.append(traceback.format_exc())
            else:
                if result is not None:
                    results.append(result)
    
        if len(failures) > 0 and self.fail_on_exception:
>           raise RuntimeError('\n'.join(failures))
E           RuntimeError: Traceback (most recent call last):
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/clone/jwst/pipeline/calwebb_spec2.py", line 119, in process
E               result = self.process_exposure_product(
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/clone/jwst/pipeline/calwebb_spec2.py", line 306, in process_exposure_product
E               x1d = self.photom(x1d)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/stpipe/step.py", line 487, in run
E               self.save_model(result, idx=idx, format=self.name_format)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/stpipe/step.py", line 967, in save_model
E               output_path = model.save(
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/stdatamodels/model_base.py", line 523, in save
E               self.to_fits(output_path, *args, **kwargs)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/stdatamodels/model_base.py", line 649, in to_fits
E               ff.write_to(init, *args, **kwargs)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/fits_embed.py", line 339, in write_to
E               self._update_asdf_extension(
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/fits_embed.py", line 311, in _update_asdf_extension
E               super().write_to(
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/asdf.py", line 1359, in write_to
E               self._serial_write(fd, pad_blocks, include_block_index)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/asdf.py", line 1099, in _serial_write
E               self._write_tree(self._tree, fd, pad_blocks)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/asdf.py", line 1072, in _write_tree
E               yamlutil.dump_tree(
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/yamlutil.py", line 400, in dump_tree
E               yaml.dump_all(
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/__init__.py", line 241, in dump_all
E               dumper.represent(data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 27, in represent
E               node = self.represent_data(data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/yamlutil.py", line 43, in represent_data
E               node = super().represent_data(data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 48, in represent_data
E               node = self.yaml_representers[data_types[0]](self, data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/yamlutil.py", line 63, in represent_mapping
E               node = super(AsdfDumper, dumper).represent_mapping(None, mapping.data, flow_style)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 118, in represent_mapping
E               node_value = self.represent_data(item_value)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/yamlutil.py", line 43, in represent_data
E               node = super().represent_data(data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 48, in represent_data
E               node = self.yaml_representers[data_types[0]](self, data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 207, in represent_dict
E               return self.represent_mapping('tag:yaml.org,2002:map', data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 118, in represent_mapping
E               node_value = self.represent_data(item_value)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/yamlutil.py", line 43, in represent_data
E               node = super().represent_data(data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 48, in represent_data
E               node = self.yaml_representers[data_types[0]](self, data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 207, in represent_dict
E               return self.represent_mapping('tag:yaml.org,2002:map', data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 118, in represent_mapping
E               node_value = self.represent_data(item_value)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/asdf/yamlutil.py", line 43, in represent_data
E               node = super().represent_data(data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 58, in represent_data
E               node = self.yaml_representers[None](self, data)
E             File "/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/miniconda/envs/tmp_env0/lib/python3.9/site-packages/yaml/representer.py", line 231, in represent_undefined
E               raise RepresenterError("cannot represent an object", data)
E           yaml.representer.RepresenterError: ('cannot represent an object', 'model')

/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests@4/clone/jwst/pipeline/calwebb_spec2.py:137: RuntimeError
```
</details>

**Comment by hbushouse** [comment]
Still working on trying to figure out what's causing the 4 NIRISS SOSS regtests to fail with this. Am systematically working my way through using different versions of numpy and asdf to see which one is causing the issue. It's failing at the very end of processing in those tests, when trying to save the resulting data model to a file.

**Comment by hbushouse** [comment]
To add to the triaging of the error, it's coming from the point in the calwebb_spec2 pipeline where the photom step tries to save its resulting datamodel to disk, going through all the usual stpipe/step/datamodels/asdf/yaml/etc. layers to do so. However, the error only occurs when running the pipeline with all the extra options turned on for the extract_1d step, as seen here: https://github.com/spacetelescope/jwst/blob/master/jwst/regtest/test_niriss_soss.py#L44
If I run the same calwebb_spec2 pipeline on the same data, without all those extra params enabled, it does not error.

@tapastro You want to get involved in this?

**Comment by braingram** [comment]
I believe this is a bug in stpipe where it should at some point convert FromCommandLine instances back to strs. I believe that converting `bad_pix` to a string here might stop the tests from failing:
https://github.com/spacetelescope/jwst/blob/522db0e8a3d6280191c1580b1c4914e0603f12b1/jwst/extract_1d/soss_extract/soss_extract.py#L1267
I became quite lost while trying to dig through the previous regression test runs to determine what conditions lead to this failure (and if it was a code and/or data change).

I opened a PR with a fix to stpipe that locally fixed the failures in the regression test. I'm not sure why the failure appears to be intermittent but this could just be my lack of understanding what conditions are used for the regression tests and what parameters come from CRDS (does it perhaps override the 'model' argument sometimes which allows the test to pass?).

**Comment by hbushouse** [comment]
I'm going to approve and merge this PR, because we obviously need to change the deprecated instances of `np.int` and the regtest failures from this are not as numerous as without it (and it looks like @braingram may have a fix for the remaining ones via stpipe).

**Review by hbushouse — APPROVED** [review]

**Pull request merged**
