### PR TITLE
Add logging of the found quaternion information to set_telescope_pointing 

### PR DESCRIPTION
**Pull request by stscieisenhamer**
Driven by SDP analysis needs, added the logging of the quaternion information to `set_telescope_pointing`.

### CODE REVIEW

**Review by tapastro — APPROVED** [review]

**Comment by tapastro** [comment]
Codecov is showing this decreases coverage substantially, but I can't get the service to show me coverage differences. Is this buggy behavior on codecov's part?

**Comment by jdavies-st** [comment]
Because this hasn't been rebased to something recent on `master`, codecov gets confused.  Would be nice to make this less dependent on that.

**Comment by jdavies-st** [comment]
And it looks like it doesn't currently have a way to say, always compare the current CI tests with the last CI run on HEAD of `master`.

https://community.codecov.io/t/set-base-commit/1014/8

For our workflow, that would be the most reliable.

What we are seeing in this PR is that the commits from 22 days ago are being merged into master and we're running CI on it, and then that is being compared to the commit of last CI success on master before this was branched off from 22 days ago.  So essentially it it comparing coverage in this PR to coverage in the repo from 22 days ago, but since we deleted a ton of well-tested code in the last 22 days (removing core `jwst.datamodels`) the overall coverage of the whole package has gone down in that period.

So an odd confluence of events.

Rebasing would fix all this.

**Comment by stscieisenhamer** [comment]
So, if one wants to get accurate coverage, a rebase will need be always done.

**Comment by jdavies-st** [comment]
Right.  Or merging master into the the branch.  😱

**Comment by stscieisenhamer** [comment]
> Right. Or merging master into the the branch. 😱

well, if one is going to go that route, there is always --force...

**Pull request merged**
