### PR TITLE
use Python 3.11 in Jenkins job

### PR DESCRIPTION
**Pull request by zacharyburnett**
Resolves [SPB-1305](https://jira.stsci.edu/browse/SPB-1305)

use Python 3.11 in regression tests on Jenkins @BGannon2 

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by zacharyburnett** [comment]
regtest run at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/594/

**Review by nden — APPROVED** [review]
LGTM. What's happening with the macosx tests?

**Comment by zacharyburnett** [comment]
> LGTM. What's happening with the macosx tests?

@WilliamJamieson pointed out that we don't need to be testing MacOS for *every* python version for every commit, only one version. We only have a finite amount of GitHub-hosted runners assigned to the organization for public repos, so tests often wait for runners to be available. This should alleviate that

**Comment by zacharyburnett** [comment]
> LGTM. What's happening with the macosx tests?

They should be enabled from https://github.com/spacetelescope/jwst/pull/7445

**Review by nden — CHANGES_REQUESTED** [review]
Actually, would it be better to leave one of the jobs running with Py 3.9, what is currently used in OPS?

**Review by nden — APPROVED** [review]

**Pull request merged**
