### PR TITLE
JP-3653: Nsclean speedup

### LINKED ISSUE #8548: Improve runtime of NSClean step
_Issue [JP-3653](https://jira.stsci.edu/browse/JP-3653) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

Filing this ticket based on an email thread with [Timothy Brandt](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tbrandt), and pasting below an excerpt of that conversation:

As noted during the meeting, NSClean takes around 1 minute to run on a rate file on a good laptop.  Of this, about 35 seconds (on my laptop) are spent constructing the mask, and about 20 seconds are spent fitting the background.  The mask construction only needs to happen once if we are applying this correction at the group level (we would just need to add a mask for jumps at the group level, but we would already know where those are).  Then, for the background fitting, it is possible to make three tiny changes that are fully mathematically equivalent but that together gain a factor of about 15 in speedup over the current implementation.  They are:

<https://github.com/spacetelescope/jwst/blob/4fcb915efa12b42ad00c6ad89cbc4ed3928195e5/jwst/nsclean/lib.py#L137>

Change

p = np.diag(self.P[y][self.mask[y]])  # Weights

to

p = self.P[y][self.mask[y]]  # Weights

(i.e. don’t construct a huge matrix with almost all zeros)

 

<https://github.com/spacetelescope/jwst/blob/4fcb915efa12b42ad00c6ad89cbc4ed3928195e5/jwst/nsclean/lib.py#L167>

Change

A = np.matmul(p, B)

to

A = B*p[:, np.newaxis]

(i.e. don’t do the full multiplication by a huge diagonal matrix)

 

<https://github.com/spacetelescope/jwst/blob/4fcb915efa12b42ad00c6ad89cbc4ed3928195e5/jwst/nsclean/lib.py#L175>

Change

rfft[:k.shape[1]] = np.matmul(np.matmul(pinv_PB, p), d)

to

rfft[:k.shape[1]] = np.matmul(pinv_PB, p*d)

(use the associativity of matrix multiplication to multiply two vectors rather than two matrices)

 

This is because p is diagonal, so there is no reason to perform a full multiplication by the giant matrix, or even to create such a giant matrix in the first place.

 

With these changes, the computed background is identical but the computational cost for the background fit is just over 1 second on my laptop.  At that point I think it is no longer any problem to apply NSClean at the group level.  (DRL editorial note- this last is a potential future change).

### PR DESCRIPTION
**Pull request by t-brandt**
Resolves [JP-3653](https://jira.stsci.edu/browse/JP-3653)

Closes #8548 

This PR improves the run time of the NSClean algorithm (not counting the time to construct a pixel mask in NIRSpec) by a factor between 10 and 20.  This is achieved by representing a diagonal weight matrix as a vector and using vector multiplication and broadcasting to achieve equivalent results without extra multiplications by zero and additions of zero.  The changes are entirely within NSClean.fit().  Nothing outside of this routine appears any different, and I have verified that the results of the calculation are the same.

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by drlaw1558** [comment]
@t-brandt Looks good to me; can you please add a change log entry?
@hbushouse Can you please kick off a regression test run for this?

**Comment by t-brandt** [comment]
Ok, I updated CHANGES.rst.

**Comment by drlaw1558** [comment]
Thanks- minor comment that the number of dashes underneath the title 'nsclean' should be the same number of characters as the step name.  I'm not honestly sure why, but @hbushouse has frequently had to remind me about it.

**Comment by hbushouse** [comment]
> Thanks- minor comment that the number of dashes underneath the title 'nsclean' should be the same number of characters as the step name. I'm not honestly sure why, but @hbushouse has frequently had to remind me about it.

The number of underline characters needs to be at least as long as the title above it, but can be longer (without doing harm). It just can't be *shorter* or the sphinx parser will barf.

**Comment by t-brandt** [comment]
Ok, I adjusted the number of dashes.

**Comment by braingram** [comment]
I tried to run regtests for this PR:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/1513/tests
Unfortunately there are many errors that look unrelated (mostly in `fgs` related tests) but I'm not sure what's causing them. Here's a snippet from the traceback:
```
        # Make the query
        params = {'pattern': pattern}
        with requests.get(search_url, params=params, headers=headers) as r:
>           url_paths = r.json()['files']
E           KeyError: 'files'
/data1/jenkins/workspace/RT/JWST-Developers-Pull-Requests/clone/jwst/regtest/regtestdata.py:500: KeyError
```

**Comment by melanieclarke** [comment]
It looks like these changes are only in the NSClean class.  Is it possible to make similar changes in the NSCleanSubarray class too?  I'm wondering if this would enable support for the ALLSLITS subarray - right now, it uses so much memory that it crashes the kernel if attempted, so support for this subarray is explicitly turned off.

**Comment by t-brandt** [comment]
@melanieclarke The NSCleanSubarray already does something close to the changes I made.  Unfortunately, I think that the reason it fails is https://github.com/spacetelescope/jwst/blob/41f24b7a4ade69a77d294bc759dd07a80c28d09f/jwst/nsclean/lib.py#L471
This results in a matrix of size npix x npix (see https://github.com/spacetelescope/jwst/blob/41f24b7a4ade69a77d294bc759dd07a80c28d09f/jwst/nsclean/lib.py#L465)
If a subarray is 1000x100 pixels, for example, then Line 471 referenced above produces a matrix with 1e10 elements, which may not fit in RAM.

This problem does not affect the full array version of NSClean because that operates row-by-row, so that there are never more than 2048 pixels to be fit simultaneously, meaning that the equivalent matrix is at most 2048^2:
https://github.com/spacetelescope/jwst/blob/41f24b7a4ade69a77d294bc759dd07a80c28d09f/jwst/nsclean/lib.py#L163

This array size/memory issue in NSCleanSubarray can be fixed, but not quite so simply as with the pull request here.  If it is a priority for the mission I can spend a bit more time to propose a fix.

**Comment by drlaw1558** [comment]
Maybe I'm missing something, but can we simply swap subarray mode to run row-by-row as well?

**Comment by t-brandt** [comment]
@drlaw1558 Yes, we can do that.  The best thing is probably to do something intermediate: to process as many rows simultaneously as we think we can profitably fit the Fourier modes.  Assuming I am interpreting Bernie's code right, line
https://github.com/spacetelescope/jwst/blob/41f24b7a4ade69a77d294bc759dd07a80c28d09f/jwst/nsclean/lib.py#L336
defines the cutoff and cuton frequencies as ~50 kHz and ~1 kHz, which would correspond to 2 pixels and 100 pixels.  So that would imply that doing a few rows at a time would be best, I think, with the number depending on subarray size.  I don't think this would be a ton of work to implement, but I think it would be good to consult with Bernie to confirm my intuition.  We might then compute backgrounds over overlapping regions and then use weighted averages to construct a smooth combined background.

**Comment by drlaw1558** [comment]
@t-brandt Sounds like that's sufficiently different that it makes sense to consider separately rather than tying it to the work currently here.  I'll file a separate ticket to track it.

**Comment by hbushouse** [comment]
Another regtest run started at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1524

**Comment by hbushouse** [comment]
Regtest run https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1525/ had no failures or differences, so this looks good.

**Review by hbushouse — APPROVED** [review]

**Pull request merged**
