### PR TITLE
ensure log payload passed to `MultilineLogger` is a string

### LINKED ISSUE #6407: Log raises TypeError when matplotlib usetex=True
Hi, our team has been using `jwst` to produce a transiting exoplanet data reduction pipeline, and we've encountered an error (see below) when we set `rc('text', usetex=True)` for matplotlib plotting and `jwst ` logging is used. 

The error occurs because when this setting is enabled, the log is passed a bytes like object at some point. The solution we've identified is to add:

```
if type(msg)==bytes:
    msg = msg.decode()
```

immediately prior to Line 158 in the `log_config.py` file. I opted not to submit this as a pull request as I thought you'd want to look at things on your end first, hopefully that's okay! Let me know if you need any more information from us. 

```
Generating x1dints figure
Traceback (most recent call last):
  File "/Users/acarter/Documents/TRANSITS/EUREKA/TESTING_TAYLOR/run_eureka.py", line 12, in <module>
    s2_meta = s2.run_eurekaS2(eventlabel)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 164, in run_eurekaS2
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/pyplot.py", line 966, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/figure.py", line 3015, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2230, in print_figure
    self.figure.draw(renderer)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/figure.py", line 2790, in draw
    mimage._draw_list_compositing_images(
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2881, in draw
    self._update_title_position(renderer)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2822, in _update_title_position
    if title.get_window_extent(renderer).ymin < top:
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/text.py", line 903, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/text.py", line 306, in _get_layout
    _, lp_h, lp_d = renderer.get_text_width_height_descent(
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 229, in get_text_width_height_descent
    w, h, d = texmanager.get_text_width_height_descent(
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/texmanager.py", line 399, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/texmanager.py", line 291, in make_dvi
    self._run_checked_subprocess(
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/texmanager.py", line 268, in _run_checked_subprocess
    _log.debug(report)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/jwst/associations/lib/log_config.py", line 158, in log
    for line in msg.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```

### PR DESCRIPTION
**Pull request by zacharyburnett**
Closes #6407 

This PR addresses the issue in #6407 where initializing `matplotlib` logging with `usetex=True` would cause the log message passed to the multiline logging handler to be `bytes` instead of the expected `str`

**Checklist for maintainers**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] ~Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)~

### CODE REVIEW

**Comment by zacharyburnett** [comment]
regtests running at https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/758/pipeline

**Comment by melanieclarke** [comment]
@zacharyburnett @braingram - is this change still needed?

**Comment by braingram** [comment]
I'd like to see if removing `MultilineLogger` is an option. I started a draft PR that does that https://github.com/spacetelescope/jwst/pull/8694 (we'll see what the regression tests show). I'll update that PR with the reasons for it's removal.

**Comment by melanieclarke** [comment]
Closing: the issue was resolved by removing the MultiLineLogger in #8781

**Pull request closed without merging**
