### PR TITLE
Update regression tests to remove missing files from tests

### PR DESCRIPTION
**Pull request by tapastro**
This PR addresses failing regression tests resulting from updated detector1 parameter reference files delivered by NIRCam and MIRI. The new reference files skip the refpix step for MIRI images and skip the persistence step for NIRCam data, resulting in test errors on missing `{..}_refpix.fits` and `{..}_trapsfilled.fits` files. This PR removes those suffixes/filenames from the test diffs.

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [x] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by tapastro** [comment]
After okifying the downstream results (i.e. ramp, rate, cal) to match the missing persistence entries, regtest run started here to verify the errors are no longer present: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1679/

**Review by melanieclarke — COMMENTED** [review]
These changes look right to me.  There are many regression test failures - are those all expected, after your changes?

Should we also delete the files from the truth directories on artifactory, to tidy up?

**Comment by tapastro** [comment]
To be safe, I've started a fresh run after okify'ing the new failures resulting from new CRDS context updates. Here: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/

I can clean up the truth files once merged.

**Comment by melanieclarke** [comment]
I think the regtests look right now - build [1680](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1680/)?   The LRS ones are expected with the rmap that needs fixing and the "full_run" one looks like it's probably related to the NIRCam READPATT.  Is that right?

**Pull request merged**
