### PR TITLE
Documentation updates for WFSS and TSGRISM mode

### PR DESCRIPTION
**Pull request by sosey**
This adds documentation for the updates  in #1710 and #1756

### CODE REVIEW

**Comment by sosey** [comment]
@stscieisenhamer I updated the docs to remove the reference for the segementation image in the association file for WFSS but the associated graphic should also be updated

**Comment by stscieisenhamer** [comment]
Is this the change you were expecting? 
[workflow-wfss.pdf](https://github.com/spacetelescope/jwst/files/2421274/workflow-wfss.pdf)

**Comment by sosey** [comment]
sorry....got lost in my emails! Looks good :)

**Comment by stscieisenhamer** [comment]
well, not a pr on a pr, but the commit with the updated graphics is now there.

**Comment by sosey** [comment]
closes #2534

**Pull request merged**
