### PR TITLE
DOC: Blender rules need __all__

### PR DESCRIPTION
**Pull request by pllim**
Reverts spacetelescope/jwst#6520

Instead of pinning automodapi, just don't try to import everything.

Because I am lazy, I am using GitHub interface. I will fix the `__all__` in subsequent commit.

### CODE REVIEW

**Comment by pllim** [comment]
Yikes, I guess some code is relying on the lack of `__all__` to work... 😬

**Comment by eslavich** [comment]
> Yikes, I guess some code is relying on the lack of __all__ to work... 😬

Those failures are in master too, I think since the rtd build succeeded this will work just fine.

**Comment by pllim** [comment]
@eslavich , good to know! I was afraid `blendrules` has dark magic like `stpyfits`. I am glad you replied before I went too deep into the rabbit hole...

**Comment by pllim** [comment]
p.s. Who merged PR with failing CI? 😜

**Review by eslavich — APPROVED** [review]
LGTM, way better than pinning the dependency.  Thanks!

**Comment by pllim** [comment]
Not saying that astropy/sphinx-automodapi#141 doesn't need to be fix but I have no idea when that will happen.

**Review by hbushouse — APPROVED** [review]
LGTM. Are we agreed that this is the final/best solution?

**Comment by hbushouse** [comment]
All of the CI failures are unrelated and due to something we're also trying to fix in a linearity step test.

**Pull request merged**
