### PR TITLE
remove non-working or out-dated scripts

### PR DESCRIPTION
**Pull request by braingram**
This PR removes a number of [scripts](https://github.com/spacetelescope/jwst/tree/master/jwst/scripts) that are:
- not working due to API changes (for example [resample.py](https://github.com/spacetelescope/jwst/blob/ce9a135f3bc6bba21e95dd47a91fc4d9ba5a1991/jwst/scripts/resample.py#L60))
- redundant to `strun` (for example [dq_init.py](https://github.com/spacetelescope/jwst/blob/ce9a135f3bc6bba21e95dd47a91fc4d9ba5a1991/jwst/scripts/dqinit.py#L46))

Regression tests: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1573/
showed only the 2 command, random, and unrelated errors

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by braingram** [comment]
Closing and re-opening to trigger CI.

**Comment by braingram** [comment]
I'm hoping @nden might know some history of these scripts. If it's helpful I'm happy to go through the removed scripts and describe:
- what command I attempted for each script (several failed during the imports due to missing modules)
- the error encountered for each script

**Review by nden — APPROVED** [review]

**Comment by melanieclarke** [comment]
Since we're deleting things, should we also remove the remaining fits_generator script (create_data) and the associated jwst.fits_generator module?  As discussed on #8652, the module is no longer used and also contains some broken code.

**Comment by braingram** [comment]
> Since we're deleting things, should we also remove the remaining fits_generator script (create_data) and the associated jwst.fits_generator module? As discussed on #8652, the module is no longer used and also contains some broken code.

I'm not familiar with the fits_generator. It does look largely untested and unused but I haven't given it a thorough look. The `create_data` script at least ran, output help text when provided with no arguments and did (apparently nothing) when provided a directory 🤷

**Comment by melanieclarke** [comment]
> I'm not familiar with the fits_generator. It does look largely untested and unused but I haven't given it a thorough look.

Okay, we can save it for another time.  Thanks!

**Review by melanieclarke — APPROVED** [review]

**Comment by braingram** [comment]
> Okay, we can save it for another time. Thanks!

Works for me. I opened an issue to track investigating it's removal:
https://github.com/spacetelescope/jwst/issues/8656

Hopefully it will also serve as a notice (for anyone watching) that we're considering removing it.

**Pull request merged**
