### PR TITLE
Only calculate S_REGION if looking at the sky JP-1115

### LINKED ISSUE #4219: Error in extract_2d step when processing NRS_LAMP exposures
Issue [JP-1115](https://jira.stsci.edu/browse/JP-1115) was created by Howard Bushouse:

DMS testing of CAL 0.14.0 has encountered an error in the calwebb_nrslamp-spec2 extract_2d step when processing NRS_LAMP exposures:
{code:java}
2019-11-03 08:02:28,969 - stpipe.Spec2NRSLamp.extract_2d - INFO - EXP_TYPE is NRS_LAMP
2019-11-03 08:02:28,970 - stpipe.Spec2NRSLamp.extract_2d - INFO - Skipping wavecorr correction for EXP_TYPE NRS_LAMP
2019-11-03 08:02:29,736 - stpipe.Spec2NRSLamp.extract_2d - INFO - Name of subarray extracted: S200A1
2019-11-03 08:02:29,737 - stpipe.Spec2NRSLamp.extract_2d - INFO - Subarray x-extents are: 816 2048
2019-11-03 08:02:29,737 - stpipe.Spec2NRSLamp.extract_2d - INFO - Subarray y-extents are: 1060 1122
2019-11-03 08:02:29,989 - stpipe.Spec2NRSLamp.extract_2d - INFO - Input model type is ImageModel
2019-11-03 08:02:30,013 - stpipe.Spec2NRSLamp.extract_2d - INFO - Slit S200A1: Wavelength zero-point correction was not applied.
2019-11-03 08:02:30,016 - stpipe.Spec2NRSLamp.extract_2d - INFO - slit.ymin -0.55
2019-11-03 08:02:30,016 - stpipe.Spec2NRSLamp.extract_2d - INFO - set slit_attributes completed
Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/gwcs/wcs.py", line 108, in get_transform
    to_ind = self._get_frame_index(to_frame)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/gwcs/wcs.py", line 191, in _get_frame_index
    return frame_names.index(frame)
ValueError: 'world' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_spec2.py", line 95, in process
    asn.filename
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_spec2.py", line 241, in process_exposure_product
    input = self.extract_2d(input)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 398, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/jwst/extract_2d/extract_2d_step.py", line 38, in process
    extract_height=self.extract_height)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/jwst/extract_2d/extract_2d.py", line 64, in extract2d
    reference_files=reference_files)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/jwst/extract_2d/nirspec.py", line 94, in nrs_extract2d
    util.update_s_region_nrs_slit(new_model)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/jwst/assign_wcs/util.py", line 813, in update_s_region_nrs_slit
    footprint = compute_footprint_nrs_slit(slit)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/jwst/assign_wcs/util.py", line 800, in compute_footprint_nrs_slit
    slit2world = slit.meta.wcs.get_transform("slit_frame", "world")
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.14.0-py37/lib/python3.7/site-packages/gwcs/wcs.py", line 110, in get_transform
    raise CoordinateFrameError("Frame {0} is not in the available frames".format(to_frame))
gwcs.utils.CoordinateFrameError: Frame world is not in the available frames
{code}

### PR DESCRIPTION
**Pull request by stscirij**
Fixes #4219

### CODE REVIEW

**Comment by nden** [comment]
Can you also wrap in a similar way the corresponding code when `EXP_TYPE==NRS_BRIGHTOBJ`, starting at line 76. Otherwise looks good.

**Comment by stscirij** [comment]
I wondered about that, but shouldn't NRS_BRIGHTOBJ data always have a 'world' frame?  And if it doesn't, shouldn't we raise an exception?

**Comment by nden** [comment]
So `NRS_BRIGHTOBJ` will never be used in calibration? Possible but I am not aware of such restriction.
@hbushouse ?

**Comment by hbushouse** [comment]
I doubt that NRS_BRIGHTOBJ would be used for calibration, so it should be safe (for now).

**Pull request merged**
