### PR TITLE
Tweak wavelength preselection, add some comments

### PR DESCRIPTION
**Pull request by drlaw1558**
Made a minor tweak to the wavelength preselection in order to address https://jira.stsci.edu/browse/JP-1840

Additionally fixed some typos in comments, and added a few additional comments.

### CODE REVIEW

**Comment by drlaw1558** [comment]
@jemorrison @hbushouse 
Tagging the two of you on the PR to fix an issue that I've been looking into the last couple of days.  Should be a pretty minor tweak, but let me know what you think.

**Review by jemorrison — APPROVED** [review]
Thanks for taking the time to clean up typos in comments. 

The code  looks good.

**Comment by hbushouse** [comment]
After merging this PR I ran our full regtest suite on it and got a few differences in results - as expected - but also got some errors. The traceback is:
```
E           RuntimeError: Traceback (most recent call last):
E             File "/data1/jenkins/workspace/RT/JWST/clone/jwst/pipeline/calwebb_spec2.py", line 110, in process
E               result = self.process_exposure_product(
E             File "/data1/jenkins/workspace/RT/JWST/clone/jwst/pipeline/calwebb_spec2.py", line 268, in process_exposure_product
E               resampled = self.cube_build(calibrated)
E             File "/data1/jenkins/workspace/RT/JWST/clone/jwst/stpipe/step.py", line 400, in run
E               step_result = self.process(*args)
E             File "/data1/jenkins/workspace/RT/JWST/clone/jwst/cube_build/cube_build_step.py", line 342, in process
E               cube_result  = thiscube.build_ifucube()
E             File "/data1/jenkins/workspace/RT/JWST/clone/jwst/cube_build/ifu_cube.py", line 642, in build_ifucube
E               pixelresult = self.map_detector_to_outputframe(this_par1,
E             File "/data1/jenkins/workspace/RT/JWST/clone/jwst/cube_build/ifu_cube.py", line 1538, in map_detector_to_outputframe
E               min_wave_tolerance = self.crval3 - np.absolute(self.zcoord[1] - self.zcoord[0]) / 2. - self.roiw
E           TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```
which is in one of the new/modified lines of code. Looks like one of the 3 variables on the right-hand side of the minus sign is None.

**Comment by drlaw1558** [comment]
Hm, that must be some test case in which self.roiw is undefined.  Is it easy to say which test case that was?

**Comment by hbushouse** [comment]
regtest/test_miri_mrs_spec2

**Comment by hbushouse** [comment]
Yes, this appears to be a case where roiw is not set and hence defaults to zero or None:
```
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - spatial size 0.12999999523162842
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - spectral size None
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - spatial roi 0.3100000023841858
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - wave min and max 5.639999866485596 10.220000267028809
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - linear wavelength False
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - **roiw None**
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - output_type multi
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - scalerad None
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - Number of bands in cube: 2
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - Working on data from 1, medium
2021-01-12 15:28:38,002 - stpipe.Spec2Pipeline.cube_build - DEBUG - number of files 1
```

**Comment by drlaw1558** [comment]
I've found the test and artifactory data going into it- will take a look and see if there's an obvious modification

**Comment by hbushouse** [comment]
You may have already noticed, but the test setup is a little confusing in that it uses an ASN file as input that references a "cal" product, but then the test modifies the file name suffix on the fly so that it actually feeds a "rate" product into calwebb_spec2 (as it should be).

**Comment by hbushouse** [comment]
I can get it to run successfully in a standalone fashion by specifying a non-zero value for the roiw parameter, as opposed to letting it default to zero. So we need some kind of handling for when the user lets it go with the default.

**Comment by jemorrison** [comment]
I pointed bigdata to artifactory.
ran:
pytest --bigdata --basetemp='/Users/morrison/scratch' test_miri_mrs_spec2.py --slow

it ran fine - but I am running this from the branch of the changes I made from JP-1560 #PR5603. Let me try from master.

**Comment by drlaw1558** [comment]
I can see the problem- it's because I didn't consider how multiband cubes don't use the self.roiw framework.  About to check in a PR to fix it, just testing for any unexpected consequences.

**Comment by jemorrison** [comment]
When I ran it from master it crashed.

**Comment by drlaw1558** [comment]
Ok, see https://github.com/spacetelescope/jwst/pull/5615

**Pull request merged**
