### PR TITLE
switch default branch name to main in docs/ci

### PR DESCRIPTION
**Pull request by braingram**
This PR updates the CI and docs to refer to a renamed "main" branch.

Unlike https://github.com/spacetelescope/stdatamodels/pull/247 and https://github.com/spacetelescope/stpipe/pull/136 it is likely that downstream packages are referring to the current default branch. For some period of time (I cannot find a statement that define for how long), github will redirect these requests to the renamed branch.

Known downstream uses will be listed here:
- (broken) link in crds: https://github.com/spacetelescope/crds/pull/1021

For developers, they will need to update their local clones and forks to match the new default branch.

Once the issue of updating packages that use the current jwst default branch is addressed, we should be able to:
- coordinate renaming with all interested parties as mentioned by @nden 
- rename the default branch to "main"
- merge this PR

It's possible codecov may need to be updated to use "main" (if it's not using the default branch).

The order of operations is:
- [ ] rename default branch to "main"
- [ ] merge this PR
- [ ] update [jenkins configuration](https://github.com/spacetelescope/jwst/pull/8210#issuecomment-2223986433)
- [ ] update [github actions](https://github.com/spacetelescope/RegressionTests/blob/02913aebf6edff5c2435408ba7837cf86ad47b6f/.github/workflows/jwst.yml#L113)
- [ ] verify that codecov is using the new default branch

Note that the items in the above checklist after merging this PR can be done in any order and aren't urgent as all will continue to work (with github redirecting requests directed to the old branch to the new branch).

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [x] updated relevant documentation
- [ ] added relevant milestone
- [x] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Review by emolter — COMMENTED** [review]
Generally LGTM.  Changelog needs to be rebased.  The only other place where I see instances that might need to be changed to "main" is in the Jenkinsfiles - can you check those, or is there a reason they don't need updating?

**Comment by braingram** [comment]
> Generally LGTM. Changelog needs to be rebased. The only other place where I see instances that might need to be changed to "main" is in the Jenkinsfiles - can you check those, or is there a reason they don't need updating?

Thanks and good question. Thanks for finding those references to the branch name. I updated them in this PR. @jhunkeler are there other jenkins/bytesalad (or other systems) that will need to be updated for a new default branch name?

**Comment by jhunkeler** [comment]
On the Jenkins side we'd need to change the branch from master to main for each pipeline. Feel free to ping me whenever you want to change this.

**Comment by braingram** [comment]
Rebasing and leaving off a changelog until https://github.com/spacetelescope/jwst/pull/8671 can be merged

**Review by melanieclarke — COMMENTED** [review]
Docs changes look good to me.  It will be nice to get this settled!

What is the status on all the various coordination needed?

**Comment by braingram** [comment]
> Docs changes look good to me. It will be nice to get this settled!
> 
> What is the status on all the various coordination needed?

Thanks. I think we're all set since github will redirect requests to master to main.

**Comment by tapastro** [comment]
I'm happy to get this merged today. If we do so, we'll need to update the Jenkins instances to point to main afterwards, correct @jhunkeler ? Any other blockers remaining pre/post merge?

**Comment by melanieclarke** [comment]
Do the GA regression tests need updating too?

**Comment by braingram** [comment]
> Do the GA regression tests need updating too?

After the branch rename the one reference to 'master' here can be updated:
https://github.com/spacetelescope/RegressionTests/blob/02913aebf6edff5c2435408ba7837cf86ad47b6f/.github/workflows/jwst.yml#L113

I'll update the list in the description with checkboxes.

**Comment by braingram** [comment]
FWIW I do not have permissions to rename the branch (the required first step prior to merging this PR). @tapastro @melanieclarke do either of you have permissions? If not @jhunkeler may.

**Comment by melanieclarke** [comment]
> FWIW I do not have permissions to rename the branch (the required first step prior to merging this PR). @tapastro @melanieclarke do either of you have permissions? If not @jhunkeler may.

It looks like we probably can - jwst-pipeline-maintainers have the admin role - but I'm a little uncomfortable touching the GitHub branches myself. Joe also has admin role, and Zach too.

**Review by melanieclarke — APPROVED** [review]
Okay by me to move forward as @braingram suggests.

**Comment by zacharyburnett** [comment]
alright, I'll go ahead and rename the `master` branch to `main`

**Comment by zacharyburnett** [comment]
done!

**Comment by braingram** [comment]
Thanks @zacharyburnett Would you also force merge this PR?

**Comment by zacharyburnett** [comment]
> Thanks @zacharyburnett Would you also force merge this PR?

UNLIMITED POWER!!!

**Pull request merged**
