### PR TITLE
Switch okify to GitHub Actions

### PR DESCRIPTION
**Pull request by melanieclarke**
Update the okify script to look for regression test artifacts from GitHub Actions instead of Jenkins

**Checklist for PR authors (skip items if you don't have permissions or they are not applicable)**
- [ ] ~added entry in `CHANGES.rst` within the relevant release section~
- [ ] ~updated or added relevant tests~
- [ ] ~updated relevant documentation~
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ~ran regression tests, post a link to the Jenkins job below.~
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] All comments are resolved
- [ ] ~Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)~

### CODE REVIEW

**Comment by melanieclarke** [comment]
@tapastro - based on [similar changes for romancal](https://github.com/spacetelescope/romancal/commit/7ae6c53fee673a828118adea855259721330db83), I think this is what's needed to update our okify script when we're ready to move over to GitHub Actions.

I tested by starting an okify run and it found the artifacts appropriately, but didn't try actually okifying anything.

**Comment by zacharyburnett** [comment]
this raises the question; should we move the `okify` script to a common upstream between `jwst` and `romancal`, so that underlying infrastructure changes are easier to make?

**Comment by melanieclarke** [comment]
There are currently some other differences between the two scripts, but we could probably come to an agreement on which version is preferable.  I'm all in favor of de-duplicating the code.

**Review by zacharyburnett — APPROVED** [review]
this looks good to me, if the devs are willing to switch to GitHub Actions regression tests as canonical

**Comment by zacharyburnett** [comment]
we'll look into consolidating `okify_regtests` later

**Review by tapastro — APPROVED** [review]

**Pull request merged**
