### PR TITLE
PEP8 fixes for pipeline package

### PR DESCRIPTION
**Pull request by hbushouse**
Applied all necessary changes to make flake8 happy and removed all instances of `__version__`.

### CODE REVIEW

**Comment by hbushouse** [comment]
Addresses #2340

**Comment by hbushouse** [comment]
@stscieisenhamer Did mess up something in all the unit tests by removing some imports or something? The jenkins test log is showing a bunch errors like this:
```
SKIP [1] jwst/pipeline/tests/test_calwebb_image2.py:31: "TEST_BIGDATA" environmental not defined. Cannot access test data.

SKIP [1] jwst/pipeline/tests/test_calwebb_image2.py:44: "TEST_BIGDATA" environmental not defined. Cannot access test data.

SKIP [1] jwst/pipeline/tests/test_calwebb_image2.py:67: "TEST_BIGDATA" environmental not defined. Cannot access test data.

SKIP [1] jwst/pipeline/tests/test_calwebb_image2.py:75: "TEST_BIGDATA" environmental not defined. Cannot access test data.

SKIP [1] jwst/pipeline/tests/test_calwebb_image2.py:83: "TEST_BIGDATA" environmental not defined. Cannot access test data.

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2.py:34: Test data not accessible

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2.py:49: Test data not accessible

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2.py:92: Test data not accessible

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2.py:121: Test data not accessible

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2.py:144: Test data not accessible

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2.py:170: Test data not accessible

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2.py:177: Test data not accessible

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py:22: "TEST_BIGDATA" environmental not defined. Cannot access test data.

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py:48: "TEST_BIGDATA" environmental not defined. Cannot access test data.

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py:74: "TEST_BIGDATA" environmental not defined. Cannot access test data.

SKIP [1] jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py:100: "TEST_BIGDATA" environmental not defined. Cannot access test data.
```

**Comment by stscieisenhamer** [comment]
@hbushouse No, these are expected with the unit tests. For the unit tests, the TEST_BIGDATA environment is not defined, on purpose. These are tests that I need to migrate to the nightly regression side of the house, now that the nightly regressions are part of the repo.  They should all be marked SKIPPED.

The one failure has to do with a missing reference file. Since this passed in travis, I would presume this is a one-off, but you might want to rerun the build to see if it happens again. Otherwise, I approve.

**Comment by hbushouse** [comment]
@stscieisenhamer agreed about the 1 actual failure (I hadn't noticed that before). But then here's a more general Jenkins question: How does one manually restart the build/test process? It's easy for the Travis-based tests: just click on the little "Restart build" link on the Travis test page. But I can't find any such facility for the Jenkins tests. I supposed I could use the brute force approach of submitting a benign commit that will automatically restart all CI tests, but that seems a bit over the top. There's got to be a better way.

**Comment by hbushouse** [comment]
The 1 error seems to be an unrelated CRDS connection hiccup, so I'm merging.

**Pull request merged**
