### PR TITLE
JP-3585: remove deprecated datamodel types

### LINKED ISSUE #8382: Remove long-deprecated unused datamodels
_Issue [JP-3585](https://jira.stsci.edu/browse/JP-3585) was created on JIRA by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter):_

The data model types DrizProductModel, MultiProductModel, and MIRIRampModel have ben listed as deprecated for some time.  This ticket would remove them. 

 

Changes are needed primarily in stdatamodels, but one line in jwst/datamodels/*_init_*.py is also required to remove these from the list of deprecated models.

 

Tests that cover these model types are already being removed by JP-3546; [PR here](https://github.com/spacetelescope/jwst/pull/8320).

### PR DESCRIPTION
**Pull request by emolter**
Resolves [JP-3585](https://jira.stsci.edu/browse/JP-3585)

Closes #8382 

This PR enforces removal of the deprecated stdatamodels model types DrizProductModel, MIRIRampModel, and MultiProductModel.  Most of the changes are in stdatamodels; [see PR here](https://github.com/spacetelescope/stdatamodels/pull/171).  On the jwst side, the only change is to remove the model types from the deprecated list.

**Checklist for maintainers**
- [x] added entry in `CHANGES.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
- [ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)

### CODE REVIEW

**Comment by braingram** [comment]
The corresponding stdatamodels changes have been merged into `main`: https://github.com/spacetelescope/stdatamodels/pull/171

Anything I can do to help bring this out of draft?

**Comment by emolter** [comment]
> The corresponding stdatamodels changes have been merged into `main`: [spacetelescope/stdatamodels#171](https://github.com/spacetelescope/stdatamodels/pull/171)
> 
> Anything I can do to help bring this out of draft?

I just added the changelog entry and moved it out of draft.  It would be helpful if you could review it!
Regression tests [started here](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1378/).

**Review by braingram — APPROVED** [review]
Thanks for making the changes!

Assuming the regtests don't reveal any surprises this looks good to me.

**Review by hbushouse — APPROVED** [review]
Failures in regtest run are unrelated. Everything looks good here.

**Pull request merged**
